### ISSUE TITLE
[Suggestion] Override Getter/Setter annotations

### ISSUE THREAD

**Issue by delverdev** [projectlombok/lombok#1026]
It would be nice if you would implement overriding getter/setter annotations. For example:

```
@Getter
public class Example {

    private int a;

    public int getA() { //override to avoid npe
         return a < 0 ? -1 : a; 
    }    

}
```

**Comment by Maaartinus** [comment]
Just do it. No getter gets generated if there's already one present.

You can also use `@Getter(AccessLevel.NONE)` to disable the generation explicitly.

**Comment by delverdev** [comment]
Well then it is an issue of IntelliJ IDEA plugin, which warns me that I cannot have `@Getter` and simple getter together. Thank you for the answer!
