### ISSUE TITLE
Remove vertical pepper in the background

### ISSUE THREAD

**Issue by ceki** [projectlombok/lombok#1028]
Hello,

I just started reading the lombok documentation. The vertical pepper in the background of every doc page hurts my eyes. I humbly suggest that it be removed.

As a workaround, I currently save the doc pages using Firefox and reopen the saved copy which does not display the pepper.

**Comment by Maaartinus** [comment]
Pepper is indeed dangerous to the eyes. Be really careful with them. As a simpler workaround, you can use FF development mode and disable the rule `#pepper {background-image: ...}` or block `https://projectlombok.org/features/lombok-background.png`.
