### ISSUE TITLE
[Feature Request] @Singular setting to ignore null values

### ISSUE THREAD

**Issue by bschlenk** [projectlombok/lombok#1074]
It would be nice if there was a way to configure `@Singular` to disallow null values from being added to the collection. It makes more sense for the collection to enforce no null values rather than the caller. I recently replaced our hand coded builders with `@Builder` and down the line things broke because we were adding null objects to the builder expecting them to be ignored. I can imagine the `@Singular` annotation looking like this:

``` java
...
@Singular(includeNull = false)
List<String> myStrings;
...


// generated code
public MyBuidler myString(String myString) {
    // includeNull toggles this line
    if (myString == null) return this;

    if (this.myStrings == null) {
        this.myStrings = new java.util.ArrayList<String>();
    }

    this.myStrings.add(myString);
    return this;
}
```

**Comment by alltej** [comment]
I need this feature too. Did anybody had a work-around for the time being?

**Comment by stevenpaligo** [comment]
I would like this feature too.

**Comment by bLindStalker** [comment]
I would like this feature too!!!
also for toBuilder()

example:
``` java
   @Value
   @Builder(toBuilder = true, includeNull = false)
   public class Foo {
        String data;
    }

**Comment by juriad** [comment]
The annotation `lombok.NonNull` allows `TYPE_USE`, therefore the configuration could be as simple as:
```
@Singular
List<@NonNull String> myStrings;

@Singular
Map<@NonNull String, @NonNull Integer>
```
This would affect null checks in both singular and plural methods.

We don't nee an extra parameters to `lombok.Singular`.

**Comment by dkatzel-home** [comment]
@juriad I needed similar functionality and saw your post and Lombok already appears to respect the `lombok.NonNull` annotation on type parameters and it correctly threw a NullPointer when passing null parameters to the builder's singular method.

I am using version `1.18.22`

**Comment by rzwitserloot** [comment]
The problem is, @dkatzel-home and @juriad, that the original question is to __allow__ calling `theBuilder.myString(null)` and that the effect of this is a no-op. What you two are saying is that lombok already throws exceptions.

The feature request is to allow a setting to no-op instead.

I'm just going to decide right now we're not going to add that. I _hate_ that trend that folks think `null` is equivalent to 'do nothing' or 'empty'. No, null is 'unknown' / 'any interaction with this should throw' / 'not set'.

**Comment by MaximeProvost** [comment]
@rzwitserloot Would have been nice to @Builder(includeNull = false) on the builder class with a mixture of @Default. When building an object. It would avoid the explicit Null check. The includeNull behavior would save some logic code.

As for the "that trend that folks think null is equivalent to 'do nothing", well sometimes, you want to do nothing when it's null. Maybe what I want to achieve is not the same as the OP question on the singular ignore Null values, but @bLindStalker idea is a nice one
