### ISSUE TITLE
Question: when I run Delombok, I get lots of compiler errors, can I turn the compiling off?

### ISSUE THREAD

**Issue by talmdal** [projectlombok/lombok#1105]
The code generates fine, but it looks like it is trying to compile the generated code.  Is there a flag that I haven't found that turns compiling off?

Thanks
Tim

**Comment by Tconan99** [comment]
Do you add the file "lombok.config" to root dic. the file's content is "lombok.addGeneratedAnnotation = false". If you added it, can you copy the error message and parse here. Good Luck to you!!!

**Comment by rzwitserloot** [comment]
This issue was added a few pretty serious refactors ago, I very much doubt it's still relevant.
