### ISSUE TITLE
@Builder.Constant missing in the API

### ISSUE THREAD

**Issue by SirGlorg** [projectlombok/lombok#1351]
After bumping to lombok v1.16.16 I noticed, that `@Builder.Default` introduction (https://github.com/rzwitserloot/lombok/commit/bf54986e8a08d246877fae902c58dc41ca2f559b) newly generates these warnings on fields with default values:

@Builder will ignore the initializing expression entirely. If you want the initializing expression to serve as default, add @Builder.Default. if it is not supposed to be settable during building, add @Builder.Constant.

But, the `@Builder.Constant` is unavailable in the API . Can we get one? :)

**Comment by joke** [comment]
Unfortunately the missing ```@Builder.Constant``` is causing builds to fail if you are building with ```-Werror``` because not specifying the annotation causes a warning message.

**Comment by heapifyman** [comment]
If `@Builder.Constant` is not available it should be removed from the documentation. The way it is now is very confusing.

**Comment by SirGlorg** [comment]
I also noticed, that the `@Builder.Default` conflicts with items such as jacksons's `@JsonProperty(defaultValue = X)`. We use both lombok's builder for testing and Jackson's Json for our JSON DTO classes. This change breaks our code, because once a field is annotated with `@Builder.Default`, the jackson's `defaultValue` stops working (it won't be applied).

Jackson version used: com.fasterxml.jackson.core:2.6.3

**Comment by rspilker** [comment]
The warning was indeed confusing, and a left-over from a previous implementation. The correct advice is to make the field final instead.

**Comment by rspilker** [comment]
Updated the warning. Will be in the next release.

**Comment by rspilker** [comment]
It is already available in the [edge release](https://projectlombok.org/download-edge.html)
