### ISSUE TITLE
Possibility to indicate which fields should be taken into account by @RequiredArgsConstructor

### ISSUE THREAD

**Issue by eximius313** [projectlombok/lombok#1376]
As stated [here](https://github.com/rzwitserloot/lombok/issues/1370), possible soulutions could be:
1. Introduce ```@RequiredArg``` annotation
2. of/exclude style: ```@RequiredArgsConstructor(of = {"field1", "field2"})```

Personally I prefer 1st solution since ```@RequiredArgsConstructor``` is already processing ```@NonNull``` annotation, so adding another one shouldn't be much effort.

**Comment by jarekCC** [comment]
For me it will also be very helpful to create constructor with selected fields

**Comment by Maaartinus** [comment]
I'd prefer annotation on the fields like `@RequiredArgsConstructor.Include` and possibly `@RequiredArgsConstructor.Exclude`, so that we don't get more stringly typed parameters.

However, excluding a field would mean that a `final` field gets it default value (which doesn't sound very useful) or that a `@NonNull` field remains `null` (which sounds a bit dangerous). Including a field sounds good.

**Comment by eximius313** [comment]
@Maaartinus, that is why I suggested only ```@RequiredArg``` which clearly indicates that "This field should be included in RequiredArgsConstructor".
Have in mind, that ```RequiredArgsConstructor``` is specific version of the constructor, wher user manually indicates several fields. If somebody has that many fields, that he must use "exclude" rather than "include" than probably he should use Builder instead...

**Comment by Maaartinus** [comment]
@eximius313 I suggested `@RequiredArgsConstructor.Include` as `@*.Include` and `@*.Exclude` is the way I'd like to see other annotations work as well, where `Include` would allow to specify additional options, e.g., `@RequiredArgsConstructor(onParameter=@Inject)`.

> Have in mind, that `RequiredArgsConstructor` is specific version of the constructor, where user manually indicates several fields.

Id' say, it works rather automatically and what this is about is the possibility to manually adjust it for a few fields. For me, *the starting point is what the `@RequiredArgsConstructor` does now.*

> If somebody has that many fields, that he must use "exclude" rather than "include" then probably he should use Builder instead...

See above. With the current behavior as the starting point, an exclusion is per se as probable as inclusion. Anyway, we probably agree, that adding fields is the more important feature.

**Comment by eximius313** [comment]
> Anyway, we probably agree, that adding fields is the more important feature.

yes :)
Any plans to include that in Lombok?

**Comment by eximius313** [comment]
I see, that number of "thumbs up" is constantly growing. 
Any plans to implement that feature in Lombok?

**Comment by eximius313** [comment]
Since both `@EqualsAndHashCode` and `@ToString` uses `onlyExplicitlyIncluded` to take fields into account, maybe it's time to introduce `onlyExplicitlyIncluded` into `@RequiredArgsConstructor`?

**Comment by mstelmaszuk** [comment]
@rzwitserloot I think that is a good point by @eximius313.

**Comment by Maaartinus** [comment]
@mstelmaszuk I'd leave the `@RequiredArgsConstructor` as is and introduce another one. For me, the `@RequiredArgsConstructor` is what I use 90% of time, and when I need a different one, I often use both.

Moreover, `@RequiredArgsConstructor(onlyExplicitlyIncluded=true)` would be the same as `@NoArgsContructor`. That's why I wrote the third paragraph in [the wiki](https://github.com/rzwitserloot/lombok/wiki/FEATURE-IDEA:-Annotation-based-Include-Exclude-for-ToString,-EqualsAHC,-etc#more-ideas)

> Instead of a single @SomeArgsConstructor, there could be three annotations @Custom*Constructor, each working just like the original one, but allowing customization via @*.Include and @*.Exclude. This would cover all common cases like "all-but-one-args-constructor" and "required-args-plus-one-field-constructor".

**Comment by eximius313** [comment]
maybe let's go with `@CustomArgsConstructor` and as it will be pobably `experimental` anyway, If anybody will come up with better solution it can be changed.

**Comment by jcomouth-de** [comment]
Is there a solution to this problem in the meantime?

**Comment by rzwitserloot** [comment]
Not really - the feature's grown in scope some, and our docket's full. For what it's worth, a nice take on this custom constructor idea (if you can somehow make it possible to generate more than one constructor with this, that'd be amazing), and then a PR with the update, would definitely be welcomed.

**Comment by rzwitserloot** [comment]
Feature denied, 'required' is self-describing, so exclude/include wouldn't make sense for it. The idea behind the feature is alive and well though, `@CustomConstructor`, issue #2957.
