### ISSUE TITLE
Using @Delegate works in the IDE but doesn't generate every method compile-time

### ISSUE THREAD

**Issue by NorbiPeti** [projectlombok/lombok#1431]
I have a class using `@Delegate` and *it works perfectly in the IDE*, but when doing a Maven build, it says a method isn't implemented. Using the Maven plugin's generate-sources I found that it generates 263 methods and then errors with the same compilation error as the compile plugin.

The methods to be generated are from an interface and it's superinterfaces - there are around 369 methods.

```
...\DiscordPlayerSender.java:12: error: DiscordPlayerSender is not abstract and does not override abstract method getEffectivePermissions() in Permissible
public class DiscordPlayerSender extends DiscordSenderBase implements Player {
       ^
[INFO] Delombok complete.
```

Enabling verbose mode in the Lombok Maven plugin just gives me a list of the files that it went through after this error.

The interface `Permissible` is extended more than once, as shown below, I wonder if that's related to this issue.

    Player --> HumanEntity --> Permissible
    Player --> CommandSender --> Permissible

Although that seems unlikely as if I exclude it and implement it manually, the error is:

```
...\DiscordPlayerSender.java:19: error: DiscordPlayerSender is not abstract and does not override abstract method isCollidable() in LivingEntity
public class DiscordPlayerSender extends DiscordSenderBase implements Player {
       ^
```

isCollidable() isn't defined in any other superinterface.

It's also unlikely that it's a limit on the number of methods, as it generates the exact same methods if I exclude some interfaces or if I don't unless if I exclude an interface which got implemented by Lombok, in which case it won't implement those but won't attempt to implement more.

**Comment by tterrag1098** [comment]
This is definitely a problem. I'm delegating to a rather complex type (Clojure's `APersistentMap`) and it fails to add delegate methods for supertypes of supertypes, such as `Associative` (superinterface to `IPersistentMap`). Here's the problem class: https://github.com/tterrag1098/K9/blob/86b594d9eea1ab61a0766af530acea205a163090/src/main/java/com/tterrag/k9/util/TypeBindingPersistentMap.java#L42

Note all the `types` I had to add to make it work when building outside the IDE. It compiles and runs fine inside the IDE.

**Comment by chrylis** [comment]
Confirm that this is still a breaking bug with 1.18.12. I have a class delegating to Guava `ImmutableList` and am getting complaints that it `does not override abstract method get(int) in java.util.List`.

**Comment by Rawi01** [comment]
This was fixed in https://github.com/projectlombok/lombok/pull/2459
