### ISSUE TITLE
Can support kotlin?

### ISSUE THREAD

**Issue by z589533** [projectlombok/lombok#1436]
![image](https://user-images.githubusercontent.com/12063612/27983564-4cac9e88-63f2-11e7-9a58-69e0827acfe0.png)
@Slf4j  ....@Data

**Comment by BorzdeG** [comment]
https://github.com/MicroUtils/kotlin-logging ?

**Comment by t1** [comment]
Write an extension function:

```kotlin
fun Any.logger(): Logger {
    val clazz = if (this::class.isCompanion) this::class.java.enclosingClass.kotlin else this::class
    return LoggerFactory.getLogger(clazz)
}
```

Use it like this:
```kotlin
private val log = logger()
```

**Comment by rzwitserloot** [comment]
"Kotlin support" can mean two different things:

* Make lombok annotations in kotlin source files work. This is not and probably never will happen.
* When using `kotlinc`to compile both `kt` and `java` files, make lombok annos in the java files work.

That second one we'd fix if we can. For that see issue #2428

This sounds like the first, so, wontfix.

**Comment by zhangxueyii** [comment]
Hi @rzwitserloot  I wonder why this annotation `@slf4j` will probably never work in Kotlin files? It's really helpful for logging.

**Comment by dstango** [comment]
@zhangxueyii Consider the way lombok works: it joins in with the javac on an intimate level, does annotation processing in a special way and modifies the bytecode. The annotation processing is doing more than the official public api ever intended and offers. So lombok needs to find some special ways to do it, using protected apis, etc.
Thus for your request lombok would have to do the same thing with kotlinc, which is a different beast.
