### ISSUE TITLE
New Feature: Support for Vavr collections in @Singular builders

### ISSUE THREAD

**Issue by EliasJorgensen** [projectlombok/lombok#1733]
I would really like Lombok's builder to fully support Vavr collections.
Therefore, i would like to implement this, if the owner/maintainers find it a fitting feature.

Would this be something that you would like in the project?

@rzwitserloot 
@rspilker

**Comment by zhongdj** [comment]
We have similar need over lombok'Builder + vavr's Option while we build JPA Entity with DDD Entity(Aggregation Root)'s stateData. 

In this case, stateData has Option values(field or getter), and JPA Entity has non-empty field with default values. So we need to jump between Option.none() with default value and their types.

such as:

StateData => JPA Entity
sd -> 
    JPAEntity.builder()
   .fieldX(sd.optionValue.getOrElse(defaultValue))
   .build()

JPA Entity => StateData
en ->
   StateData.builder()
   .optionProp( en.getterX == defaultValue ? option.none(), option.some(en.getterX) )
   .build()

it's quite verbose, maybe it is fake requirement, or we need a concise expressive solution.

**Comment by dabraham02124** [comment]
I came here to ask for a vavr Singular as well.  If you don't want to get into the business of supporting every type of collection, you could declare an interface like below, tell the user to instantiate the interface, and let the annotation take a class or an object.

I can't figure out a way to make L a generic on T, but I can see that as actually being helpful if you want to do something a little different
1. like what I _think_ @zhongdj is saying above
2. or maybe you don't actually want to keep the list, but to generate an average of all the elements that were added.

```
     public interface SingularCollectionCreator<T, L> {
        public void addElement(T t);
        public void clear();
        public L createCollection();
    }
```

**Comment by rzwitserloot** [comment]
Vavr is _very much_ dancing to a completely different tune from the rest of the OpenJDK world, and every new java release means vavr is off on its own little planet a little more. Almost everything it does is either something OpenJDK is going to add at some point, or more likely, OpenJDK adds something different that caters to the same problemset.

As a result, I don't use VAVR at all. As far as I know, @rspilker doesn't either.

Thus, we can't possibly agree to this. We've been maintaining lombok for 12 years and intend to maintain it for at least another 12. We can't do that if we have no idea what a feature is even supposed to do.

The stuff I see so far strongly indicates this feature is multiple ballparks removed from being clear, concise, and easily understood even by a non-VAVR user, thus, odds that we'd accept any PR on this is abysmally low.

There is no clear plan, and if someone comes up with one, we have no way to judge if it is fitting for VAVR's needs. It would take some sort of community effort, for example, get the VAVR team itself on board, if they tell us that some 'this is what you write with lombok, and this is what it would delombok too' is the right way to go, that'd be pretty convincing, then we would be able to maintain the feature going forward. Without that - I have no real way to tell and as I think VAVR is just wrong as a point of principle, I don't want to delve into it enough to be capable of determining if any feature proposal fits the bill.

Hence, without that signoff from the core vavr maintenance team itself, I don't see a way forward.
