### ISSUE TITLE
Renaming fields in Eclipse Photon also renames lombok annotations

### ISSUE THREAD

**Issue by manuel-hegner** [projectlombok/lombok#1758]
In Eclipse Photon the ranimg within a class via Alt+Shift+R is broken if the field uses a lombok annotation.
Class example (working)
![1](https://user-images.githubusercontent.com/12272732/42380797-68f133be-812f-11e8-8a2f-e691bcb4077c.png)
Marking the field
![2](https://user-images.githubusercontent.com/12272732/42380800-6a963b74-812f-11e8-9f6f-a706175e3745.png)
Pressing Alt+Shift+R
![3](https://user-images.githubusercontent.com/12272732/42380802-6c265b72-812f-11e8-8590-5f611391ef24.png)
Typing "Renamed"
![4](https://user-images.githubusercontent.com/12272732/42380805-6e0baabe-812f-11e8-90be-86dc874ffd98.png)

This happens if the annotation is on the field directly and if it is on the class level. It occurs at least with @Getter @Setter @XXXConstructor. I did not test others.
The expected behaviour is for annotations not to change.

> Version: Photon Release (4.8.0)
> Build id: 20180619-1200
> Lombok v1.18.0 "Envious Ferret" is installed.

**Comment by Maaartinus** [comment]
I guess, this happens because of occurrences of the field name in the generated code. The generated code claims to be written where the annotation stays. During refactoring, Eclipse replaces all occurrences of the old field name by the new name using this information, without bothering to check the original code.

This happens to `@EqualsAndHashCode` as well and seems to cause #1628, too.

No idea, if Lombok can solve it, but Eclipse surely could.

**Comment by Klaboe** [comment]
It also happens with `@Data`.

Version: Photon Release (4.8.0)
Build id: 20180619-1200
Lombok v1.18.2 "Envious Ferret" is installed.

**Comment by chrischall** [comment]
Workaround is to rename via the Package Explorer.

**Comment by Klaboe** [comment]
For `@Data` looks like it has been fixed with

Version: 2018-09 (4.9.0)
Build id: 20180917-1800
Lombok v1.18.4 "Envious Ferret" is installed.

\o/

But when refactoring the corresponding getter-methods does not seem to update

**Comment by janmaterne** [comment]
Version: 2019-06 (4.12.0)
Build id: 20190614-1200
Lombok: 1.18.8

Tested with @Setter and worked.
After renaming the field, the used (old) setter was marked as invalid.

**Comment by hradecek** [comment]
Not working for inner classes (static or non-static).

```
public class Main {
    public static void main(String... args) {
        System.out.println(new MyDataClass().getFieldOne());
    }

   @Data
   private static class MyDataClass {
        private String fieldOne;
    }
}
```

Renaming `fieldOne` via `Alt+Shift+R` results in:
```
public class Main {
    public static void main(String... args) {
        System.out.println(new MyDataClass().getFieldAnotherOne());
    }
	
    @getFieldAnotherOne
    private static class MyDataClass {
        private String fieldAnotherOne;
    }
}
```
Tested with:

Version: 2020-03 (4.15.0)
Build id: 20200313-1211
Lombok version: 1.18.12
