### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by daotianxiyang** [projectlombok/lombok#2383]
**Describe the bug**
description : 
service could not recieve web params ,but both params are same!!!!

**To Reproduce**
web tools: postman 
------------------------------------------------------------------
```
curl --location --request GET 'http://localhost:8080/test' \
--header 'Content-Type: application/json' \
--data-raw '{
  "bUerId":123,
  "cUserId":123
}'
```
------------------------------------------------------------------
service
------------------------------------------------------------------
```java
import lombok.Data;

@Data
public class ServiceParam{
    private Long bUserId ;
    private Long cUserId;
}
```

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version:1.18.12
 - idea version: 2018.3.5
 - mac
 - jvm :1.8

**Additional context**

**Comment by janrieke** [comment]
A typo? `bUerId` instead of `bUserId`?
Or this? https://stackoverflow.com/questions/51464720/lombok-1-18-0-and-jackson-2-9-6-not-working-together/51465038#51465038

No idea. Most likely not a bug in lombok. Seems to be more appropriate for StackOverflow.

**Comment by daotianxiyang** [comment]
try it !!!
"bUserId":123,
"cUserId":123

**Comment by daotianxiyang** [comment]
You  can try it. I am sure that you must be recurred it!

**Comment by janrieke** [comment]
No, we cannot. Please upload a minimal example project to GitHub that demonstrates this issue.

**Comment by janrieke** [comment]
Did you configure prefixes using `lombok.accessors.prefix` in your `lombok.config`?

**Comment by rzwitserloot** [comment]
@daotianxiyang Maybe a language barrier is making it difficult, but, we need a fully reproducible test case and some explanation about what is wrong.

As written I have no real idea what the problem is, or how to produce it.

close if no further feedback by 2020-03-20.
