### ISSUE TITLE
[BUG] NPE when using two "val"s together with anonymous class instantiation in nested scope

### ISSUE THREAD

**Issue by dttrian** [projectlombok/lombok#2420]
**Describe the bug**
When in the same nested scope there are two `val`s followed by the instantiation of an anonymous class, compiling with javac, a NullPointerException is raised:

```
Exception while resolving: NODE LOCAL (class com.sun.tools.javac.tree.JCTree$JCVariableDecl) @val()
final ___Lombok_VAL_Attrib__ k = 2(RegularFileObject[C:\Dev\lombok-crash-test-case\src\TestCase.java])
java.lang.NullPointerException
        at com.sun.tools.javac.comp.Check$Validator.visitTypeIdent(Check.java:1340)
        at com.sun.tools.javac.tree.JCTree$JCPrimitiveTypeTree.accept(JCTree.java:2084)
        at com.sun.tools.javac.comp.Check$Validator.validateTree(Check.java:1359)
        ....
```

**To Reproduce**
The following Java source can reproduce the problem when compiled with `javac -cp lombok.jar TestCase.java`:
```
import lombok.val;

class TestCase {
	public void func() {
		for (int i = 0; i < 1; ++i) {
			val j = 1;
			val k = 2;

			new TestCase() { };
		}
	}
}
```

**Expected behavior**
It should compile.

**Version info (please complete the following information):**
 - Lombok version: behavior observed both with 1.6.22 and 1.18.12
 - Platform: javac 1.8.0_192

**Additional context**
No problem at all when compiling in Eclipse.

Compilation succeeds even with javac, if any of the following happens:
- one of the `val`s is removed (j or k, it doesn't matter)
- the curly braces are removed after `new TestCase()` thus instantiating a named class instead of an anonymous class
- the for cycle is removed thus removing the nested scope and having the two `val`s and the anonymous class instantiation in the root function scope

**Comment by rspilker** [comment]
We did change something in the `val` handling code while fixing #2358. Can you please check the problem still exists in the [edge release](https://projectlombok.org/download-edge)?

**Comment by dttrian** [comment]
Same problem also with edge release (tried a few minutes ago).
I got the exact same error.
