### ISSUE TITLE
[BUG] @Delegate Methods that have been customized should no longer be generated

### ISSUE THREAD

**Issue by hywr** [projectlombok/lombok#2504]
`

    public interface I {
        String getName();
        int getAge();
    }
    
    @Data
    public class Vo {
        private String name;
        private long age;
    }
    
    @AllArgsConstructor
    public class Adapter implements I {
    
        @Delegate(types = I.class)
        private Vo vo;
    
        //I want to use my own code here,Because vo.getAge() returns a long,But I.getAge() expects a int
        public int getAge(){
            return (int) vo.getAge();
        }
    }
`

**Comment by Rawi01** [comment]
The latest edge version should detect already implemented methods and skip delegating them. So there is no need for `types` or `exclude` anymore. If that doesn't work you can continue to use `types` but in your case you need an additional interface to exclude the `getAge` method.
```java
@AllArgsConstructor
public class Adapter implements I {
    private interface D {
        String getName();
    }

    @Delegate(types = D.class)
    private Vo vo;

    //I want to use my own code here,Because vo.getAge() returns a long,But I.getAge() expects a int
    public int getAge(){
        return (int) vo.getAge();
    }
}
```

**Comment by quaff** [comment]
I confirm `lombok-edge-20200822.021431-1.jar` fixed this.
