### ISSUE TITLE
[BUG]one of properties dont have set mehtod,other fine

### ISSUE THREAD

**Issue by jr981008** [projectlombok/lombok#2523]
![image](https://user-images.githubusercontent.com/20749545/88178234-ab3a3e80-cc5c-11ea-8441-3b1e4edf668f.png)
![image](https://user-images.githubusercontent.com/20749545/88178264-b7be9700-cc5c-11ea-89dd-e7f2a2275b64.png)
![image](https://user-images.githubusercontent.com/20749545/88178301-c4db8600-cc5c-11ea-8477-63f14f6186e3.png)
![image](https://user-images.githubusercontent.com/20749545/88178317-cad16700-cc5c-11ea-9d0e-901138a8640a.png)
all other class and filed  fine ,just these filed can find symbol ,make me confusion ,i clean and rebuild many time ,still not ok 
idea  2020.1  with lomhok 1.18.6

**Comment by AN3Orik** [comment]
Same here. In one moment setters just stop generating. Only getters available =\

**Comment by Rawi01** [comment]
Based on the information you shared I guess that there is something else that breaks compilation. Does it compile if you remove the line that gets marked as error? Have you tried to update lombok? Does it compile outside of InteliJ?

The code you shared only using basic lombok features and there are no special cases so most likely it is not a lombok issue.

Disclaimer: I'm not a project owner.
