### ISSUE TITLE
[FEATURE] Composition builder

### ISSUE THREAD

**Issue by juanmbellini** [projectlombok/lombok#2557]
**Feature description**
Suppose I have the following classes:

```java
@Getter
@Builder
public class User {
    private final String username;
    private final String email;
    private final List<Phone> phones;
    private final String status;
}

@Getter
@Builder
public class Phone {
    private final PhoneType type;
    private final String countryCode;
    private final String areaCode;
    private final String number;
}

public enum PhoneType {
    HOME,
    MOBILE,
    WORK,
    OTHER,
    ;
}
```

It would be great If I could do the following:

```java
User.builder()
    .username("JoeDoe")
    .email("joe.doe@gmail.com")
    .phone() // This returns a Phone builder
        .type(PhoneType.HOME)
        .countryCode("+54")
        .areaCode("11")
        .number("1234-5678")
        .continueUser() // This returns the previous user builder (the Phone builder must hold a reference to it)
    .phone() // This returns a new Phone builder
        .type(PhoneType.OTHER)
        .countryCode("+598")
        .areaCode("42")
        .number("123-4567")
        .continueUser() // Again, this returns the user builder
    .status("SomeStatus")
    .build();
```

The annotation to allow this could be `@Builder.Composition`, or something of the sort. Must be placed in the field you want to allow this. Obviously, the sub-builder (in the example, this is the `Phone.PhoneBuilder`) class must allow holding an "owner" reference. Maybe this could be achieved by subclassing the sub-builder for each use of `@Builder.Composition`, adding in the subclass the owner's field. Or maybe allowing any builder hold an owners reference (with generics).

Note that in the given example, to get the `Phone` builder, I use the `Phone.PhoneBuilder#phone()` method (same name but different arguments as the generated by the `@Singular` annotation). So there should not be any naming conflicts.

I think this allows not explicitly creating a builder each time you want to add an element to the phones list. The method chain is cleaner.

**Target audience**
Any java programmer

**Comment by wimdetroyer** [comment]
After reading https://jonasg.io/posts/object-mother/ under:

> But what if your test requires a specific field in one of the nested custom objects to be in a particular state? [...]

I wondered if lombok had this functionality.

Sadly this does not seem to be the case, and it would definitely help in having a maintainable test architecture. Is there any update on this?

**Comment by rzwitserloot** [comment]
You're asking for a really complex feature.

The update is: Sounds like a nice idea. If someone wants to contribute it, we'd have a look at it. It's not on our shortlist. I'm closing the issue, under the maxim of 'If I doubt it'll be done _by us_ within the next year, it's too much of a drag to keep it around'. But, PRs might be accepted, I don't see any egregious issues with having this as a lombok feature. But, it has to be well thought through, builder as is already steers dangerously close to doing a little too much to still sell itself as boilerplate tool. It's on the right side of the line to be sure, and I see how this can also be on the right side of it. But it's a major feature, and needs major maintenance. At the very least, the PR needs to be well written: The javac _and_ the eclipse version, tests, docs, the works.

**Comment by wimdetroyer** [comment]
Thank you for the reply @rzwitserloot ! 

I definitely didn't want to come off as rude :-) Sorry if it came across that way! I'm aware the time of an OSS maintainer is valuable and it is often a thankless job.
