### ISSUE TITLE
[BUG] @Builder.Default doesn't work with hand-written setter in builder

### ISSUE THREAD

**Issue by Pr0methean** [projectlombok/lombok#2636]
**Describe the bug**
If a field is annotated with `@Builder.Default`, it can't be set by a non-generated method in the builder class. If this use case isn't going to be supported even with a `@NonNull` field (where there isn't a need for an extra field to distinguish "not set" from "set to null"), then it should raise an error at build time.

**To Reproduce**
```
@Value @Builder
public class Example {
  @Builder.Default @NonNull String foo = "";
  public static class ExampleBuilder {
    private String foo;
    public ExampleBuilder foo(String foo) {
      this.foo = foo.toUpperCase();
    }
  }
}
public class ExampleTest {
  @Test public void testFoo() {
    Example example = Example.builder().foo("hello").build();
    assertEquals("HELLO", example.getFoo());
  }
}
```
**Expected behavior**
testFoo passes, or else there is an error or warning at build time.
**Version info (please complete the following information):**
 - Lombok version:
1.18
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.
javac 11.0.8

**Comment by Pr0methean** [comment]
A workaround is to remove `@Builder.Default` and declare the builder field with an initializer.

**Comment by janrieke** [comment]
You have to set `this.foo$set = true;` in your `foo(String)` method.
