### ISSUE TITLE
HEAD build of Lombok gives Javac compile error lombok.javac.apt.Processor is not available

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#267]
_Migrated from Google Code (issue 194)_

**Comment by colinkuo** [comment]
We encountered the same issue in lombok-1.16.6 still. But using @pe.fips 's patch was able to solve the compiler error. 

"You found a bug in lombok; lombok.javac.apt.Processor is not available. Lombok will not run during this compilation: java.lang.ClassNotFoundException: lombok.javac.apt.Processor"

The information of my test bed as below
JDK8 build 51
Ubuntu 14.04
lombok-1.16.6

**Comment by ouaibsky** [comment]
+1 same issue with jdk 8u60 and mvn 3.3.3
Strange it works fine within intellij, 
so it means there is something incomptatible with maven

**Comment by diguage** [comment]
same error。

```
You found a bug in lombok; lombok.javac.apt.Processor is not available. Lombok will not run during this compilation: java.lang.ClassNotFoundException: lombok.javac.apt.Processor
```


```
mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.2", arch: "x86_64", family: "mac"
```

**Comment by lombokissues** [comment]
If you try the edge release, https://projectlombok.org/download-edge.html
you might get more information on the cause of this problem. Since lombok
1.16.0, this processor should not be used anymore. The edge release will
generate a log file containing information of why it is still used.

The correct processor is
`lombok.launch.AnnotationProcessorHider$AnnotationProcessor`

Roel

**Comment by rspilker** [comment]
If you try the [edge release](https://projectlombok.org/download-edge.html), you might get more information on the cause of this problem. Since lombok
1.16.0, this processor should not be used anymore. The edge release will
generate a log file containing information of why it is still used.

The correct processor is `lombok.launch.AnnotationProcessorHider$AnnotationProcessor`
