### ISSUE TITLE
[BUG] @Jacksonized does not copy @JsonUnwrapped to @Builder

### ISSUE THREAD

**Issue by mjustin** [projectlombok/lombok#2736]
## Describe the bug
The [`@Jacksonized`](https://projectlombok.org/features/experimental/Jacksonized) annotation says it "[copies] Jackson-related configuration annotations [...] from the class to the builder class."  However, it does not copy the [`@JsonUnwrapped`](https://fasterxml.github.io/jackson-annotations/javadoc/2.12/com/fasterxml/jackson/annotation/JsonUnwrapped.html) annotation, which results in incorrect deserialization behavior for objects that require it.

### ExampleFile.java

```java
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.json.JsonMapper;
import lombok.*;
import lombok.extern.jackson.Jacksonized;

public class ExampleFile {
    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper objectMapper = JsonMapper.builder().disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES).build();
        WithUnwrapped expected = new WithUnwrapped(new NestedValue("A", "B"));

        String json = "{\"value1\":\"A\",\"value2\":\"B\"}";
        WithUnwrapped deserializedObject = objectMapper.readValue(json, WithUnwrapped.class);
        if (!expected.equals(deserializedObject)) {
            throw new IllegalStateException("Wrong value; was: " + deserializedObject);
        }
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder     // Correct result if these two annotations are commented out
    @Jacksonized // Correct result if these two annotations are commented out
    public static class WithUnwrapped {
        @JsonUnwrapped
        private NestedValue nested;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class NestedValue {
        private String value1;

        private String value2;
    }
}
```

### Reproduction Steps

```
$ curl -s https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.18/lombok-1.18.18.jar -O
$ curl -s https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.1/jackson-annotations-2.12.1.jar -O
$ curl -s https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.1/jackson-core-2.12.1.jar -O
$ curl -s https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.1/jackson-databind-2.12.1.jar -O
$ javac -cp "*" ExampleFile.java
$ java -cp ".:*" ExampleFile
Exception in thread "main" java.lang.IllegalStateException: Wrong value; was: ExampleFile.WithUnwrapped(nested=null)
	at ExampleFile.main(ExampleFile.java:17)
```

### Expected behavior
The `@JsonUnwrapped` annotation should be copied to the builder method.  In the specific example above, this should lead to the JSON value successfully parsing.

### Version info (please complete the following information):
 - Lombok 1.18.18
 - javac 11.0.9.1

**Comment by snystedt** [comment]
I have been facing the same issue with my use case and I took a look at the JacksonizedHandler.

It uses the array defined in HandlerUtils with the following members:

```java
JACKSON_COPY_TO_BUILDER_ANNOTATIONS = Collections.unmodifiableList(Arrays.asList(new String[] {
			"com.fasterxml.jackson.annotation.JsonAutoDetect",
			"com.fasterxml.jackson.annotation.JsonFormat",
			"com.fasterxml.jackson.annotation.JsonIgnoreProperties",
			"com.fasterxml.jackson.annotation.JsonIgnoreType",
			"com.fasterxml.jackson.annotation.JsonPropertyOrder",
			"com.fasterxml.jackson.annotation.JsonRootName",
			"com.fasterxml.jackson.annotation.JsonSubTypes",
			"com.fasterxml.jackson.annotation.JsonTypeInfo",
			"com.fasterxml.jackson.annotation.JsonTypeName",
			"com.fasterxml.jackson.annotation.JsonView",
			"com.fasterxml.jackson.databind.annotation.JsonNaming",
		}));
```

Wouldn't the fix be as simple as adding `"com.fasterxml.jackson.annotation.JsonView"` to this array?

**Comment by janrieke** [comment]
Probably not, because that list is for the builder class, not the setter methods. However, there's another list for that: `COPY_TO_SETTER_ANNOTATIONS`

**Comment by snystedt** [comment]
I just realized the sample above is a bit different from our case.

Our case is something like this:

```java
@Builder
@Jacksonized
public class Foo {
    @JsonUnwrapped
    Bar other;
}
```

If I manually add a builder and annotate the Bar-method as JsonUnwrapped it works as expected.

In this case the suggestion above should be valid, right?

**Comment by snystedt** [comment]
Or is it that you mean to say that the `JACKSON_COPY_TO_BUILDER_ANNOTATIONS` enumerates the annotations that would end up on the actual Builder _class_ and the `COPY_TO_SETTER_ANNOTATIONS` enumerates annotations that would end up on the actual _setter method of the class_?

**Comment by janrieke** [comment]
Exactly.

**Comment by j-klemm** [comment]
Any updates on this @snystedt @janrieke ?

**Comment by rzwitserloot** [comment]
@snystedt I don't use any of these tools so I have to go by what you've all figured out. I don't know what `@JsonUnwrapped` is meant to do. However, if indeed it is the case that it should __always__ be copied straight to the builder's 'setter' method if the field is annotated with it, then yeah, it's as simple as adding it to the list for the `COPY_TO_SETTER_ANNOTATIONS` file. If you're a new contributor, also add yourself to the `AUTHORS` file and that's all that's needed in the PR for this one I think.
