### ISSUE TITLE
[FEATURE]Automatically generate "Getter and Setter" fields and methods within the interface

### ISSUE THREAD

**Issue by 74744747** [projectlombok/lombok#2751]
before:

```
@AbstractData
interface MyInter {
    int getMyInt();
    void setMyInt(int myInt);
}

class MyClass implements MyInter { }
```

after:

```
class MyClass implements MyInter {
    private int myInt;
    public int getMyInt(){ return this.myInt; }
    public void setMyInt(int myInt){ this.myInt = myInt; }
}
```

_Originally posted by @omega09 in https://github.com/rzwitserloot/lombok/issues/1285#issuecomment-277394362_

**Comment by ChrisKohle** [comment]
I'm interested in this functionality

**Comment by rzwitserloot** [comment]
This would require [resolution](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution), hence, no(t anytime soon enough to bother leaving this issue open).
