### ISSUE TITLE
[BUG] Override @JsonIgnore in the subclass not work properly as before.

### ISSUE THREAD

**Issue by ijustyce** [projectlombok/lombok#2778]
**Describe the bug**
Before spring boot v2.1.18.RELEASE I can override @JsonIgnore in the subclass. But from spring boot v2.1.18.RELEASE I can't. And I find spring boot v2.1.18.RELEASE update lombok to 1.18.16.

I have three class and named UserVO, InsertUserVO and UpdateUserVO I want to ignore the ID when create a user and don't ignore while update. Just like the below.

UserVO.java
```java
@Getter
@Setter
public class UserVO {

    private Long id;

    private String name;

    private Integer age;
}
```  

InsertUserVO.java
```java
@Getter
@Setter
public class InsertUserVO extends UserVO {

    @JsonIgnore
    private Long id;
}
```  

UpdateUserVO.java
```java
@Getter
@Setter
public class UpdateUserVO extends InsertUserVO {

    private Long id;
}
```

Before spring boot v2.1.18.RELEASE lombok will generate code like below

![right](https://user-images.githubusercontent.com/6041166/111744459-3dffab80-88c6-11eb-8703-1f70183419b3.png)

But when update to spring boot v2.1.18.RELEASE or latest lombok will generate code like below.

![error](https://user-images.githubusercontent.com/6041166/111744583-69829600-88c6-11eb-8ca0-2a3912c75f5f.png)

I hope to generate code like before. What should I do?

**Comment by Rawi01** [comment]
The only difference between these two classes is the additional annotation on the setter and I think that Jackson ignores the field in both cases. Can you please explain why the annotation is a problem?

**Comment by ijustyce** [comment]
I can't explain why, but Jackson not ignore the field if code generate as before. I have tested it.

**Comment by arbing** [comment]
We've got the same problem

**Comment by janrieke** [comment]
You aren't bound to the Lombok version that spring uses, as Lombok is not a runtime dependency.
Could you switch to the previous Lombok version to verify that this is indeed a Lombok issue?

**Comment by janrieke** [comment]
However, I very much doubt that copying those Jackson annotations automatically is necessary at all. Jackson considers the setter, getter, and field as a single virtual property, and any annotation on any of those should work for all. See https://github.com/FasterXML/jackson-databind for an example.

I can only see two scenarios where copying helps:
1. Builders
2. when getter/setter name generation in Lombok does not match with Jackson (crappy BeanSpec).

**Comment by ijustyce** [comment]
Switch to the Lombok version I used previously fix the issue and I have leave my previous company now, so let's close it.
