### ISSUE TITLE
[BUG] Getters/setters shouldn’t be generated for Optional fields

### ISSUE THREAD

**Issue by 2is10** [projectlombok/lombok#2784]
**Describe the bug**

Getters/setters should not be generated for `Optional` fields.

**To reproduce**

```java
@Getter
@Setter
private Optional<String> foo;
```

**Expected behavior**

```java
private Optional<String> foo;
```

**Actual behavior**

```java
private Optional<String> foo;

public Optional<String> getFoo() {
    return foo;
}

public void setFoo(Optional<String> foo) {
    this.foo = foo;
}
```

**Version info**

- Lombok version 1.18.11 (or any)
- Java 11 (or any)

**Additional context**

Project Lombok has taken [a strong stance](https://github.com/rzwitserloot/lombok/wiki/Language-Design:-Null-vs.-Optional#lomboks-position-on-null-and-optional) against helping developers who use `Optional` as intended—as a return type. Its most popular feature request (a `@Getter` variation that wraps nullable fields in `Optional`) has been rejected repeatedly: #1214, #1957, #2264.

For consistency with its own position, Project Lombok shouldn’t help developers who use `Optional` as a field type. That pattern is [discouraged](https://stackoverflow.com/a/26328555/140743) even by Brian Goetz, who helped add `Optional` to Java:

> You should almost never use it as a field of something or a method parameter.

If Project Lombok is trying to help the Java community by discouraging the use of `Optional`, it should be consistent in that policy. Its current behavior discourages _intended_ uses of `Optional` and promotes _discouraged_ uses of `Optional` as a workaround. This behavior is a disservice to the Java community.

**Comment by ymajoros** [comment]
That would be a breaking change. Also, the community is clearly divided. It's not up to this project (or even to Brian Goetz, with all respect) to decide whether Optional can be used for fields. People that don't want getters for Optional fields already have the option to exclude those fields. Or to not use Optional in fields.

**Comment by emlun** [comment]
Frankly, this "bug report" is just rude. I agree that Optional-`@Getter` support would have been nice (but I have read through most of #1957 and appreciate the arguments against), but you're clearly not arguing in good faith here. We all know that it would certainly _not_ be "expected behavior" for `@Getter`, or any other Lombok feature, to handle some magic types differently from others. This does not helpfully contribute to the discussion.

**Comment by 2is10** [comment]
@emlun You’re certainly entitled to your own opinions, as everyone is. I meant what I said. We have developers declaring `Optional` fields (a discouraged use) because of the “We hate `Optional` so we’re going to pretend it doesn’t exist” position that the Lombok team has taken. `Optional` is not like other Java types. It’s context sensitive; it’s meant to be used in some contexts and not others. I would honestly appreciate it if Lombok didn’t generate getters for `Optional` fields (to discourage that antipattern) or had a way to be configured to behave that way.
