### ISSUE TITLE
Optional parameter for method in java

### ISSUE THREAD

**Issue by faouzi-chabchoub** [projectlombok/lombok#2795]
The idea is to add an annotation for a parameter in a method to indicate that has a default value for example:
Lombok:
public void doSomething(String s1, @Default(value="defaultValue") String s2){
	somethingToDo(s1, s2);
}

Vanilla
public void doSomething(String s1){
	doSomething(s1, "defaultValue");
}
public void doSomething(String s1, String s2){
	somethingToDo(s1, s2);
}
this will be cool to add to Lombok thx for

**Comment by janrieke** [comment]
Duplikate of #2316.
