### ISSUE TITLE
[FEATURE] split access levels in builder

### ISSUE THREAD

**Issue by borsch** [projectlombok/lombok#2817]
**Describe the feature**
Sometimes I want to extends a builder generated by lombok. Also I would like to hide this generated builder(make it private) and only show my custom builder
Example:

```
@Builder(access = AccessLevel.PRIVATE)
public class MyObject {

  private String field1;
  private String field2;

  public static MyCustomObjectBuilder builder() {
    return new MyCustomObjectBuilder();
  }

  public static class MyCustomObjectBuilder extends MyObjectBuilder {

    public MyCustomObjectBuilder doSomeAction(){
      // build another type of object/ custom validation / etc.
      // do something
      return this;
    }

  }

}
```

Because of `access = AccessLevel.PRIVATE` I can't access methods of hidden builder

```
MyObject.builder()        <-- use custom builder
  .doSomeAction()         <-- this is OK
  .field1("value")        <-- this throws compile time exception
  .build();
```

**Feature request:**
It would be nice if there will be a way to configure access level separately: `@Builder(access = AccessLevel.PRIVATE, methodAccessLevel = AccessLevel.PUBLIC)`

**Describe the target audience**
Anyone who need to extend standard builder and hide a standard one

**Comment by Rawi01** [comment]
If you pre-define the builder lombok detects that one and merges it changes into your own implementation.

Example:
```java
@Builder
public class MyObject {

  private String field1;
  private String field2;

  public static class MyObjectBuilder {

    public MyObjectBuilder doSomeAction(){
      // build another type of object/ custom validation / etc.
      // do something
      return this;
    }

  }
}
```
If, for some reason, you have to extend the generated builder you can still define an empty `private static class MyObjectBuilder { }` to change the access level of the builder.
