### ISSUE TITLE
[FEATURE] IDEA 2021 Can't install lombok

### ISSUE THREAD

**Issue by bestitxq** [projectlombok/lombok#2820]
The latest version of Lombok 1.18.20 IDEA 2021 Build is not compatible. It cannot be found for Lombok, and previous versions cannot be installed  #2425

**Comment by janrieke** [comment]
You're in the wrong project.
However, the IntelliJ Lombok plugin is built-in in recent IntelliJ versions. No need to install it any more.

**Comment by RathnamSai** [comment]
Today installed 2021 intelli Version. not able to find lombok plugin in search box and not able to install. can you check and let me know how do solve this issue
