### ISSUE TITLE
[BUG] @Builder will not work if another method with the same name but different paramaters exists

### ISSUE THREAD

**Issue by Auties00** [projectlombok/lombok#2827]
**Describe the bug**
When using @Builder on a constructor the name of the builder method can be specified using the property builderMethodName, though, if a method with the same name, but different parameters exists, the builder method isn't created. This should happen only if another method with the same parameters and name exists.

**To Reproduce**
Lomboked example source:
```
    record IntHolder(int value){
        @Builder(builderMethodName = "newIntHolder")
        public IntHolder(String value){
            this(Integer.parseInt(value));
        }

        public static IntHolder newIntHolder(int value){
            return new IntHolder(value);
        }
    }
```
Delomboked example source:
```
    record IntHolder(int value){
        public IntHolder(String value){
            this(Integer.parseInt(value));
        }

        public static IntHolder newIntHolder(int value){
            return new IntHolder(value);
        }

        public static class IntHolderBuilder {
            private String value;

            IntHolderBuilder() {
            }

            public IntHolderBuilder value(String value) {
                this.value = value;
                return this;
            }

            public IntHolder build() {
                return new IntHolder(value);
            }

            public String toString() {
                return "LombokTest.IntHolder.IntHolderBuilder(value=" + this.value + ")";
            }
        }
    }
```    
Expected delomboked example source:
```
    record IntHolder(int value){
        public IntHolder(String value){
            this(Integer.parseInt(value));
        }

        public static IntHolder newIntHolder(int value){
            return new IntHolder(value);
        }
        
        public static IntHolderBuilder newIntHolder() {
            return new IntHolderBuilder();
        }
        
        public static class IntHolderBuilder {
            private String value;

            IntHolderBuilder() {
            }

            public IntHolderBuilder value(String value) {
                this.value = value;
                return this;
            }

            public IntHolder build() {
                return new IntHolder(value);
            }

            public String toString() {
                return "LombokTest.IntHolder.IntHolderBuilder(value=" + this.value + ")";
            }
        }
    }
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.20

**Comment by Rawi01** [comment]
I think you can add an `@Tolerate` to the `newIntHolder` method to get the expected result.

Replacing the 'is there a method with the same name'-check by a 'name+arguments'-check is not hard but might break some existing code:
```java
@Builder
public class Test {
    ...
    public static TestBuilder builder(String required) {
        return new TestBuilder.required(required);
    }
}
```
```java
public class Test {
    ...
    // Right now lombok does not generate this method
    public static TestBuilder builder() {
        return new TestBuilder();
    }

    public static TestBuilder builder(String required) {
        return new TestBuilder.required(required);
    }
    ...
}
```

**Comment by Auties00** [comment]
> I think you can add an `@Tolerate` to the `newIntHolder` method to get the expected result.
> 
> Replacing the 'is there a method with the same name'-check by a 'name+arguments'-check is not hard but might break some existing code:
> 
> ```java
> @Builder
> public class Test {
>     ...
>     public static TestBuilder builder(String required) {
>         return new TestBuilder.required(required);
>     }
> }
> ```
> 
> ```java
> public class Test {
>     ...
>     // Right now lombok does not generate this method
>     public static TestBuilder builder() {
>         return new TestBuilder();
>     }
> 
>     public static TestBuilder builder(String required) {
>         return new TestBuilder.required(required);
>     }
>     ...
> }
> ```

Makes sense, thanks for the quick fix
