### ISSUE TITLE
[BUG] Eclipse does not lombok

### ISSUE THREAD

**Issue by bconnection42** [projectlombok/lombok#2830]
My maven configuration is working probably, the system is able to run. Unfortunately Eclipse does not lombok, therefore I see errors within the editor. 

I tried the following:

- started lombok.jar and installed lombok to eclipse
- went through the installation in eclipse. 
- checked eclipse installed features, that lombok is present.
- checked Eclipse error log, found nothing which could help me

**To Reproduce**
I don't know how to reproduce the case. At home I used Lombok within Eclipse successfully, but not within my working environment. 

**Expected behavior**
I hope you can help me to get Lombok at my work functioning probably.

**Version info (please complete the following information):**
 - Lombok version 
 - 

lombok 1.18.20
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

![About Eclipse](https://user-images.githubusercontent.com/23283795/117048812-afc77380-ad13-11eb-915b-eef93e9e7a41.png)
![Lombok installed](https://user-images.githubusercontent.com/23283795/117049084-0634b200-ad14-11eb-8b7e-b155693b87f7.png)
[eclipse.configuration.txt](https://github.com/projectlombok/lombok/files/6423107/eclipse.configuration.txt)

**Comment by Rawi01** [comment]
There should be a line like `-javaagent:plugins//org.projectlombok.agent_1.18.20/lombok.jar` in your `eclipse.ini`. If it is not there you have to add it manually. If that does not work either you can use the old lombok installer: [https://projectlombok.org/setup/eclipse](https://projectlombok.org/setup/eclipse), Make sure to completly close eclipse and start it again.

**Comment by bconnection42** [comment]
Thank you for quick reply. While checking the ini-file, I recognized, that there are two ini-files. The one which was created by my organization was left unchanged by the installer. I adopted the changes to the other ini-file and WOW it starts working. 

Thanks a lot.
