### ISSUE TITLE
[FEATURE] @Builder Validation

### ISSUE THREAD

**Issue by onkcampbell** [projectlombok/lombok#2831]
**Describe the feature**
Would it be possible to generate an empty Example.validateBuilder(ExampleBuilder) or ExampleBuilder.validate() method?  This method would be called at the start of ExampleBuilder.build() to sanitize data or throw exceptions in order to prevent the object from being constructed with an invalid state.  For example:

```java
@Builder
@Value
class Person {
    String name;
    ...

    class PersonBuilder {
        @Override
        private void validate() {
            if (name == null || name.isBlank()) {
                throw new IllegalStateException("name is required");
            } 
        }
    }
}
```
or
```java
@Builder
@Value
class SearchRequest {
    String indexName;
    int page;
    ...

    @Override
    private void validateBuilder(SearchRequestBuilder b) {
        if (b.indexName() == null || b.indexName().isBlank()) {
            throw new IllegalStateException("indexName is required");
        } 
        if (b.page() <= 0) {
            b.page(1);
        } 
    }
}
```

**Describe the target audience**
E for Everyone.  Anyone who uses `@Builder` frequently and would like to be able to prevent invalid configurations from generating an instance.

**Comment by janrieke** [comment]
Why don't you simply validate it in your constructor? In that way, you'd also catch instantiations via direct constructor call.

**Comment by Auties00** [comment]
> **Describe the feature**
> Would it be possible to generate an empty Example.validateBuilder(ExampleBuilder) or ExampleBuilder.validate() method? This method would be called at the start of ExampleBuilder.build() to sanitize data or throw exceptions in order to prevent the object from being constructed with an invalid state. For example:
> 
> ```java
> @Builder
> @Value
> class Person {
>     String name;
>     ...
> 
>     class PersonBuilder {
>         @Override
>         private void validate() {
>             if (name == null || name.isBlank()) {
>                 throw new IllegalStateException("name is required");
>             } 
>         }
>     }
> }
> ```
> 
> or
> 
> ```java
> @Builder
> @Value
> class SearchRequest {
>     String indexName;
>     int page;
>     ...
> 
>     @Override
>     private void validateBuilder(SearchRequestBuilder b) {
>         if (b.indexName() == null || b.indexName().isBlank()) {
>             throw new IllegalStateException("indexName is required");
>         } 
>         if (b.page() <= 0) {
>             b.page(1);
>         } 
>     }
> }
> ```
> 
> **Describe the target audience**
> E for Everyone. Anyone who uses `@Builder` frequently and would like to be able to prevent invalid configurations from generating an instance.

Most of the validation needed can be achieved using annotations, for more complex operations you could simply specify a constructor.  This is how I would organize your snippet:
```
@Builder
@Value
class SearchRequest {
    @NotNull(message = "indexName is required")
    @NotBlank(message =  "indexName is required")
    private String indexName;
    @Default
    private int page = 1
}
```

**Comment by vedp544** [comment]
Agree with @Auties00

**Comment by onkcampbell** [comment]
Thanks for the responses.  I was able to get everything working.
