### ISSUE TITLE
[BUG] Building lombok from sources

### ISSUE THREAD

**Issue by dembanakh** [projectlombok/lombok#2832]
**Describe the bug**
Is it possible that the instructions here and at projectlombok webpage about how to build lombok from sources is lacking something important? A fresh clone of repository master branch gives BUILD FAILED on `ant intellij` or `ant eclipse`.

**To Reproduce**
1. `git clone git@github.com:projectlombok/lombok.git`
2. `cd lombok`
3. `ant intellij` or `ant eclipse`
I am using jdk-14.0.2 and ant-1.10.10.
Error log:
```
[compile:javac] Compiling 1 source file to C:\lombok\build\lombok-version
Compile errors:
----------
1. ERROR in C:\lombok\src\core\lombok\core\Version.java (at line 1)
/*
^
The type java.lang.Object cannot be resolved. It is indirectly referenced from required .class files
----------
```
... and 30 more similar errors.

**Expected behavior**
Successful build and IDE setup.

**Version info (please complete the following information):**
 - Lombok version 1.18.21
 - javac version 14.0.2

**Comment by Rawi01** [comment]
I think this is a problem on your system, I just tried to run `ant eclipse` and it works. It seems like the compiler is unable to find `java.lang.Object` and without it is is obviously impossible to compile anything.

**Comment by dembanakh** [comment]
It definitely is. Obviousy, I am not assuming that the master branch is in broken state😉
This is why I think that the instructions on how to build lombok are not full. My JDK is certainly working properly, I am able to run IntelliJ or compile any Java code. So, I don't know, maybe one must have anything else apart from ant installed? Maybe some specific jdk (e.g. I saw that ant compiles Version.java for java 1.5)?

**Comment by Rawi01** [comment]
Yes,the build process is quite complex and uses old java versions for some tasks but it should all work without further configuration. You can run `ant -diagnostics` or `ant eclipse -verbose` to get some more ouptut, that might be useful to figure out what is wrong.

**Comment by dembanakh** [comment]
Oh, okay. I found the problem eventually. I have no idea why, but lib/openjdk6_rt.jar was just "partially" downloaded - it has 106KB. It was enough to remove lib/ and restart ant. Thanks for your help!
