### ISSUE TITLE
[IntelliJ 2021.1.1 (Ultimate Edition)]java: JPS incremental annotation processing is disabled. Compilation results on partial recompilation may be inaccurate. Use build process "jps.track.ap.dependencies" VM flag to enable/disable incremental annotation processing environment.

### ISSUE THREAD

**Issue by cru5ader** [projectlombok/lombok#2842]
Intellij version - Intellij 2021.1.1 (Ultimate Edition)
Lombok version being used - 1.18.x (Latest)
Previous issue(i.e. Issue that was coming before the above mentioned issue)- Intellij was throwing _**Compiler not compatible with Lombok**_
Solution used to remove the above issue - Used **_-Djps.track.ap.dependencies=false_** in **_Shared build process VM options_** , invalidated cache and restarted the Intellij.
**_Issue_** - Even after trying every solution, the issue **_JPS incremental annotation processing is disabled_** is **NOT getting resolved.** Kindly, help with the issue.

**Comment by wenbochang888** [comment]
so how to solve it ? 

i try to use  ```  -Djps.track.ap.dependencies=false  ```

but it do not work

**Comment by bogdanovmn** [comment]
have the same problem

**Comment by coolZhangSir** [comment]
> so how to solve it ?
> 
> i try to use ` -Djps.track.ap.dependencies=false `
> 
> but it do not work


Here is a solution from the JB stuff, it may help you, 
![image](https://user-images.githubusercontent.com/27146728/127619141-2f36e88d-970f-44b2-9f28-aff4b81009dc.png)
[IDEA-252069](https://youtrack.jetbrains.com/issue/IDEA-252069)
You can jump to the end to see get the conversation context.

**Comment by yasminwz** [comment]
I tried in every way to do the step by step above and I see that the debug compiler option doesn't appear in the log, as well as in the issue, could someone who managed to solve this problem help me? My email: yasmin.wichinievski@gmail.com
thanks

**Comment by tjxone** [comment]
'java: JPS incremental annotation processing is disabled. Compilation results on partial recompilation may be inaccurate. Use build process "jps.track.ap.dependencies" VM flag to enable/disable incremental annotation processing environment.'
----------------------------------------------
I also appear this tips ,and tried every way in that issue.and did not work.
Finnaly ,I add ths 'shared build process heap size' to 2000m from default 700m,then it work.
Hope it can help you .

**Comment by verigle** [comment]
> ## 'java: JPS incremental annotation processing is disabled. Compilation results on partial recompilation may be inaccurate. Use build process "jps.track.ap.dependencies" VM flag to enable/disable incremental annotation processing environment.'
> I also appear this tips ,and tried every way in that issue.and did not work. Finnaly ,I add ths 'shared build process heap size' to 2000m from default 700m,then it work. Hope it can help you .

I modified this 'shared build process heap size' to 8192m, but also has same problem.
