### ISSUE TITLE
[FEATURE] record support for @Builder

### ISSUE THREAD

**Issue by ktechies** [projectlombok/lombok#2851]
**Describe the feature**
Currently the @Builder annotation doesn't seem to support java 16 records yet. Records are in my view a good addition that removes a bunch of boilerplate code. however they are sadly limited and overloading a record constructor is a hassle when they get more members.

**Describe the target audience**
Java 16 developers.

**Additional context**
records implicitly have an "allargsconstructor" already.

when currently annotating a record with @Builder is seems that none of the members are added to the builder class, even tho this might be a bug i consider this request a feature because records are a new feature to java.

public class Test {
    
    @Builder
    record Rtest(boolean one, String two, int three) {
        
    }
    
    @Test
    public void builderTest() {
        Rtest.builder().<< no methods?
    }

}

**Comment by janrieke** [comment]
`@Builder` on records is supported since the last release v1.18.20. Which version are you using?

**Comment by ktechies** [comment]
just updated to 1.18.20, using IntelliJ indeed. compile seems to work fine now but IDE isn't aware yet.

thanks for the suggestion

**Comment by openminded-oscar** [comment]
Nice!
