### ISSUE TITLE
[BUG] @Getter(lazy = true) generates Row-typed generic field

### ISSUE THREAD

**Issue by Vyacheslav-Lapin** [projectlombok/lombok#2852]
**Describe the bug**
java.util.concurrent.atomic.AtomicReference, generated for @Getter(lazy = true) is loosing real type of field.
It is very sad...

**To Reproduce**
Write this code in any class:

```
@Getter(lazy = true)
private final UUID id = UUID.randomUUID();

public void myMethod() {
  AtomicReference<UUID> id = this.id;
  //...
}
```

Delombok for this code throw this error:
```
error: incompatible types: java.util.concurrent.atomic.AtomicReference<java.lang.Object> cannot be converted to java.util.concurrent.atomic.AtomicReference<java.util.UUID>
    AtomicReference<UUID> id = this.id;
                                   ^
```

This behavioural is inconvenience in some cases.

The reason is:
```
@Getter(lazy = true)
private final UUID id = UUID.randomUUID();
```
Delomboks to this:
```
private final java.util.concurrent.atomic.AtomicReference<java.lang.Object> id = new java.util.concurrent.atomic.AtomicReference<java.lang.Object>();

@java.lang.SuppressWarnings({"all", "unchecked"})
@edu.umd.cs.findbugs.annotations.SuppressFBWarnings(justification = "generated code")
@lombok.Generated
public UUID id() {
  java.lang.Object value = this.id.get();
  if (value == null) {
    synchronized (this.id) {
      value = this.id.get();
      if (value == null) {
        final UUID actualValue = UUID.randomUUID();
        value = actualValue == null ? this.id : actualValue;
        this.id.set(value);
      }
    }
  }
  return (UUID) (value == this.id ? null : value);
}
```
So, all we can do for using this code is:
```
public void myMethod() {
    AtomicReference<?> id = this.id;
    //...
  }
```

As I said, this behavioural is inconvenience in some cases...

**Expected behavior**
Following the PECS principle, I think it'll be better to delombok above code to something like this:
```
private final java.util.concurrent.atomic.AtomicReference<? extends UUID> id = new java.util.concurrent.atomic.AtomicReference<>();
// ...
```

**Version info (please complete the following information):**
 - 1.18.20
 - JDK 16 (Corretto)

**Comment by rspilker** [comment]
The way to extract the data from the field is to use the getter, and not access the field directly. We cannot use `AtomicReference<UUID>`, because we use the same field to store a reference to itself. That allows us to distinguish between an uninitialized field and a field that contains `null`.
