### ISSUE TITLE
[BUG]  create-intellij-project not work

### ISSUE THREAD

**Issue by dulm** [projectlombok/lombok#2860]
**Describe the bug**
`ant intellij`
```
/lombok/buildScripts/create-intellij-project.ant.xml:36: java.lang.IllegalArgumentException: requested configuration not found in projectlombok.org#lombok;working@MacBook-Pro-2.mshome.net: [ 'buildTools' ]
```

fix:  change  `create-intellij-project.ant.xml`:  `buildTools` to `buildtools`

**To Reproduce**
Steps to reproduce the behavior, preferably in the form of the smallest java source file you can make that will show the problem when compiled with `javac -cp lombok.jar ExampleFile.java` or as sole java file in a fresh new eclipse project.

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version:  master
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.

**Additional context**

**Comment by rzwitserloot** [comment]
99% sure this doesn't work either, but at least you get an iml. If you can manage to set up lombok to be compilable and editable by futzing about with it, attach your working iml to this issue and I'll se what I can do to fix the build to make it generate that.
