### ISSUE TITLE
[BUG] @Builder.Default vs primitive boolean on field in inner class leads to show errors in Apache Netbeans IDE

### ISSUE THREAD

**Issue by netbeansuser2019** [projectlombok/lombok#2863]
**Describe the bug**
Generates reds in Apache Netbeans on calls to class that returns inner class and when other inner class class contains primitive boolean annotated with @Builder.Default as field, but if it is used delomboked source then there is no issue in IDE and there is even no issue when exact build is run so very likely it is something wrong with generating during annotation processing with nb-javac. 

**To Reproduce**
@Builder.Default
private final boolean someVariable = true; 

**Expected behavior**
As it seems that using delombok source do not do not do such issue I guess that there is any issue during annotation procession so maybe again some wrong class is created. So expected behavior is to be error free. 

**Version info (please complete the following information):**
 - Lombok version 1.18.20
 - Platform nb-javac used in Apache Netbeans 12.0+

**Additional context**

**Comment by shengding1214** [comment]
you can try it
```java
Foo build = Foo.builder().build();
System.out.println(build.str); // 'default'
```

when i check Diagnose.class, I found
```java
public class Diagnose {
    public Diagnose() {
    }

    public static void main(String... argv) {
        System.out.println((new Diagnose.Foo()).str);
        Diagnose.Foo build = Diagnose.Foo.builder().build();
        System.out.println(build.str);
    }

    public static class Foo {
        private String str;

        public Foo() {
        }

        public Foo(String str) {
            this.str = str;
        }

        private static String $default$str() {
            return "default";
        }

        public static Diagnose.Foo.FooBuilder builder() {
            return new Diagnose.Foo.FooBuilder();
        }

        public static class FooBuilder {
            private boolean str$set;
            private String str$value;

            FooBuilder() {
            }

            public Diagnose.Foo.FooBuilder str(String str) {
                this.str$value = str;
                this.str$set = true;
                return this;
            }

            public Diagnose.Foo build() {
                String str$value = this.str$value;
                if (!this.str$set) {
                    str$value = Diagnose.Foo.$default$str();
                }

                return new Diagnose.Foo(str$value);
            }

            public String toString() {
                return "Diagnose.Foo.FooBuilder(str$value=" + this.str$value + ")";
            }
        }
    }

```
