### ISSUE TITLE
[FEATURE]How to distinguish between "null" and null when using @ToString

### ISSUE THREAD

**Issue by jearton** [projectlombok/lombok#2876]
![image](https://user-images.githubusercontent.com/10370433/121661248-96fe6a80-cad6-11eb-9617-e2b856ccbc34.png)

**Comment by rspilker** [comment]
We've discussed putting quotes around strings. We might do that. Or allow users to configure doing that. 

But the same problem already exists in standard libraries.
```java
public class ToStringExample {
	public static void main(String[] args) {
		System.out.println(Arrays.toString(new String[] {null}));
		System.out.println(Arrays.asList(new String[] {null}));
		
		System.out.println(Arrays.toString(new String[] {"null"}));
		System.out.println(Arrays.asList(new String[] {"null"}));
	}
}
```

Output:
```cmd
[null]
[null]
[null]
[null]
```

Adding quotes in lombok generated toString methods would not fix that problem. Also, in practice it has never been that much of a problem for me.

Adding quotes to strings or having alternative rendering for null values increases the maintenance load, lombok learning curve or both. It might/would also affect existing programs or cause a split in the output.

So I am currently leaning against implementing improved null string rendering.
