### ISSUE TITLE
The regular process to install lombok in Eclipse (https://projectlombok.org/setup/eclipse) fail .

### ISSUE THREAD

**Issue by eitan-rosenberg** [projectlombok/lombok#2879]
Try to install lombok-1.18.20.jar in Eclipse 2021-06 (4.20.0) 

My environment:

- Eclipse installation is eclipse-java-2021-06-R-win32-x86_64.zip.
- lombok-1.18.20.jar from Maven
- Java installation is openjdk-16.0.1_windows-x64_bin.zip. 
- The workspace is fresh.
- Windows 10

Expected behavior:
A Lombok enabled indication in eclipse's about dialog and no compile errors.

**It is a severe showstopper.......**

Regards.

**Comment by Rawi01** [comment]
I just updated to the latest eclipse version and it works wothout any problems. There is an already fixed Java 16 related issue (#2810) that might be the reason why it doesn't work.

If that doesn't help please check if there is a `-javaagent:.../lombok.jar` line in your `eclipse.ini`. If not you have to add one (thats  what the installer does). If the javaagent is there please check the eclipse error log for any errors.

**Comment by yoyo837** [comment]
Same here.

**Comment by eitan-rosenberg** [comment]
Hello there,

Many thanks for the quick response.

I opt for this solution https://github.com/projectlombok/lombok/issues/2810#issuecomment-817348339

![image](https://user-images.githubusercontent.com/48506054/122331961-58d1d280-cf3e-11eb-8121-d1d76600c1c0.png)

And it seems to be working !!!!

Thank you.

**Comment by eitan-rosenberg** [comment]
Thanks again
