### ISSUE TITLE
 Errors occurred during the build on Eclipse202106

### ISSUE THREAD

**Issue by cxfly** [projectlombok/lombok#2882]
**Describe the bug**

lombok version:  1.18.20
eclipse version :  eclipse-jee-2021-06-R

Errors occurred during the build.
Errors running builder 'Java Builder' on project.
Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @645dc557

**Comment by btheu** [comment]
Hi, 

I got same error. This is blocking issue causing Eclipse building endlessly project when automatic build is enabled.

Plus, I have noticed that lombok version is not shown on Eclipse "About" window.

**Comment by Rawi01** [comment]
Duplicate of #2810

**Comment by tolgadurak** [comment]
Hi,

The same error still occurs with the installation below. I cannot see Java source files when I open them.

Lombok version: 1.18.20
Eclipse version: eclipse-jee-2021-06-R
Java version: Oracle JDK 11 LTS

When I use eclipse-jee-2021-03-R, there is not any problem.

**Comment by sergey-morenets** [comment]
Hi @tolgadurak 

I added the following VM arguments to my eclipse.ini file and it solved this issue:

```
--illegal-access=warn
--add-opens java.base/java.lang=ALL-UNNAMED

```

**Comment by Ashish503** [comment]
> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

thanks, 
it worked for me.

**Comment by mauricio-serafim** [comment]
thanks.


> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

thanks,
it worked for me.

**Comment by princessMiracle** [comment]
That worked! Thank you so much for help.

**Comment by Shane-Park** [comment]
> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

It worked for me as well ! many thanks !

**Comment by erhajdami** [comment]
thks a lot ! 
it works what it means please explain 

Thks

**Comment by erhajdami** [comment]
> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

It works thks, but i dont know what this line does

**Comment by raulCandido** [comment]
> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

It works thks, but i dont know what this line does²

**Comment by swmproopengit** [comment]
thank you that's great

> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

**Comment by thaitzer** [comment]
The pre-build worked for me. Thanks for that.
Sorry for the stupid question, probably in the wrong place:
Is there any ETA for this in a release? (Rolling out a pre-release to 10+ PCs for production work scares me a bit)

**Comment by karandeep-kamboj** [comment]
worked for me, thanks

> Hi @tolgadurak
> 
> I added the following VM arguments to my eclipse.ini file and it solved this issue:
> 
> ```
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED
> ```

**Comment by SunGungg** [comment]
worked for me. thanks

**Comment by rzwitserloot** [comment]
@thaitzer certainly not a stupid question. We push new releases more or less when we get the impression it is neccessary, and, well, I'm starting to get that impression :)

A few things to look at are open bugs marked 'critical' ('critical' basically means: This must be addressed in some fashion, and fast - so generally we'd want to work on that instead of push a new release), and any open issues in milestone next-release.

**Comment by rzwitserloot** [comment]
@thaitzer plan is to release tomorrow.

**Comment by mohamedHedi1990** [comment]
> --illegal-access=warn
> --add-opens java.base/java.lang=ALL-UNNAMED

it is working as a charm..thanks

**Comment by MateusRangel0** [comment]
the pre-built version saved me, thanks!
