### ISSUE TITLE
[BUG] Eclipse 2021-06 Cleanup "Remove variable assignment before return" removes @EqualsAndHashCode

### ISSUE THREAD

**Issue by lars-sh** [projectlombok/lombok#2886]
**Describe the bug**
When activating the new Eclipse 2021-06 Cleanup option "Remove variable assignment before return" `@EqualsAndHashCode` annotations are removed when executing the cleanup.

**To Reproduce**
* Use Eclipse version 2021-06
* Create some small Java class, probably with one or more fields, but not necessarily.
* Add the `@EqualsAndHashCode` annotation to that class.
* Make sure everything is syntactically correct.
* Activate the Cleanup option "Remove variable assignment before return"
(can be found in the project properties > Java Code Style > Clean Up > Edit > tab "Unneccessary Code")
* Execute the Cleanup function

**Expected behavior**
The annotation is not removed.

**Version info (please complete the following information):**
 - Lombok 1.18.20
 - Eclipse 2021-06 (4.20.0)

**Additional context**
I used delombok to have a look at why this might occur and noticed, the generated `hashCode` method ends the following way:

```java
result = result * PRIME + ($previousCheckpoint == null ? 43 : $previousCheckpoint.hashCode());
return result;
```

That's exactly what that cleanup function tries to change to:

```java
return result * PRIME + ($previousCheckpoint == null ? 43 : $previousCheckpoint.hashCode());
```

While there are some more issues open regarding such kind of influence of Eclipse on the Lombok annotations and it seems, there's no easy or known way to avoid Eclipse removing/updating the generated code, this might be fixable by changing Lombok to generate code as in the second code example instead of the first to make sure, Eclipse does not touch it.

**Comment by lars-sh** [comment]
I just took a look at the Eclipse related handling code and found the return statement generation at https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleEqualsAndHashCode.java#L48

My notices:
1. Placing the `return` statement in the last result calculation line would require a change to `createResultCalculation`.
Such a change might make that method less readable and probably require good comments in code.
2. In case `cacheHashCode` is `true`, this problem should not appear from what I expect. (I didn't test it!)
3. A workround could be used to trick-out Eclipse: Prior the `return` statement there could be some noop statement to make sure, Eclipse does not try to optimize the code.
Well, I'm definitely not a fan of that.

I just looked at the Lombok implementation for this or that. Though, if you're fine with either way (or probably some additional one), I could try to create a Pull Request or at least a first suggestion.

**Comment by Rawi01** [comment]
Thanks for reporting this issue, I have checked some of the new Eclipse cleanups but it seems like I missed this one. We usually try to hide generated code for the cleanups to avoid conflicts like this one, see [EclipsePatcher.java#L209](https://github.com/projectlombok/lombok/blob/master/src/eclipseAgent/lombok/eclipse/agent/EclipsePatcher.java#L209). I will check why it doesn't handle this cleanup tomorrow morning.

**Comment by Rawi01** [comment]
It works for me, can you share an example class? I activated only this cleanup, is there another one active in your setup?

**Comment by lars-sh** [comment]
I just created a new and clean project for testing and just a single dummy class.

I'll hand that over to you whenever I'm back home today.

**Comment by lars-sh** [comment]
Thanks for your support @Rawi01, I just had one more look at my configuration and noticed, that I missed to update the Lombok version of my Eclipse installation. After upgrading from 1.18.18 to 1.18.20, the problem's gone.
