### ISSUE TITLE
compile error when i use @ExtensionMethod

### ISSUE THREAD

**Issue by zhoujiaping** [projectlombok/lombok#2889]
**Describe the bug**
when i use @ExtensionMethod, some times it will report compile error, java.lang.Stackoverflow.
**To Reproduce**
```
package org.example.ext;

import lombok.experimental.ExtensionMethod;
import org.assertj.core.util.Lists;
import org.junit.jupiter.api.Test;
import java.util.Arrays;

@ExtensionMethod(Arrays.class)
public class ExtendsionsBugTest {

    @Test
    public void testCompileError() {
       Lists.newArrayList("ONE","TWO").forEach(it->
               println(it)
       );
       Lists.newArrayList("ONE","TWO").forEach(it->
               println(it)
       );
    }
    public <T> void println(T t){
        System.out.println(t);
    }

}

```
**Expected behavior**
it works.

**Version info (please complete the following information):**
 - Lombok 1.18.4
 - Platform (jdk 1.8.0_291)

**Additional context**

**Comment by dstango** [comment]
possible duplicate: https://github.com/projectlombok/lombok/issues/2741

**Comment by Rawi01** [comment]
@zhoujiaping Can you update your lombok version and try if the error is still there?

**Comment by zhoujiaping** [comment]
@Rawi01  i had try 1.18.20,1.18.18,1.18.16,1.18.14,1.18,12,1.18.10,1.18.8,1.18.6,1.18.4,1.18.2,1.18.0
but got the same error.

**Comment by zhoujiaping** [comment]
@dstango thanks. is this fixed?

**Comment by dstango** [comment]
@zhoujiaping I tried it and can't reproduce it. 
My test environment:
- maven-project
- eclipse 2021-06
- jdk8

Do you get the error when doing a maven build or in your IDE? Or do you have a totall different setup?

**Comment by Rawi01** [comment]
@zhoujiaping I vaguely remember fixing a problem like that. Can you share a full stacktrace?

**Comment by zhoujiaping** [comment]
@Rawi01 for 1.18.4, the problem still exists. but i tried 1.18.24, it works well. thanks!
