### ISSUE TITLE
Eclipse can not initialize editor after the Lombok Installation

### ISSUE THREAD

**Issue by SantiRey** [projectlombok/lombok#2893]
**Description**

eclipse cannot open the text editor after lombok installation. Which means that i cannot see any Java class for example. I have installed lombok in both ways that are in the documentation. I have tried installing Lombok both from jar and from eclipse and in both ways I still have the error from eclipse.

**To Reproduce**
to reproduce this error it is only necessary to install lombok in any way as in the documentation is explained. Using in the latest version of Eclipse and Lombok

![Bildschirmfoto 2021-06-29 um 19 58 02](https://user-images.githubusercontent.com/17256988/123845619-b38f0500-d914-11eb-9983-7a7996c26b50.png)

![Bildschirmfoto 2021-06-29 um 20 10 37](https://user-images.githubusercontent.com/17256988/123846803-1c2ab180-d916-11eb-8a57-11ca1903adbb.png)

**Expected behavior**
that the editor can be initialized

**software versions involved**
 - Lombok version v1.18.20
 - Eclipse Version: 2021-06 (4.20.0)

**Additional context**
The error occurred when I updated the latest version of Eclipse and lombok. I have also tried to reinstall lombok and eclipse and I still have the same error. I have also tried to use other projects but the exact same thing continues to happen with java classes.

**Comment by mohanaraosv** [comment]
This is already addressed here https://github.com/projectlombok/lombok/issues/2892

**Comment by SantiRey** [comment]
it is works perfectly again with the solution in that linked issue. thanks a lot...!
