### ISSUE TITLE
[BUG] Lombok makes Eclipse very slow

### ISSUE THREAD

**Issue by nlisker** [projectlombok/lombok#2897]
**Describe the bug**
When Lombok is installed in Eclipse, it makes its operations extremely slow.

**To Reproduce**
1. I used a completely new Eclipse installation from https://download.eclipse.org/eclipse/downloads/drops4/R-4.20-202106111600/ and downloaded eclipse-SDK-4.20-win32-x86_64.zip just to be sure, but It happens also on existing installations.
2. In Eclipse's .ini file, I added:
    ```
    --illegal-access=warn
    --add-opens java.base/java.lang=ALL-UNNAMED
    ```
    as a fix for getting Lombok to work.
3. I installed Lombok from the updated site https://projectlombok.org/p2. The "About" section says "Lombok v1.18.20 "Envious Ferret" is installed. https://projectlombok.org/".
4. Import the minimal project [LombokTest.zip](https://github.com/projectlombok/lombok/files/6783686/LombokTest.zip) (it's a cut down version of a big project, so it has some leftovers, but it doesn't matter). You might notice that building it is very slow despite it having only 1 source file. Sometimes building is fast, probably because of the incremental compiler.
5. Open the only source file, `com.test.lombok.Descriptions.java`, go to one of the fields and try to inline it by pressing `alt+shift+i`, the operation will take a lot of time just to bring up the dialog. Sometimes it's fast, probably because of caching. In such a case, if I restart Eclipse and try inlining again, the problem comes back.
6. Uninstall Lombok and restart. The inline operation will complete instantly. (In the "About" section there is still "Lombok v1.18.20 "Envious Ferret" is installed. https://projectlombok.org/", although Lombok was removed from the installation details. This is probably a separate bug.)

**Expected behavior**
Build and inline operations should be fast.

**Version info (please complete the following information):**
 - 1.8.20
 - Eclipse Version: 2021-06 (4.20) Build id: I20210611-1600
 - Java 16

**Additional context**
Could be related to #2489

**Comment by Rawi01** [comment]
I also notice a massive slow down using your example class but this is an eclipse problem, it also happens without lombok. According to the profiler the slow down happens during type interference (as in https://bugs.eclipse.org/bugs/show_bug.cgi?id=512156). It seems to work if you replace `Map.ofEntries` with `Map.<String, String>ofEntries`.

**Comment by nlisker** [comment]
Interesting, I could not reproduce it without Lombok, but I will take your word for it and report it at Eclipse's bug tracker.

**Comment by Rawi01** [comment]
@nlisker Thanks for creating the [eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574732). :+1:
My sampling results:
![img](https://user-images.githubusercontent.com/5850477/124924592-e794b500-dffb-11eb-9361-8da8725dd34b.png)

**Comment by nlisker** [comment]
If you have additional info, maybe it's best to post it there.
