### ISSUE TITLE
[FEATURE] JDK 17 support

### ISSUE THREAD

**Issue by clemstoquart** [projectlombok/lombok#2898]
Hello lombok team,

JDK 17 release is just around the corner and it would be very convenient to have at least a lombok snapshot to start working on the migration.

Thanks !

**Comment by Rawi01** [comment]
Thanks for the reminder, release date for Java 17 is 2021-09-14.

So far I have identified these tasks:
- [ ] Support new switch expressions
- [ ] Support sealed classes
- [ ] Update ASM to 9.1+

I already started to fix the first switch expression related thing (https://github.com/Rawi01/lombok/tree/jdk-17).

**Comment by rzwitserloot** [comment]
An edge release is out with this patch applied. Give it a whirl if you like :)

https://projectlombok.org/download-edge

**Comment by chrisgleissner** [comment]
The edge release works well on a large project that uses most of Lombok's features. We had trouble with the @Singular annotation and slow val performance. Both are fixed. We are keen to upgrade and hope that a new release can be cut soon.

**Comment by clemstoquart** [comment]
Hi,
I confirm that everything is now working fine with JDK 17 🎉

**Comment by rzwitserloot** [comment]
Weeeellll, time for us to start getting a new release out the door Real Soon Now. @Rawi01 deserves all the credit for making it work. @clemstoquart gracias for checking the edge build!
