### ISSUE TITLE
[BUG] https://www.projectlombok.org is down

### ISSUE THREAD

**Issue by rogeriochaves** [projectlombok/lombok#2912]
https://downforeveryoneorjustme.com/projectlombok.org?proto=https&www=1

![image](https://user-images.githubusercontent.com/792201/127008413-05cf2c57-6fa6-4647-9f83-b97fb33c35c8.png)

where can I read the docs meanwhile?

**Comment by janrieke** [comment]
http://web.archive.org/web/20210723051828if_/https://projectlombok.org/features/all

**Comment by rspilker** [comment]
Thanks for the message. We're back.
