### ISSUE TITLE
[BUG] Problem with save action in eclipse

### ISSUE THREAD

**Issue by epictecch** [projectlombok/lombok#2926]
After updating lombok from 1.18.18 to 1.18.20, I encounter a problem in eclipse / STS 4.11.0.
I use the save action "Use modifier 'final' where possible" in Preferences -> Java -> Editor -> Save Action -> Code Style.

When saving the following class with eclipse where I applied the lombok-1.18.18.jar, then everything works fine:
```
@Data
public class Example {
    private int myVar = 42;
}
```
Eclipse's save action does not change this code.
After applying the lombok.jar of the version 1.18.20 and restarting eclipse, saving that file leads to the situation that the `final` keyword is inserted for `myVar`.
After applying lombok-1.18.18.jar again and restarting eclipse, I can remove the final keyword and eclipse does not insert it again.
Note: Without the member variable initializer, the problem is not reproducible.

If this is an eclipse problem, please let me know. I first try a bug report here because I can reproduce it by only applying the lombok.jar of the newer version without changing anything else.

**Comment by Rawi01** [comment]
Can confirm this for lombok 1.18.20 and Eclipse 2021-06. This is most likely related to the latests changes to support the new Eclipse cleanups/save actions.
