### ISSUE TITLE
[BUG] @Getter not work expected

### ISSUE THREAD

**Issue by IWareQ** [projectlombok/lombok#2944]
**Describe the bug**

**To Reproduce**
```
@Getter
public class TestLombok {

	private static final int test1 = 1;
	private static int test2 = 1;
}
```

Output:
```
public class TestLombok {

	private static final int test1 = 1;
	private static int test2 = 1;
}
```

**If you write @Getter above the field, then it will be created**

**Expected behavior**
```
public class TestLombok {

	private static final int test1 = 1;
	private static int test2 = 1;

	public int getTest1() {
		return test1;
	}

	public int getTest2() {
		return test2;
	}
}
```

**Version info (please complete the following information):**
 - 1.18.20
 - JDK 1.8

**Comment by Rawi01** [comment]
Documentation:
>  You can also put a @Getter and/or @Setter annotation on a class. In that case, it's as if you annotate all the non-static fields in that class with the annotation. 

You used non-static methods in your expected behavior code, as far as I know lombok generates static getters/setters for static fields.

**Comment by IWareQ** [comment]
Why?

**Comment by Rawi01** [comment]
Etters for private static fields are quite unusual, they create some kind of global variable and that's something you usually try to avoid.

**Comment by IWareQ** [comment]
Ok, thanks you to answer.
