### ISSUE TITLE
[Help]Where are the implementations of annotations?

### ISSUE THREAD

**Issue by http600** [projectlombok/lombok#2955]
alright, here it's neither a bug nor feature request, just for help
1. if I apply https://github.com/projectlombok/lombok/blob/693601e939e14d73224886c81af3a7513d0a6bfc/src/core/lombok/Data.java#L46 to my class T
2. then class T has `Getter` `Setter` `ToString` methods automatically at run-time
3. class T from has no `Getter` `Setter` `ToString` methods to has `Getter` `Setter` `ToString` methods
4. who did the work behind to make this change, implemented those methods for class T
5. where is the implementation? I could not find but `@interface Data`
6. Thanks in advance.

**Comment by Rawi01** [comment]
There are two implmentations: [javac](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/javac/handlers/HandleData.java), [eclipse](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleData.java). They simply call the handlers of the other annotations.
