### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by no0ker** [projectlombok/lombok#2959]
**To Reproduce**
```java
public class TestMasked {
    public static void main(String[] args) {
        SomeDto someDto = new SomeDto();
        someDto.setEmail("aaaaa@mail.ru");

        System.out.println("someDto  = " + someDto);
    }
}

@Data
class SomeDto {
    private String email;

    @ToString.Include(name = "email")
    public String getMaskedEmail() {
        return "***@mail.ru";
    }
}
```

Excpected Result = Actual Result = someDto  = 
> SomeDto(email=***@mail.ru)

**but**

```java
public class TestMasked {
    public static void main(String[] args) {
        SomeDto someDto = new SomeDto();
        someDto.setEmail("aaaaa@mail.ru");

        System.out.println("someDto  = " + someDto);
    }
}

interface ContainsEmail {
    @ToString.Include(name = "email")
    default String getMaskedEmail() {
        return "***@mail.ru";
    }
}

@Data
class SomeDto implements ContainsEmail{
    private String email;
}
```

Expected Result = 
> someDto  = SomeDto(email=***@mail.ru)

Actual Result = 
> someDto  = SomeDto(email=aaaaa@mail.ru)

**Version info (please complete the following information):**
 - Lombok version - 1.18.20
 - Platform adopt-openjdk-11.0.12-1

**Comment by rzwitserloot** [comment]
This is intentional; the `@ToString` implementation doesn't do [resolution](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution) therefore doesn't know about the method in the `ContainsEmail` interface. This would be cool but is not (currently) feasible.
