### ISSUE TITLE
[BUG] lombok Eclipse Installer with @ char in Path on Linux

### ISSUE THREAD

**Issue by Stratehm** [projectlombok/lombok#2960]
**Describe the bug**
The lombok Eclipse installer escapes @ characters in the javaagent path to lombok.jar in eclipse.ini, then Eclipse fails to start with an alert window containing "JVM terminated. Exit code=1" followed by the content of eclipse.ini.

**To Reproduce**

- Make a new Eclipse installation with a path containing @ character
- Make a lombok installation on it.
- Start Eclipse

**Expected behavior**
Eclipse starts.

**Version info:**
 - Lombok version: 1.18.20
 - Eclipse 2021-03 (4.19)
 - Ubuntu 20.04
 - OpenJDK 16 as Eclipse runtime (installed through Ubuntu apt repositories)

**Comment by rzwitserloot** [comment]
It sounds like you actually intended to say that lombok does _not_ escape `@` characters, but that it should start doing so. I don't know how one should properly escape it; can you fix your `eclipse.ini` file so that it works and then show us what lombok's installer should be generating?

Parked: This issue will be closed without action if no feedback by 2021-09-30.

**Comment by Stratehm** [comment]
Thank you for your reply.

The installer _do_ escape @ characters which, I presume, prevents the JVM to access the agent.

Failing eclipse.ini: 
`-javaagent:/home/strat\@domain.local/dev/eclipse/lombok.jar`

Working eclipse.ini:
`-javaagent:/home/strat@domain.local/dev/eclipse/lombok.jar`

**Comment by rzwitserloot** [comment]
Interesting. A leading `@` is interpreted by `java` as 'actually, the remainder of this cmdlinearg is a path; open it as a text file and process the contents thereof as command line arguments' which is presumably why we escape it. Evidently, either [A] that processing does not 'work' in eclipse, or [B] that only kicks in when the `@` is the first character in an arg, not when it appears halfway through.

I think we can presumably leave the usecase of 'my filename _starts_ with an @ symbol' as unaddressed and simply cease escaping it. Alternatively, the entire idea of escaping anything in these simply does not work, and if lombok believes that a path will not 'work' in the provided form in the `eclipse.ini` file, then it should just error instead, or we figure out what the correct way is to escape, say, a forward slash in a name.

I'm still somewhat surprised; `\@` in linux shells is simply `@`.

At any rate, I've also tested shoving a `:` as well as a space inside a path name, and then simply leaving it unescaped works.
