### ISSUE TITLE
[BUG] FieldNameConstants returns an empty array

### ISSUE THREAD

**Issue by jansedlon** [projectlombok/lombok#2965]
**Describe the bug**
When I use `@FieldNameConstants(asEnum = true)` and then call `TargetClass.Fields.values()`, it returns an empty array.

**To Reproduce**
There's not really a way to reproduce it. It happens once in a few weeks. This is exactly one of those bugs that happens multiple times, you restart the app a few times, change a code, change it back and then it's gone.

**Expected behavior**
It should return list of all properties

**Version info (please complete the following information):**
 - Lombok version: 1.18.16 (IntelliJ Maven plugin shows 1.18.12 but provided version in pom.xml is 1.18.16)
 - Platform: javac 11.0.11

**Additional context**
I just noticed that there's a few patch versions released. Does any of them fix this issue? I'd like to try it but there's no way to reproduce it.

**Comment by Rawi01** [comment]
This was fixed in #2441

**Comment by jansedlon** [comment]
@Rawi01  Well, not really. I'm running on 1.18.20 and it happened again

**Comment by rzwitserloot** [comment]
I created a text file named `Test.java` and put this code inside it:

```java
@lombok.experimental.FieldNameConstants(asEnum = true)
public class Test {
        private String foo, bar;

        public static void main(String[] args) {
                Test.Fields[] all = Test.Fields.values();
                System.out.println(all.length);
                System.out.println(java.util.Arrays.toString(all));
        }
}
```

Then:

```
> javac -cp lombok.jar Test.java
> java Test
2
[foo, bar]
```

Perhaps you're not actually on lombok 1.18.20? Or perhaps it's more complicated. Without a reproducible test case I don't think there's much we can do though.

Will re-open once a reproducible test case is provided.

**Comment by jansedlon** [comment]
@rzwitserloot You were right, sorry. I'm just a backup for our backend developer that doesn't have much time. I'm usually working on frontend. Found out that I couldn't override the lombok version because it's `provided` and all I had to do was to update spring boot that provides the newest version. Thanks
