### ISSUE TITLE
Call child constructor using @SuperBuilder

### ISSUE THREAD

**Issue by renatokenji** [projectlombok/lombok#2966]
I have a inheritance structure using SuperBuilder but the build process doesn't call the child constructor. For example if i have any validation methods in child constructor i'd like to have them called during the build process.

In the docs there's a info telling that: _@SuperBuilder generates a protected constructor on the class that takes a builder instance as a parameter. This constructor sets the fields of the new instance to the values from the builder._ 

Is there any way to customize the build process to enter the child constructor and execute any methods that could be inside it? Calling `Child.createChild().withRequiredField(null).create()` does work as "not" expected in this scenario. I debugged with a breakpoint inside the child constructor and it never triggers.

```
@lombok.experimental.SuperBuilder(buildMethodName = "create", setterPrefix = "with", toBuilder = true)
@lombok.NoArgsConstructor(access = AccessLevel.PROTECTED)
@MappedSuperclass
public abstract class BaseEntity {

    protected UUID id;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long DbId;

    public UUID getId() {
        return id;
    }

    public Long getDbId() {
        return DbId;
    }
}

@lombok.Getter
@lombok.experimental.SuperBuilder(builderMethodName = "createChild", buildMethodName = "create", setterPrefix = "with", toBuilder = true)
@lombok.NoArgsConstructor(access = AccessLevel.PROTECTED)
@Entity
public class Child extends BaseEntity {

    private String requiredField;

    @SuppressWarnings(value = "unused")
    private Child(String requiredField) {
        somePrivateValidationMethodFromChild(requiredField);
        this.requiredField = requiredField;
    }

    private void somePrivateValidationMethodFromChild(String requiredField) {
        //throw Exception if requiredField is null
    }
}
```

lombok version: 1.18.20
java version in project's pom: 16

**Comment by janrieke** [comment]
That's not the constructor `@SuperBuilder` creates. Thus, Lombok will create another constructor. Have a look at the `delombok` output and copy the exact constructor header to your source file. Lombok will then skip the generation of the constructor and use your constructor.

**Comment by renatokenji** [comment]
It worked. Thank you very much for your support.

```
protected Child(final Child.ChildBuilder<?, ?> b) {
    super(b);
    somePrivateValidationMethodFromChild(b.requiredField);
    this.requiredField = b.requiredField;
}
```
