### ISSUE TITLE
[FEATURE] Configure CI workflows with GitHub Actions

### ISSUE THREAD

**Issue by aalmiray** [projectlombok/lombok#2968]
I did not find any information on CI builds after a quick glance at the project's main page here on GitHub. It'd be great if CI status were to be known and updated periodically. GitHub Actions' matrix capabilities lets you test with multiple OSes and Java versions.

As an aside I'd would had created this issue as a discussion instead of an "issue", perhaps allowing discussions to happen in this repository would be another thing to look at.

**Comment by rzwitserloot** [comment]
The discussions are held on the groups forum. Adding actions is on the radar.
