### ISSUE TITLE
[BUG] Organize imports remove val import

### ISSUE THREAD

**Issue by Rawi01** [projectlombok/lombok#2972]
**Describe the bug**
Using the "Organize imports" command in eclipse removes the `lombok.val` import.

**To Reproduce**
- Create a java file and use `val`
- Use "Organize imports" (Ctrl + Shift + O, Right click -> Source -> Organize Imports)

**Expected behavior**
Eclipse does not remove the used import.

**Version info (please complete the following information):**
 - Lombok version: **edge**
 - Platform: **Eclipse 2021-09**

**Additional context**
I have already started to work on this

**Comment by rzwitserloot** [comment]
I recall that when I wrote the original val support stuff I turned `val` into `@lombok.val String`, keeping that annotation around partly to avoid this scenario. Just in case it helps :)

**Comment by andi-huber** [comment]
Might be a related issue:

Given following snipped ... 

```java
// choosing LocalDateTime is just exemplary, any other type would work as well

public static LocalDateTime now() {
    val now = LocalDateTime.now();
    // now.  <-- trigger code completion
    return now;
}
```
Eclipse (2021-09) fails to fully populate code completion suggestions, that is, in the above case it believes `now` to be of type `Object.class` and does not provide any methods specific to the `LocalDateTime` type.

I'm using my own lombok build from the 'master' with latest commit https://github.com/projectlombok/lombok/commit/ba68962cec99cb1411ed7cac259301edc417ebc5

Side Note: I'm contributer to an ASF project with 160k+ lines of code and we use _lombok_ as much as we can. Apart from code-completion and organize-imports, I'm happy to say that the new _snapshot_ version works pretty solid.

**Comment by Rawi01** [comment]
@rzwitserloot thats exatly what I did too but I used the general `addAnnotation` method and that one always generates a `QualifiedTypeReference` even if you only pass a single type e.g. `val`. As this is a qualified reference eclipse ignores it while searching for used imports. Using an existing helper method in `addAnnotation` fixes the problem.

@andi-huber I noticed that too while fixing this issue and still search for the reason. The resolved type is `Annotation` so lombok does not get called to modify the tree during completion. I hope that I can finish this today or tomorrow.

**Comment by andi-huber** [comment]
Thanks @Rawi01, much appreciated!

**Comment by Rawi01** [comment]
@andi-huber Can you test if my changes fix the problem?

**Comment by andi-huber** [comment]
At a brief glance, looks good to me, thanks! Let me use this version for a day and report back how it goes.

Found a different issue though, (rather minor for me):
```java
@Log4j2
public class AnyClass {
    void action() {
        // log.  <-- trigger code completion
    }
}
```
Eclipse (2021-09) fails to fully populate code completion suggestions.

**Comment by rzwitserloot** [comment]
@andi-huber interesting. This sounds sufficiently unrelated to this issue that I think it'll be easier to track the `@Log4j2` problem with a separate issue. Would you mind filing that?
