### ISSUE TITLE
[BUG] lombok not working with jdk 17 and eclipse 2021-09

### ISSUE THREAD

**Issue by dabbabi** [projectlombok/lombok#2974]
Hi
I tried to install lombok v1.18.20 for eclipse 2021-09 running with jdk 17 on windows 10 following the same installation process as usual but I didn't get anything in the "about eclipse" window. When I start eclipse 2021-09 with jdk 16 it works fine. Is it an issue?
Thank you

**Comment by rzwitserloot** [comment]
Pretty sure we fixed this in edge. Can you check and make sure? [Download the edge release here](https://projectlombok.org/download-edge). I'm keeping an eye on the issue, if you report problems, I'll re-open. We'll get to work on an official release real soon now.
