### ISSUE TITLE
The Java new keyword should be optional.

### ISSUE THREAD

**Issue by CamilYed** [projectlombok/lombok#2982]
**Describe the feature**
The Java new keyword is used to create an instance of the class. In other words, it instantiates a class by allocating memory for a new object and returning a reference to that memory. We can also use the new keyword to create the array object.

Creating class objects is an activity that repeats many times, even in small projects, so 
as programmer I would like to omit the **new** keyword every time I instantiate a given class. 

**Describe the target audience**
All programmers who have had contact with the Kotlin programming language, They will quickly see the benefits of this simple change.

**Comment by rzwitserloot** [comment]
This can be done with lombok but would be an incredibly complicated hack. The java namespace for types and methods are separate, so you can't introduce this feature without defining what is supposed to happen in this case:

```
class Foo {}

class Bar {
    public void Foo() {}

   public void test() {
       Foo(); // this this invoke Foo's constructor, or invoke the Foo method?
}
```

This is not at all intended personally, but I'm sure you'd prefer clear communication over beating around the bush: This is never, ever, going to happen as a lombok feature.
