### ISSUE TITLE
[BUG] @Log fails on nested enums

### ISSUE THREAD

**Issue by charphi** [projectlombok/lombok#2990]
**Describe the bug**
Compilation fails when the annotation @Log is set on a nested enum.

**To Reproduce**
Here is an example:
```java
class Example {

  @Log
  enum Status  { OK, KO }
}
```
The following error appears during compilation:  
`@Log is not supported on non-static nested classes.`

**Expected behavior**
Should compile without error.
Was working fine in 1.18.20

**Version info (please complete the following information):**
 - Lombok 1.18.22
 - all platforms

**Additional context**
Addind the keyword `static` to the enum seems to workaround the problem.

**Comment by rzwitserloot** [comment]
@varkart Feel free! Should be as simple as removing two lines, or at least 'guarding' an existing `if (mods.static) { addTheError(); return; }` with checking if the type is NOT an enum first. Make sure to add your name to AUTHORS as well :) – no need to mess with the docs, we'll review and take care of that part.
