### ISSUE TITLE
[BUG] Equals fails for list member variable

### ISSUE THREAD

**Issue by arvindkgs** [projectlombok/lombok#2997]
**Describe the bug**
Equals generated by Lombok fails for Object containing a List as a member variable

**To Reproduce**
```
class Scratch {
    @Data
    static class Integers {
        List<Integer> numbers = new ArrayList<>();
        public void addNumber(int i) {
            numbers.add(i);
        }
    }
    public static void main(String[] args) {
        Integers p1 = new Integers();
        p1.addNumber(1);
        p1.addNumber(2);
        Integers p2 = new Integers();
        p2.addNumber(1);
        p2.addNumber(2);
        Assert.assertEquals(p1,p2);
    }
}
```

If I define a custom equals as below Assert passes:
```
@Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Integers)) return false;

            Integers point = (Integers) o;

            if (!Objects.equals(numbers, point.numbers)) return false;

            return true;
        }
```

**Expected behavior**
As both the Integers Objects contain similar lists, both should be equal

**Version info (please complete the following information):**
 - Lombok version : 1.18.10
 - Platform : openjdk 11.0.12 2021-07-20
 - Intellij IDE : Community 2021.2

**Additional context**

**Comment by rzwitserloot** [comment]
I pasted the exact snippet you have, with only 2 changes:

* I add imports for `lombok.Data`, `j.u.List`, and `j.u.ArrayList`.
* I replace `Assert.assertEquals` with `System.out.println(p1.equals(p2))`

and it prints 'true' as expected. Presumably you aren't compiling this code with lombok enabled.
