### ISSUE TITLE
[FEATURE] @RequiredArgsConstructor on abstract classes.

### ISSUE THREAD

**Issue by adjiandov** [projectlombok/lombok#3002]
**Describe the feature**
Currently if we have defined final fields in an Abstract class which we want to be always instantiated when another class extends it, this is not possible without creating manual constructor in the implementing class which calls super() of the declared fields in the Abstract class.
The goal of this feature is to be able to do something like the following:
Define abstract class:
```
@RequiredArgsConstructor
public abstract class AbstractSample<T> {
   private final <T> o;
}
```
Define inheriting class:
```
@SomeAnnotation
public class Sample extends AbstractSample<Object> {
}
```

This should generate a class like the following -Delomboked version:
```
public class Sample extends AbstractSample<Object> {
   public Sample(Object o) {
      super(o);
   }
}
```

The @SomeAnnotation could be a new annotation defined for this case or reuse the @RequiredArgsConstructor annotation.
Additionally list of fieldnames could be provided for which the super should be invoked.
I have read that it is difficult to figure out all of the constructors that the abstract class could potentially have. But at least some sort of RequiredAllArgs for both classes should be doable. Annotation which will generate constructor for all required fields in both abstract and implementing class.

**Describe the target audience**
It is common for any java program type to keep some state into an abstract class, especially if this class uses generics. It would save boilerplate code to create constructors in the implementing class and defining the generic type twice (once when extending the abstract class and once in the constructor parameters).
It especially useful when using frameworks where IoC is available like spring and beans are injected on the constructor.

I wasn't sure if it is a bug or a feature, but since it does not exist by now I classified it as feature.
Fingers crossed you would implement this :)

**Comment by foal** [comment]
@rzwitserloot May be review all closed issue because **resolution**  with consideration of using JEP 409 (sealed classes)

**Comment by rspilker** [comment]
If we currently do not allow`@RequiredArgsConstructor` on an abstract class, that constraint can probably be lifted. 

That does not mean we can generate super constructor calls though.
