### ISSUE TITLE
[FEATURE] Make toString optional in @Builder

### ISSUE THREAD

**Issue by dirweis** [projectlombok/lombok#3027]
Hi,

can you please introduce a boolean parameter `toString` in `@Builder`? The mandatory `toString` method creates an overhead for testing if not used. (And I hope I don't go too far when I assert that it's rarely used).

Thank you in advance!
Dirk

**Comment by rspilker** [comment]
Sorry, we're not going to spend time on this. You shouldn't spend any/too much time on testing generated code. Please configure your boss/build/sonar/code coverage tool to ignore code that's annotated with `@lombok.Generated`, and add an instruction to your  `lombok.config`: `lombok.addLombokGeneratedAnnotation = true`.

**Comment by dirweis** [comment]
Yeah, that's an old thing: We developers have our expert view and outside there is the reality. Sorry @rspilker but man, here's what happens in reality if you don't cover Lombok annotations in your tests:
Since there are very creative developers in this world (and yes, there are a lot of them) and don't see what is covered from tests they seem to use Lombok without any brain activity which means in the end: A lot of hidden code that causes side effects. I know much more than 1 team where Lombok is forbidden due to this. From my experience I can tell you this one thing: Won't you EVER suggest test exclusions. Have a nice day
