### ISSUE TITLE
[BUG] When there are many POJO attributes (about 100 +), loading is very slow

### ISSUE THREAD

**Issue by wdyyeah** [projectlombok/lombok#3033]
**Describe the bug**
When there are many POJO attributes (about 100 +), loading is very slow, this Bug recurs every time.

**Version info (please complete the following information):**
 - Lombok version : 0.34-2020.2
 - Java version: 1.8
 - Intelli Idea version: 2020.2.4

**Comment by Rawi01** [comment]
***You're in the wrong place!***

Please do not report any problems or feature requests for the intellij plugin here; file these with the [intellij lombok plugin github repo](https://github.com/mplushnikov/lombok-intellij-plugin/issues) or the [IDEA Youtrack](https://youtrack.jetbrains.com/issues/IDEA).

Thank you!
