### ISSUE TITLE
@Accessors(chain = true) doesn't generate overrides for methods in child classes

### ISSUE THREAD

**Issue by VGoudkov** [projectlombok/lombok#3034]
**Describe the bug**
I have a parent class with a method `setDescription(@NonNull String description)`. Then I have its child. When I try to use `childVar.setDescription("Example")` it returns an instance of the parent class, which doesn't allow writing something like `return new ChildClass().setDescription()`. This also breaks a list of calls in fluent style, if I will call a method of one of the parent classes between child method calls - it returns parent instance and there is no chance to return to the child's context and call their methods.

**To Reproduce**
1. Create a parent class with one setterMethod(of something) and annotate the class with `@Accessors(chain = true)`
2. Create a child class
3. Create a method somewhere and a variable inside it with a type of *child* class
4. Try to assign the result of `new ChildClass().setterMethod(...)` to the variable

**Expected behavior**
the setterMethod(...) call on the child will return ChildClass, because it is called on a ChildClass instance and there are no type conversions inside

**Version info (please complete the following information):**
 - Lombok version: bundled with spring-boot-starter-parent 2.5.6
 - Platform javac 11.0.12 / IDEA Build #IU-212.5284.40

**Comment by craftmaster2190** [comment]
+1

**Comment by rzwitserloot** [comment]
That would require [resolution](https://github-wiki-see.page/m/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution) which is extremely difficult. The amount of feature requests I could write up for when we have resolution is as long as my leg, see keeping them all open is not useful, and there's no worry we lose sight of stuff like this if ever we figure out a way to do resolution correctly. Hence, closed.

**Comment by rzwitserloot** [comment]
Duplicate of #1147
