### ISSUE TITLE
Can't find symbol in the configuration class of the microaut framework, Native set get can inject attributes

### ISSUE THREAD

**Issue by zundaren** [projectlombok/lombok#3035]
package com.example.api.prop;

import io.micronaut.context.annotation.ConfigurationProperties;
import lombok.Data;

@Data
@ConfigurationProperties("config")
public class Config {

    private String a;
    private String b;
    private String c;

//    public String getA() {
//        return a;
//    }
//
//    public void setA(String a) {
//        this.a = a;
//    }
//
//    public String getB() {
//        return b;
//    }
//
//    public void setB(String b) {
//        this.b = b;
//    }
//
//    public String getC() {
//        return c;
//    }
//
//    public void setC(String c) {
//        this.c = c;
//    }
}

**Comment by zundaren** [comment]
Try to generate get set before compiling

**Comment by Rawi01** [comment]
If the framework cannot find the generated methods it is most likely a configuration problem and lombok does not generate the methods. Please provide more information about your problem (a small sample project would be great) and why you think this is a lombok problem.

**Comment by zundaren** [comment]
> If the framework cannot find the generated methods it is most likely a configuration problem and lombok does not generate the methods. Please provide more information about your problem (a small sample project would be great) and why you think this is a lombok problem.

The framework can configure the execution order of lombok， thanks
