### ISSUE TITLE
[FEATURE] @Map to add .map() method

### ISSUE THREAD

**Issue by fredrik-rambris-bhg** [projectlombok/lombok#3039]
With Lombok
`
@Map
class MyClass {
  int id;
  String name;
}
`

Vanilla Java
`
class MyClass {
  int id;
  String name;

  public <R> R map(Function<? super MyClass, R> mapper) {
    return mapper.apply(this);
  }
}
`

Often you translate DTOs to external domain objects and a convenient way is to have a mapper. And to be able to call it directly on the object is consistent with Java libraries such as Optional and Stream.

**Comment by rspilker** [comment]
I understand that what you suggest might be convenient, to add it to a class. But really, in this case one static function anywhere could also fix this.

```java
public static <T,R> R mapApply(T subject, Function<? super T, R> mapper) {
    return mapper.apply(subject)
}
```

```java
import static com.example.util.Util.mapApply;
```

In my opinion, it's not a significant reduction of boilerplate, not worth then maintenance burden.
