### ISSUE TITLE
[BUG] @SuperBuilder: compile warning happens when we use generated builder to set values

### ISSUE THREAD

**Issue by chengco** [projectlombok/lombok#3045]
**Describe the bug**
compile warning happens when we use generated builder to set values, details in `To Reproduce`

**To Reproduce**
compile warnings:
![image](https://user-images.githubusercontent.com/350708/143538596-b3b8b539-7a70-4579-9041-b606b9b78d43.png)
![image](https://user-images.githubusercontent.com/350708/143538696-5a51a2a6-9e98-46c1-a71f-de8d19b8516c.png)

can reproduce using code below:

```java
@SuperBuilder
public class Student extends Person {
    private int age;
    private String dateOfBirth;
    private List<String> habits;

    public static void doSomething() {
        StudentBuilder studentBuilder = Student.builder()
                .age(10);

        //for some reason, we need set values to other fields using studentBuilder
        studentBuilder.dateOfBirth("2011-01-01")
                    .habits(List.of())
                    .name("ss")
                    .build();
    }
}

@SuperBuilder
abstract class Person {
    private String name;
}
```

**Expected behavior**
No Compile Warnings

**Version info (please complete the following information):**
 - Lombok version 1.18.20
 - Platform javac 11

**Additional context**
we can use code below to avoid this issue, but not sure if there is a best way.
```java
StudentBuilder<?, ?> studentBuilder = Student.builder()
                .age(10);
```

**Comment by janrieke** [comment]
Yes, the "double-wildcard" variable is the only way. `@SuperBuilder` instances must have type variables.

Use `var` if you don't like the syntax.

**Comment by chengco** [comment]
Thanks, actually I tried `var`, it works well.
