### ISSUE TITLE
[BUG] Excluding SLF4J

### ISSUE THREAD

**Issue by willianbumba** [projectlombok/lombok#3048]
Good Morning every one?

When we use lombok and spring boot in the same project, there have conflit of multiple SLF4J binding. And slow documentation to explain show exclude SLF4J from lombok.

**Comment by janrieke** [comment]
Lombok does not bring any dependencies with it. There must be another problem with your setup.

**Comment by abimarank** [comment]
We are using lombok with spring boot without any issues. Can you share your POM?
