### ISSUE TITLE
[BUG] Classes with lombok annotations not compiling in root project with gradle

### ISSUE THREAD

**Issue by Kalyan-M** [projectlombok/lombok#3051]
**Describe the bug**
I have multi-project java 8 build with gradle 7.3 and it has code in the root project also. I have added this:
```
plugins {
    id "io.freefair.lombok" version "6.3.0"
}
```
in the root build.gradle and this:
```
plugins {
    id "io.freefair.lombok"
}
```
in all the sub-project build.gradle files.

Everything was working fine but I updated the version of an internal dependency. Even though I can't see any unexpected changes in ./gradlew dependencies outputs, especially for the root project, the compilation for root project after version update is failing. The sub-projects compile fine.
I can see that lombok is present in classpath in both the cases. Infact, I don't see any difference related to lombok in both the cases.
![image](https://user-images.githubusercontent.com/24321730/144087897-2e1efaf9-9876-4f7f-89bb-62d6a8a85159.png)

The compilation fails due to getters and setters not being present and also @Slf4j annotation fails.

I've also tried adding:
```
compileOnly 'org.projectlombok:lombok:1.18.22'
annotationProcessor 'org.projectlombok:lombok:1.18.22'
testCompileOnly 'org.projectlombok:lombok:1.18.22'
testAnnotationProcessor 'org.projectlombok:lombok:1.18.22'
```
in all build.gradle files but same result.

This looks like a bug to me but wanted to know if I'm missing something here?

**Expected behavior**
Lombok works for the root project too.

**Comment by Rawi01** [comment]
If all lombok generated code disappears at the same time it is either a configuration problem or the java compiler does not invoke annotation processors. The later happens for examples if you try to static import a non existing class.

**Comment by rzwitserloot** [comment]
1. `io.freefair.lombok` - that's not us. Sounds like a contributor that has kindly publicized a gradle plugin that smooths over lombok usage. However, if that's the source of the problem, you'd have to file a bug with that project.
2. If you downgrade back to 1.18.20 does the problem go away again? As in, is the _only_ difference 1.18.20 vs 1.18.22?
3. Did you try the latest edge?

As is, there isn't enough information. It's possible that just having a multimodule gradle project (I have no idea what that means) and any lombok anywhere is enough to reliably trigger this. But even that is not clear.

**Comment by rzwitserloot** [comment]
Given no information has been provided, I'm closing this due to lack of detail. If anybody provides the required detail, I will re-open it if neccessary.
