### ISSUE TITLE
[BUG] delomboked class is missing @Builder.Default initialization in no args constructor

### ISSUE THREAD

**Issue by Alexey007gold** [projectlombok/lombok#3053]
**Describe the bug**
There is a parent class

```
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class DTOParent {
    private String a;
}
```

and a child, using `@SuperBuilder` and `@Builder.Default`
```
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
public class DTO extends DTOParent {
    @Builder.Default
    private Integer number = 5;
}
```
The problem is that lombok and delombok generate different result.
Lombok on the left and delombok+compile on the right
![image](https://user-images.githubusercontent.com/25862367/144285490-589630e7-e6ef-4668-ba23-9b1b76503ed7.png)

**Expected behavior**
Lombok initializes the field annotated with @Builder.Default in no-args constructor, as I believe is expected
Delomboked code is missing that step

**Version info (please complete the following information):**
 - Lombok 1.18.22

**Comment by janrieke** [comment]
How do you delombok? It looka like delombok uses Lombok <= 1.18.0.

**Comment by Alexey007gold** [comment]
> How do you delombok? It looks like delombok uses Lombok <= 1.18.0.


```
> java -jar lombok.jar version
 v1.18.22 "Envious Ferret"
> java -jar lombok.jar delombok src/main/java -d src-delomboked
```
![image](https://user-images.githubusercontent.com/25862367/144463386-bca305f4-9c56-442e-b823-34514fb0844e.png)

Screenshot in the issue description is showing a two .class files, decompiled with Intellij. First one was compiled directly using lombok, the second one compiled from delomboked sources.

**Comment by Rawi01** [comment]
I still don't know how you managed to generate the code on the left side but I think that you actually found a bug. In 3987f54b8321ae666cb1c774aef5986df05bf4ad support for `@Builder.Default` in `@NoArgsConstructor` was added. This works with `javac` if you use `@Builder` but not if you use `@SuperBuilder`. In `ecj` both annotations generate the initialization in the constructor so it most likely is an `javac` specific problem.
