### ISSUE TITLE
[BUG] log4j出现严重漏洞，请升级log4j至2.15版本

### ISSUE THREAD

**Issue by 371486927** [projectlombok/lombok#3062]
https://open.work.weixin.qq.com/wwopen/mpnews?mixuin=3_HVCQAABwBHKvwGAAAUAA&mfid=WW0310-6x9-BwAABwB7tPj8XTxKnQJm-1T5c&idx=0&sn=d38bbc1075de2cdc8c9f67fc6d09894a&notreplace=true

log4j出现严重漏洞，请升级log4j至2.15版本

**Comment by rspilker** [comment]
I just assume this is a duplicate of #3063 3063
