### ISSUE TITLE
When we will be able to find the release with log4j vulnerbality fix

### ISSUE THREAD

**Issue by vtanuj** [projectlombok/lombok#3067]
Log4J vulnerability is fixed with version upgrade but still the latest release is not available.

Reference https://github.com/projectlombok/lombok/commit/c10b47a5d12b94570067c4b412c3018630300e7f

When can we expect a new release with this vulnerability fixed?

**Comment by janrieke** [comment]
Lombok is not affected by this vulnerability. See #3063.
