### ISSUE TITLE
[BUG] Eclipse - SuperBuilder toBuilder=true with Singular ImmutableList Guava field

### ISSUE THREAD

**Issue by balazstbb** [projectlombok/lombok#3070]
**Describe the bug**

The problematic combination is Eclipse Lombok plugin + Class with SuperBuilder(toBuilder=true) and a Guava ImmutableList field with Singular annotation.

The problem does NOT occur if one of the following conditions are matching
- the toBuilder is false (or not defined, so false)
- no Singular annotation on the ImmutableList field
- using List instead of ImmutableList as field type

**To Reproduce**

```
package lombok.superbuilder.eclipse;

import lombok.Getter;
import lombok.Singular;
import lombok.experimental.SuperBuilder;

import com.google.common.collect.ImmutableList;

@Getter
@SuperBuilder(toBuilder = true)
public class Parent {
    private final String stringValue;
    private final @Singular ImmutableList<String> stringItems;
}
```

**Expected behavior**

Should NOT have an error: "com.google.common.collect cannot be resolved to a type"

```
Multiple markers at this line
	- com.google.common.collect cannot be resolved to a type
	- overrides java.lang.Object.toString
	- implements lombok.superbuilder.eclipse.Parent.ParentBuilder<lombok.superbuilder.eclipse.Parent,lombok.superbuilder.eclipse.Parent.ParentBuilderImpl>.
	 build
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Lombok Eclipse plugin version: 1.18.22
 - Project Java version: 11.0.12
 - Project Maven version: 3.8.4
 - Eclipse version: 2021-12 (4.22)
 - Eclipse Java version: 11.0.12
 - Eclipse Maven (M2E) version: 1.19.0.20211116-0804
 - Eclipse Java Development Tools version: 3.18.1000.v20211124-1800

**Additional context**

This problem occurs only with the Eclipse plugin. Does not throw any error, and works well compiling with maven CLI. I have not tryed in other IDE they may fail as well.

**Comment by janrieke** [comment]
Can comfirm. Only affects Eclipse and `@SuperBuilder`.

**Comment by janrieke** [comment]
I'm working on it. I already have (yet failing) tests. Also found a related problem also affecting javac.
