### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by zt317** [projectlombok/lombok#3072]
Is it possible that @Builder annotation denote default value from field definition?

e.g. If the class is like this:
```java
@Builder
@Data
public class Animal {
   private int legs = 4;
}
```
When using @Builder and generating an Animal object without explicitly setting legs property, it'll become 0 because the inner AnimalBuilder's legs is 0 by default. 

Is there a way to build an Animal Object with 4 legs by default?

**Comment by Rawi01** [comment]
You can use defaults by adding `@Builder.Default`.
