### ISSUE TITLE
[BUG] Documentation for "NonNull"

### ISSUE THREAD

**Issue by CC007** [projectlombok/lombok#3073]
**Describe the bug**
The Vanilla Java section on [the `@NonNull` documentation page](https://projectlombok.org/features/NonNull) doesn't show the correct exception message.

**To Reproduce**
Example code Main.java: 
```java
class ClassWithNonNull {
    public static void doSomething(@NonNull String param) {
        ...
    }
}
public class Main {
    public static void main(String[] args) {
        ClassWithNonNull.doSomething(null);
    }
}
```

**Expected behavior**
I infer from the website with its example that this would produce the following exception message:
`param is marked @NonNull but is null`, but I get: `param is marked non-null but is null`

**Version info:**
 - Lombok version: 1.18.20
 - Platform: javac 17.0.1

**Comment by sparhidev** [comment]
Hello Maintainers, Let me know if I can pick this up

**Comment by rspilker** [comment]
A pull-request will be accepted.

**Comment by sparhidev** [comment]
The documentation clearly states that :
> When lombok generates a null-check if statement, by default, a java.lang.NullPointerException will be thrown with 'field name is marked non-null but is null' as the exception message.

The confusion mentioned above is related to the custom message example in the overview section of the documentation.
> The null-check looks like if (param == null) throw new NullPointerException("param is marked @NonNull but is null"); and will be inserted at the very top of your method.

Note : The example given has a custom exception message thrown by NPE. The default exception message is '_field name_ is marked non-null but is null'

**Comment by sparhidev** [comment]
PR created for this #3090.
