### ISSUE TITLE
[BUG][JPAModelGen] Lombok won't work when annotation involves static methods

### ISSUE THREAD

**Issue by hall-wong** [projectlombok/lombok#3074]
**Describe the bug**
Lombok won't work when anntotaion involved static methods

I had these working fine at `tag: working_well`, but once I refactor some util class with `@UtilityClass` annotation, things go wrong.

**To Reproduce**

I've a codebase to reproduce this issue: https://github.com/hall-wong/lombok-issue

Funny things: refactor package  to a new name or drop some field will stop reproducing the issue.

**Expected behavior**
Compile success.

**Version info (please complete the following information):**
 - Lombok 1.18.22
 - Platform faild on openJdk 11.02 and OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
 - OS Windows 10 and Mac Big Sur
 - Gradle check the wrapper.properties

**Comment by rspilker** [comment]
I'm sorry, but the code you shared is not a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/).

**Comment by hall-wong** [comment]
> I'm sorry, but the code you shared is not a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/).

I tried to trim the codes, but if I do so, the issue won't reproduce. So it cannot be short.

And the code is about to reproduce the issue, so it won't be correct. But you set the HEAD to the tag `working_well`, it will be alright.

**Comment by hall-wong** [comment]
> Your 'platform' is, apparently, OpenJDK. Which has no refactoring tools. What are you refactoring with? `sed`? Prayer? We definitely need more details.

A refactoring tool in JDK? This is beyond my knowledge. 

I knew `sed`, but it seemed to be a stream editor, I can't see the relation between this and Lombok.

**Comment by Rawi01** [comment]
In `TransactionStatisticsRepository` you try to import the static methods generated by `@UtilityClass`. This is not possible, see #2044
