### ISSUE TITLE
[BUG] Bad Checker Framework annotation This

### ISSUE THREAD

**Issue by janrieke** [projectlombok/lombok#3081]
When setting `checkerframework = 4.0`, lombok generates `@org.checkerframework.common.returnsreceiver.qual.This` on the setter methods of `@Builder`/`@SuperBuilder`. However, lombok generate it as a method annotation, but in fact it's a type annotation for the return type.

This results in a compile error.

**To Reproduce**

Compile 

    @lombok.Builder
    public class BuilderTest {
        String name;
    }

with lombok.config:

    lombok.addNullAnnotations = checkerframework
    checkerframework = 4.0

**Expected behavior**
Generate `@This` as a type annotation for the return type.

Furthermore, the minimum version for `@This` should be reduced, as it is already supported by Checker Framework 3.10.0 (maybe earlier).

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Checker Framework version: 3.16.0
 - Platform: javac 11.0.12

**Comment by janrieke** [comment]
Branch [janrieke:checkerFrameworkFixThis](https://github.com/janrieke/lombok/tree/checkerFrameworkFixThis) contains a fix, but I wait for #3080 before I create a PR.

**Comment by rspilker** [comment]
@janrieke #3080 has been merged.
