### ISSUE TITLE
Undocumented change in 1.18.22

### ISSUE THREAD

**Issue by andye2004** [projectlombok/lombok#3083]
Hi, there appears to be an undocumented change to `@Builder` and the generated code that has affected our MapStruct `@AfterMapping` code generation. There is a known issue (which we have only just discovered) in MapStruct when using builders - see [here](https://github.com/mapstruct/mapstruct/issues/1862) - and after upgrading Lombok from 1.18.20 to 1.18.22 we are now triggering the documented behaviour. In earlier version of Lombok this is not the case, e.g. MpStruct is not detecting the builders and is generating code as expected.

Can someone confirm what may have changed which means MapStruct is now detecting the builder to be available where it previously could not?

**Comment by Rawi01** [comment]
Generated classes and methods are now visible for other annotation processors, the PR is #2718. I think you have to update your mapper configuration...

**Comment by andye2004** [comment]
@Rawi01, many thanks for the confirmation.

**Comment by Rawi01** [comment]
You're welcome, I'm sorry that this change causes some problems.
