### ISSUE TITLE
[BUG]fName field naming difference with jdk

### ISSUE THREAD

**Issue by SealinRepo** [projectlombok/lombok#3086]
Hi, I found a field naming problem:
Field name like xXxxx(The first letter is lowercase, the second letter is uppercase).Our database was used many years ago, fields are named starting with "f", table names are starting with "t", and views are starting with "v" (this is the database naming convention at that time)
Lombok generated name is getXXxxx, and the norm for jdk, jackson, mybatis and most frameworks is getxXxxx.
In this case, json will not be able to parse the content, the persistence layer will not be able to assign values, and many other problems. Could you fix this kind of naming method? This will be helpful for development work .
thanks.

**Comment by rspilker** [comment]
I think you should use the [Accessors feature](https://projectlombok.org/features/experimental/Accessors).

If this is common in your whole codebase, in the upcoming version of lombok you can use `lombok.config` to fix this:

```Shell
lombok.accessors.capitalization = beanspec
```

In the meantime, we can offer to get rid of the letters 'f'and 'v' by using
```Shell
lombok.accessors.prefix += f
lombok.accessors.prefix += v
```

If that's not what you want

**Comment by SealinRepo** [comment]
> 我认为您应该使用[访问器 功能](https://projectlombok.org/features/experimental/Accessors)。
> 
> 如果这在你的整个代码库中很常见，那么在即将推出的龙目岛版本中，你可以用它来解决这个问题：`lombok.config`
> 
> ```shell
> lombok.accessors.capitalization = beanspec
> ```
> 
> 同时，我们可以通过使用
> 
> ```shell
> lombok.accessors.prefix += f
> lombok.accessors.prefix += v
> ```

I'll try it, thank you very much^_^
