### ISSUE TITLE
[BUG] Netbeans Maven: Package Java.util.logging is not visible.

### ISSUE THREAD

**Issue by Angular-Angel** [projectlombok/lombok#3088]
**Describe the bug**
I get an error in Netbeans IDE when using Lombok - it says that 'Package Java.util.logging is not visible -Package Java.util.logging is declared in module java.logging, but lombok does not read it'. The project still builds and runs without this causing any errors, but it shows errors in my IDE for all files that import from java.util.logging. I have the following in my POM for compiler args - I think I need to add something to it, or edit it a bit?

`
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED</arg>
                                <arg>-J--add-exports=jdk.compiler/com.sun.tools.javac.logging=ALL-UNNAMED</arg>
                                <arg>-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED</arg>`

I tried switching the 'add exports' to 'add opens' for the java.util and java.logging.

**To Reproduce**
Download and building my project [here](https://gitlab.com/AngularAngel/omnicraft) should do it, though be warned you have to also download, switch to a specific git branch, and build another project first. That's a fairly large effort, I know, so I wouldn't reccemmend doing it unless it seems a pressing need. I expect there's an easier way to reproduce the issue, but I don't want to put in the time to figure it out, as I expect this will probably be resolved by someone posting one line saying 'Add this to your POM beneath the other entries: <something>', or something similarly simple. If nobody knows any quick solutions to the problem, I can put together a minimal reproduction of the issue, but I don't think that will be necessary.

**Expected behavior**
I expect to not have my IDE report errors that don't actually seem to exist or stop me from building the project.

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Platform: Netbeans 12.6 With Maven 3.8.3

**Additional context**
I am also using Checker Framework, so it is possible that that is part of the problem.

**Comment by Angular-Angel** [comment]
I also tried adding: '<arg>--add-modules=java.logging</arg>' to the compilerArgs, and that didn;t work either.

**Comment by rspilker** [comment]
Lombok itself does not depend on `java.util.logging`, we just generate source code. You have to provide your own implementation. I am not a Netbeans expert. What happens if you type the code to create a logger in your source code yourself?

**Comment by Angular-Angel** [comment]
I just went and used java.util.logging, yeah, and that worked.
