### ISSUE TITLE
callSuper = false not treated as default

### ISSUE THREAD

**Issue by macwirbel** [projectlombok/lombok#3089]
(lombok version 1.18.22) Used not `@Data` but only `@Getter`/`@Setter` with `@EqualsAndHashCode` without any parameters. Expected that the option `callSuper = false` is silently used because it is indicated as default.
But that is not the case, the generated code does call `super.equals()` unless explicitely `callSuper = false` is demanded as parameter.

**Comment by rzwitserloot** [comment]
Your request is unclear - please change it to include an example class, what lombok produces (toss it through `java -jar lombok.jar delombok -p YourExample.java`), and which line you feel is in conflict with the documentation. Then I'll re-open this issue.
