### ISSUE TITLE
[BUG] Log4j from lombok.

### ISSUE THREAD

**Issue by mariusica98** [projectlombok/lombok#3092]
I'm using log4j from lombok and I don't know how to update to the latest version. The import: import lombok.extern.log4j.Log.
In the POM i have: 
 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.5</version>
 </dependency>
 <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.5</version>
 </dependency>

I don't know how to upgrade to log4j, do I need to upgrade lombok or change the version in the tree?.

Thank you!

**Comment by rspilker** [comment]
No need to update lombok, update your own (other) dependencies: #3063

**Comment by mariusica98** [comment]
OK, and in lombok is there the latest version of log4j? and 2.17.1? i mean the update will be:
org.slf4j
slf4j-api
2.17.1


org.slf4j
slf4j-log4j12
2.17.1

**Comment by janrieke** [comment]
There is no log4j in Lombok. Please read #3063 for details.
