### ISSUE TITLE
[BUG] Why can RequiredArgsConstructor generate null-check statement for spring NonNull

### ISSUE THREAD

**Issue by xma08** [projectlombok/lombok#3100]
**Describe the bug**
I know if we put a `lombok.NonNull` on a field. Then lombok `RequiredArgsConstructor` helps generate a constructor with a null-check statement. However, if I replace `lombok.NonNull` with `org.springframework.lang.NonNull`, it could still generate a null-check statement. Does `RequiredArgsConstructor` recognize other packages' `NonNull`? Is this expected?

Source:
```
import lombok.RequiredArgsConstructor;
import org.springframework.lang.NonNull;

@RequiredArgsConstructor
public
class MyTest {
  @NonNull private String username;
}
```

Generated:
```
import lombok.RequiredArgsConstructor;
import org.springframework.lang.NonNull;

@RequiredArgsConstructor
public
class MyTest {
  @NonNull String field;

  public MyTest(@NonNull final String username) {
      if (username == null) {
        throw new NullPointerException("username is marked non-null but is null");
      }
      this.username = username;
  }
}
```

**Comment by Rawi01** [comment]
Yes, this is expected. Lombok contains a [list of know `NonNull` annotations](https://github.com/projectlombok/lombok/blob/36db0524e4d0f6bc6fa2440b0df2c425c4d130fc/src/core/lombok/core/handlers/HandlerUtil.java#L84) and generates the `null`-checks if it detects one of these annotations.

**Comment by rzwitserloot** [comment]
@xma08 Yes - as @Rawi01 said, we have a list of types we know specifically mean 'null is never okay here'.

3 points:

* There are many nonnull annotations that do _not_ mean that. For example, JPA/Hibernate's `@NotNull` means: When making the sql `CREATE TABLE` statement, add a non-null constraint. But instances of this class can have `null` here - that just means: "When inserting, let the DB engine generate the default here". JPA's NotNull is not in our list. It's possible we misjudged `org.springframework.lang.NonNull` (though, fixing that now would be backwards incompatible, oof, I hope not). If that's the problem, please post an explanation, with some proof (links to documentation and the like) – most of us don't use spring.
* This feature is specifically for the setter and the constructor. Lombok will generate nullchecks in any method you write if you use specifically `@lombok.NonNull` on the parameter. That feature (if `@NonNull` on a handwritten method or constructor, inject a nullcheck) requires specifically using `@lombok.NonNull`).
