### ISSUE TITLE
[FEATURE] @SuperConstructor

### ISSUE THREAD

**Issue by CheeseTastisch** [projectlombok/lombok#3110]
**Describe the feature**
My idea would be to add an annotation `@SuperConstructor` which, on classes, creates a constructor that is equal to and calls the super-constructor.

Lomboked:
```
public class LombokIdeaSuperConstructor{

    @RequiredArgsConstructor
    public class FirstClass {

        private final String string;
        
    }

    @SuperConstructor
    public class SecondClass extends FirstClass {
        
    }

}
```

Plain Java:
```
public class LombokIdeaSuperConstructor{
    
    public class FirstClass {
        
        private final String string;

        public FirstClass(String string) {
            this.string = string;
        }
    }
    
    public class SecondClass extends FirstClass {

        public SecondClass(String string) {
            super(string);
        }
        
    }
    
}
```

**Describe the target audience**
Any developer working with class hierarchies would benefit from this project.

**Comment by rzwitserloot** [comment]
Requires [resolution](https://github-wiki-see.page/m/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution). Love the feature idea, but we can't deliver it within the foreseeable future.
