### ISSUE TITLE
[BUG] Lombok stops processing annotations

### ISSUE THREAD

**Issue by ginkel** [projectlombok/lombok#3119]
**Describe the bug**
We've got a Java 17 and Spring Boot based multi-module project where Lombok suddenly stopped processing annotations after a non-trivial code change, which causes errors such as:

```
[ERROR] Foo.java:[46,13] cannot find symbol
[ERROR]   symbol:   variable log
[ERROR]   location: class Foo
```

when the `@Slf4j` annotation is "ignored". Other annotations, such as `@Data` and `@Getters` are equally affected, though.

Reverting the respective commit resolves the issue, but figuring out what exactly is triggering it has failed so far.

Lombok is registered as an annotation processor with the Maven Compiler Plugin.

As this is most likely insufficient information to troubleshoot the issue: Is there a way to cause Lombok to emit debug messages during annotation processing to get an insight into what it is doing / if it is running at all?

**To Reproduce**
tbd

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Platform: Maven (`javac 17.0.2`)

**Additional context**
n/a

**Comment by janrieke** [comment]
Does that commit change static imports? Then that is probably the cause.

**Comment by ginkel** [comment]
Wow, there was indeed a new fully-qualified static import for a static method that indeed caused the issue. Thanks a lot!

One question remains: Is this supposed to happen or should Lombok handle this more gracefully?

**Comment by janrieke** [comment]
Well, it's obviously not supposed. The problem is that in this case the compiler bails out before even calling Lombok. So Lombok is a bit limited in solving this issue :wink:

The problem is also mentioned in the small print here: https://projectlombok.org/features/experimental/UtilityClass

**Comment by ginkel** [comment]
Makes sense, thanks for the clarification and the speedy help!
