### ISSUE TITLE
[BUG] @EqualsAndHashCode generates unexpected annotations

### ISSUE THREAD

**Issue by solf** [projectlombok/lombok#3122]
**Describe the bug**
@EqualsAndHashCode is supposed to take into account lombok.addNullAnnotations configuration, however even when I specify CUSTOM annotations that I want to use, it still appears to add 'org.eclipse.jdt.annotation.Nullable' which results in 'org.eclipse.jdt.annotation.Nullable cannot be resolved to a type'

Note: this is basically a re-write of #3055 -- however I believe this issue makes a stronger case that the observed behavior is a bug by focusing on different configuration.

**To Reproduce**
Eclipse 2019-12 (4.14)
-javaagent:lombok-1.18.22.jar
Maven:
```
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.22</version>
			<scope>provided</scope>
		</dependency>	
		<dependency>
			<groupId>io.github.solf</groupId>
			<artifactId>extra2-epl</artifactId>
			<version>2.7.0</version>
		</dependency>
```

lombok.config
`lombok.addNullAnnotations=CUSTOM:javax.annotation.Nonnull:javax.annotation.Nullable`

Source code:
```
import org.eclipse.jdt.annotation.NonNullByDefault;

import lombok.EqualsAndHashCode;
import lombok.Setter;

@NonNullByDefault
@EqualsAndHashCode
public class LombokFail
{
	@Setter
	private String field = "";
}
```

**-> org.eclipse.jdt.annotation.Nullable cannot be resolved to a type**

Commenting out @NonNullByDefault fixes the issue

I think what Lombok is actually doing -- it's putting both annotations on the method -- one as configured in lombok.addNullAnnotations and one of 'org.eclipse.jdt.annotation.Nullable' because it assumes this is necessary.

This assumption is wrong -- both Eclipse and Idea allow user to specify which annotations are used for Nullable/NonNull and the fact that org.eclipse.jdt.annotation.NonNullByDefault is used does not imply that org.eclipse.jdt.annotation.Nullable must be used (or is indeed available on the classpath).

**Expected behavior**
Lombok should respect lombok.addNullAnnotations and only put the requested custom annotation on the method; Lombok should not make assumptions about what my configuration might be and try to put 'guessed' annotation on the method.

**Version info (please complete the following information):**
Eclipse 2019-12 (4.14)
-javaagent:lombok-1.18.22.jar

**Additional context**

**Comment by rzwitserloot** [comment]
>  and the fact that org.eclipse.jdt.annotation.NonNullByDefault is used does not imply that org.eclipse.jdt.annotation.Nullable must be used (or is indeed available on the classpath).

That's crazy. I would expect lombok to generate it, and would be highly confused if there's even a setting available to tell lombok not to. So, we can't default the behaviour to not doing it, and we can't add the setting.

Request still denied.
