### ISSUE TITLE
[BUG] Lombok + eclipse + null-analysis: full compile OK, incremental incorrect

### ISSUE THREAD

**Issue by JohnPaulTaylorII** [projectlombok/lombok#3133]
**Describe the bug**
When Eclipse performs an incremental build with null analysis enabled, it cannot see the annotations on Lombok generated code outside of the current file.

**To Reproduce**

lombokeclipse/LombokCheck.java
```
package lombokeclipse;
public class LombokCheck {
    public static void main(String[] args) {
        new NullCheck().setTheString(null);
    }
}
````
lombokeclipse/NullCheck.java
```
package lombokeclipse;
@org.eclipse.jdt.annotation.NonNullByDefault
@lombok.Setter
public class NullCheck {
    private @Nullable String theString;
}
```
When cleaning the project (full build), everything is fine. Making a non-change to LombokCheck (add or remove a space for example), causes the call to setTheString to produce an error that the value must not be null. It appears that the compiler sees the @NonNullByDefault in NullCheck's source, and it sees the setTheString method just fine, but it does not see the @Nullable annotation on the generated method.

**Expected behavior**
Eclipse performs null analysis correctly during incremental build.

**Version info**
 - Lombok version: 1.18.22
 - Eclipse (checked versions 2020-06 through 2021-12)

**Additional context**
Attached an Eclipse project demonstrating the issue (lombok jar not included for size; add your own).
[lombok-test.zip](https://github.com/projectlombok/lombok/files/8233683/lombok-test.zip)

**Comment by JohnPaulTaylorII** [comment]
This same problem exists with EqualsAndHashCode. I tried adding the appropriate bits to the Equals and CanEquals methods, but was surprised to find it did not seem to fix the issue.

**Comment by JohnPaulTaylorII** [comment]
This same problem exists with EqualsAndHashCode. I tried adding the appropriate bits to the Equals and CanEquals methods, but was surprised to find it did not seem to fix the issue.

**Comment by JohnPaulTaylorII** [comment]
Figured out the issue on my end and created a PR with additional changes for this.

**Comment by rzwitserloot** [comment]
@JohnPaulTaylorII Hmm, @Rawi01 just added a PR a day before yours which seems a bit simpler and is playing in the same space (namely, setting the `Eclipse.HasTypeAnnotations` flag). Can you check if @Rawi01's patch (commit b50a9c2, currently already in lombok's main branch) fully addresses this issue, and if not (and yours does), let me know?

Reopening for a moment, until this is resolved.

**Comment by Rawi01** [comment]
My PR only handles copied annotations, the new one is about generated `@Nullable`/`@NonNull` annotations. Adding the bits for these annotations makes sense to me.

**Comment by JohnPaulTaylorII** [comment]
@rzwitserloot Sorry for the confusion. I had pulled @Rawi01's changes and realized that it didn't completely fix the bug, so I made a PR with additional changes. The two PRs complement each other and both are necessary to close this issue.
