### ISSUE TITLE
[FEATURE] Multi-language website support

### ISSUE THREAD

**Issue by ValeryVerkhoturov** [projectlombok/lombok#3139]
**Feature description**
Enable  contributing translation into different languages of the Lombok website documentation.

**The target audience**
Translate contribution is  volunteering.
Consumer is everyone for whom English is not native.

**Comment by rzwitserloot** [comment]
I'm not opposed; one problem is: How do we confirm that a translation is fit for purpose? I guess we can toss it through google translate to at least confirm it's not complete hogwash.

Thing is, __you can already do this__. Just.. send a PR, the website is in this github project. You'll also have to do the work of adding a little flag and all that. @rspilker is chief website wrangler. I'm sure he'll be willing to put in a little time to automate picking the right language based on the incoming Accept-Language header, but that's the only small detail you can't fix with a PR.

**Comment by Rawi01** [comment]
You can also use some tool to manage these translations (e.g [Weblate](https://weblate.org/)). It also helps to keep the translation up to date.

**Comment by rspilker** [comment]
I have a few problems with this:
* As Reinier already mentioned, how can we verify the translation? Is it okay, or possibly misleading?
* My browser already offers to translate any page that is not in any of the languages I understand
* There are several online tools that can translate a web page
* Our HTML is already tagged `lang="EN"`. This should help translation tools

In my day job, I have a some experience with keeping documentation up-to-date across multiple languages. It is really hard.

So in my moderately expert opinion, we should not add translations.
