### ISSUE TITLE
[BUG] @Builder requires inner records to be explicitly static

### ISSUE THREAD

**Issue by RMSD** [projectlombok/lombok#3140]
**Describe the bug**
An inner record with a builder reports "@Builder is not supported on non-static nested classes." despite `record` being implicitly static.

**To Reproduce**
Simple class that should reproduce it (reduced from my complex service)
```java
public record Outer(String hello) {

   @Builder
   public Outer {
   }
   
   public record Inner(String world) {
   
      @Builder
      public Inner {
      }
   }
}
```

Which results in:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project svc: Compilation failure:
[ERROR] /Users/rajat.murthi/Documents/Repos/svc/src/main/java/com/test/Outer.java:[9,9] @Builder is not supported on non-static nested classes.
```

**Expected behavior**
`@Builder` should work as expect as in outer records and normal static inner classes.

**Version info (please complete the following information):**
 - Lombok version: 1.8.22
 - Platform:
 
 java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)

**Additional context**
Adding the redundant `static` keyword to the inner class seems to fix the problem.

https://openjdk.java.net/jeps/395:

```text
A record class can declare nested types, including nested record classes. If a record class is itself nested, then it is implicitly static; this avoids an immediately enclosing instance which would silently add state to the record class.
```

**Comment by rspilker** [comment]
We're currently looking into the whole is-this-thing-static code. I expect that that will address this issue as well.

**Comment by irisindigo** [comment]
I think lombok version 1.18.24 fixed this issue.

**Comment by rzwitserloot** [comment]
@irisindigo That's nice to hear :)
