### ISSUE TITLE
[FEATURE] Lombok Maven+ECJ bootstrap agent

### ISSUE THREAD

**Issue by jopatai** [projectlombok/lombok#3143]
I have created (but not published) a small bootstrap agent to make using Lombok with Maven and the ECJ compiler easier. That combination currently requires either a non-portable build (as described on the setup/ecj page) or putting lombok.jar into source control with your project. The bootstrap agent allows you to contain the build in your pom.xml without embedding lombok.jar.

The project is located at https://github.com/JohnPaulTaylorII/lombok-maven-ecj-bootstrap.

Questions:
1. Is this worth including in the projectlombok space rather than mine? (I know it's fairly niche.)
2. If not, is it okay to publish this artifact using the org.projectlombok group, or would you prefer if I use a different one?
3. Would a PR updating the setup/ecj page to explain this alternative setup be accepted?

Thanks for your consideration.

**Comment by rzwitserloot** [comment]
I don't mind either the jar file directly in the projectlombok git repo or this solution; but how do we efficiently 'get it' there? We could fold it into lombok.jar and ask users to e.g. run `java -jar lombok.jar setupMavenBootstrapper` which unpacks this tiny jar and makes that `.mvn/jvm.config` file as well. Perhaps it even adds/fixes your pom.xml file. That sounds slightly nicer, perhaps?

**Comment by JohnPaulTaylorII** [comment]
I hadn't been able to come up with a very good distribution technique... However, that does sound like a pretty good solution. I can certainly work on that integration.
