### ISSUE TITLE
[BUG] Fluent builder with default nested field fails to resolve types correctly.

### ISSUE THREAD

**Issue by ascopes** [projectlombok/lombok#3145]
**Describe the bug**
Type inference seems to be incorrect for a specific test case I came across. Adding explicit (redundant) casts appears to fix the issue.

**To Reproduce**
1 .Use the following dependencies in a `pom.xml`:

```xml
<dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.22</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>io.projectreactor.kafka</groupId>
      <artifactId>reactor-kafka</artifactId>
      <version>1.3.8</version>
    </dependency>

    <dependency>
      <groupId>com.github.javafaker</groupId>
      <artifactId>javafaker</artifactId>
      <version>1.0.2</version>
    </dependency>
</dependencies>
```

2. Create the following class:

```java
package org.example;

import com.github.javafaker.Faker;
import lombok.Builder;
import lombok.Data;
import lombok.experimental.Accessors;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.TopicPartition;
import reactor.kafka.sender.SenderResult;

public class SomeTest {

  private static final Faker faker = new Faker();

  @Accessors(fluent = true)
  @Builder
  @Data
  private static class MockSenderResult implements SenderResult<String> {

    @Builder.Default
    private final RecordMetadata recordMetadata = new RecordMetadata(
        new TopicPartition(
            faker.internet().slug(),
            faker.random().nextInt(1000)
        ),
        123,
        456,
        System.currentTimeMillis(),
        101112L,
        123,
        456
    );

    private final String correlationMetadata;

    @Builder.Default
    private final Exception exception = null;
  }
}
```

3. Try to build.
4. IDEs such as IntelliJ will determine the code to be correct, but Lombok will emit the following error:

```
/home/ashley/code/lombok-reproduction/src/main/java/org/example/SomeTest.java:16:3
java: incompatible types: java.lang.String cannot be converted to int
```

**Expected behavior**
The code should compile without this issue.

**Version info (please complete the following information):**

- Lombok 1.18.22
- JRE: OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)
- JDK: javac 17.0.2
- Platform (probably is not relevant, but who knows): Linux dell 5.16.13-200.fc35.x86_64 #1 SMP PREEMPT Tue Mar 8 22:50:58 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

Replacing `faker.random().nextInt(1000)` with `(int) faker.random().nextInt(1000)` fixes this issue, although this doesn't make sense, since the signature of `.nextInt` is:

```java
  public int nextInt(int n) {
    return this.random.nextInt(n);
  }
```

My guess is that it is getting confused with the first argument being passed to `TopicPartition#<init>` which is of type `java.lang.String`.

**Comment by Rawi01** [comment]
Can you try to use the [current edge version](https://projectlombok.org/download-edge)? IIRC I fixed this problem.

**Comment by ascopes** [comment]
@Rawi01 looks like that fixes this. Thanks.

Is there a timeframe for when this will be on Maven Central?

**Comment by Rawi01** [comment]
Thanks for testing. I think there will be a new release soon because some changes are required for JDK 18 (release in 4 days) and the latest eclipse version (released 2 days ago).

**Comment by rzwitserloot** [comment]
@ascopes week or so. I want to run the current edge on the 'final' JDK18 release first, which is out, as @Rawi01 said, 4 days.
