### ISSUE TITLE
STS installing software from https://projectlombok.org/p2 - fails 

### ISSUE THREAD

**Issue by javaspeak** [projectlombok/lombok#3149]
**Describe the bug**
Installing of STS plugin from https://projectlombok.org/p2 fails with error message:

    An error occurred while collecting items to be installed
    session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    No repository found containing: osgi.bundle,jnr.x86asm,1.0.2.v201505052040

**To Reproduce**
On Mac have STS with version:

    Spring Tool Suite 4 
    Version: 4.10.0.RELEASE
    Build Id: 202103111225

Then click on Help   ==> Install New Software and type url:

      https://projectlombok.org/p2 

Click next accept license etc. Then you get a popup error message:

    An error occurred while collecting items to be installed
    session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
    No repository found containing: osgi.bundle,jnr.x86asm,1.0.2.v201505052040

**Expected behavior**
I expected the plugin to install without errors

**Version info (please complete the following information):**
Spring Tool Suite 4 
Version: 4.10.0.RELEASE
Build Id: 202103111225

**Additional context**
I gave up with the eclipse plugin and downloaded the jar and installed it instead.  That worked.

**Comment by Rawi01** [comment]
Can you install any other plugin? It seems like your eclipse tries to find a repository for jnr.x86asm. The eclipse lombok plugin has no additional dependencies so I don't think that the error message is actually related to lombok.

**Comment by rzwitserloot** [comment]
Given that I'm assuming the same and closing it. I keep an eye out on any updated issue, even closed ones - just report back if somehow this truly _IS_ related to lombok after all. But, make sure you include loads of details because that's a bizarre error if it really is lombok. We don't have that dependency (or any other).
