### ISSUE TITLE
[FEATURE] Add a feature for limiting @SuperBuilder for alien ancestors

### ISSUE THREAD

**Issue by onacit** [projectlombok/lombok#3151]
**Describe the feature**
Some base types, sometimes, need to extend an alien class which don't have `@SuperBuilder`.

```java
abstract class BaseType<T extends BaseType<T>>
        extends org.springframework.hateoas.RepresentationModel<T> {
}
```

Now `@SuperBuilder` is not applicable complaining the `RepresentationModel` should also be annotated with `@SuperBuilder`.

Is it technically possible to limit the hierarch check using another annotation or an annotation element?

```java
@SuperBuilderRoot // no more check above this class
@SuperBuilder
abstract class BaseType<T extends BaseType<T>>
        extends org.springframework.hateoas.RepresentationModel<T> {
}
```

```java
@SuperBuilder(root = true) // no more check above this class
abstract class BaseType<T extends BaseType<T>>
        extends org.springframework.hateoas.RepresentationModel<T> {
}
```

**Describe the target audience**
@rspilker 

**Additional context**
N/A.

**Comment by janrieke** [comment]
I don't think that's a good idea, and it's technically nearly impossible:

# Lombok cannot access the superclass. Thus, it does not know which constructor to call. If there is no default constructor, Lombok cannot know which arguments to supply.
# Without knowledge of the superclass, Lombok also cannot generate builder setter methods. What use does a builder have if there are fields missing in it?

So from my POV I'd say no. You can also do it manually, which is better in this case in my opinion: https://stackoverflow.com/a/61763012/10026074

**Comment by rzwitserloot** [comment]
Given that it's technically almost impossible and not anywhere close to a marquee feature, I'm just going to close this.
