### ISSUE TITLE
[BUG] @Builder, childClass with privateField, and need of "toBuilder" : 4 to 5 different bugs.

### ISSUE THREAD

**Issue by sarahBuisson** [projectlombok/lombok#3152]
For some reason I need to add a builder with a "toBuilder" method to a class ("ParentClass") of an external lib ( that I can't change):

```
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class ParentClass {

    private String someField;
}

```

The issue is, all the field of the class are private. But they can be set with constructor and setter, so it should be fine, right?

Wrong. I have 5 different bug !!!

I need to create a builder for this class, in another project. The issue is, no matter what I do, I endup with a bug.

First Bug:

```
@Builder(setterPrefix = "with", toBuilder = true)
class ChildrenClass1 extends ParentClass {

 }

```

the error is : the ChildrenClass.ChildrenClassBuilder dont get any method "withSomeField".

Second Bug : 

```
class ChildrenClass2 extends ParentClass {


    @Builder(setterPrefix = "with", toBuilder = true)
     public ChildrenClass2(String someField) {
         super(someField);
     }
 }

```

the error is : java: someField has private access in com.ParentClass

3th bug:

```
class ChildrenClass3 extends ParentClass {

    @Builder(setterPrefix = "with")
    public ChildrenClass3(String someField) {
        super(someField);
    }
}

```
actually, this one work. The issue is, I need the toBuilder(). I cannot get it. because each time I add toBuilder = true somewhere, it bug

```
@Builder(setterPrefix = "with", toBuilder = true)
class ChildrenClass4 extends ParentClass {

    @Builder(setterPrefix = "with")
    public ChildrenClass4(String someField) {
        super(someField);
    }
}

````
bug : no methode withSomeField nowere

````
@Builder(setterPrefix = "with", toBuilder = true, builderClassName = "AlternateName")
public class ChildrenClass5 extends ParentClass {

    @Builder(setterPrefix = "with")
    public ChildrenClass5(String someField) {
        super(someField);
    }
}

````
bug : I can't simultaneously get withSomeField and toBuilder method.

I use lombok 1.18.20 and the intellij idea plugin bundled 213.6777.52

Nor the lombok plugin maven, nor the intellij compilation tab, nor the intellij red wave give me the same error. Nor position the error at the same place. For any of those case.

I resume all of it in this project: 
https://github.com/sarahBuisson/bug_lombok

Please fix it. any of it, even 1 of it.
(I struggle to not mention that it's urgent for me.)

**Comment by Rawi01** [comment]
`@Builder` cannot see the fields of the parent class. The constructor solution works if you add `@Builder.ObtainVia(method = "getSomeField")`. This is also mentioned in the [documentation](https://projectlombok.org/features/Builder).

**Comment by janrieke** [comment]
That's technically impossible for any annotation processor, not only lombok.
Your only way out with lombok is to convince the authors of that library to also use lombok and put an `@SuperBuilder` on their class.

I'm not aware of any tool that fits your use-case of automatically generating a builder for a class from a library during compilation.

**Comment by sarahBuisson** [comment]
If its impossible, why does it work when i dont use 'toBuilder' ?
Also, i agree lombok shouldnt be able to access the private field, BUT it should be able to use the setter instead.

**Comment by janrieke** [comment]
Well, we agree that it would be nice if Lombok could do that, but it's simply not possible at the moment.

The problem is that annotation processors only have access to the compilation unit that is currently compiled. Any other compilation unit (e.g. the superclass) can not be accessed. Thus, Lombok simply cannot see the setters from the superclass.

Your one working example does compile because you manually provided the information how to set the field in the superclass by adding a constructor that has that field as parameter. For `toBuilder` you also have to provide that mapping manually via `@ObtainVia`. That's what @Rawi01 is referring to.
