### ISSUE TITLE
The "Alt+Shfit" key doesn't work well after install lombok

### ISSUE THREAD

**Issue by er3456** [projectlombok/lombok#3162]
If I hadn't installed lombok, I could use "alt+shit+r" in eclipse to rename some variable.
But after I installed lombok, the "alt" keys seems doesn't work normally. if I click "alt+shift+r" the eclipse menu "Run" opened which means the "alt+shift+r" didn't work. 

If I git rid of the lombok from eclipse.ini file, the hot keys works normally again.

I tried some versions of lombok , but they have the same issue.
So would you confirm and improve this issue?

**Comment by er3456** [comment]
I used the eclipse 2022.3

**Comment by dstango** [comment]
Duplicate of #3142
