### ISSUE TITLE
[BUG] Propagation of @CheckForNull annotation does not work for Findbugs/Spotbugs

### ISSUE THREAD

**Issue by taa-autorola-com** [projectlombok/lombok#3163]
**Describe the bug**
@edu.umd.cs.findbugs.annotations.Nullable is propagated from fields to generated getter methods when using @Getter, however @edu.umd.cs.findbugs.annotations.CheckForNull is not propagated.

@javax.annotation.CheckForNull (jsr-305) is propagated correctly.

**To Reproduce**
```
@lombok.Getter
public class RegressionCheckForNull
{
  @edu.umd.cs.findbugs.annotations.CheckForNull
  private String findBugs_CheckForNull;

  @edu.umd.cs.findbugs.annotations.Nullable
  private String findBugs_Nullable;

  @javax.annotation.CheckForNull
  private String jsr305_CheckForNull;

  @javax.annotation.Nullable
  private String jsr305_Nullable;
}
```

This compiles to 
```
import edu.umd.cs.findbugs.annotations.CheckForNull;
import edu.umd.cs.findbugs.annotations.Nullable;

public class RegressionCheckForNull {
  @CheckForNull
  private String findBugs_CheckForNull;
  @Nullable
  private String findBugs_Nullable;
  @javax.annotation.CheckForNull
  private String jsr305_CheckForNull;
  @javax.annotation.Nullable
  private String jsr305_Nullable;

  public RegressionCheckForNull() {
  }

  // I expected to see an annotation here
  public String getFindBugs_CheckForNull() {
    return this.findBugs_CheckForNull;
  }

  @Nullable
  public String getFindBugs_Nullable() {
    return this.findBugs_Nullable;
  }

  @javax.annotation.CheckForNull
  public String getJsr305_CheckForNull() {
    return this.jsr305_CheckForNull;
  }

  @javax.annotation.Nullable
  public String getJsr305_Nullable() {
    return this.jsr305_Nullable;
  }
}

```

**Expected behavior**
I expect @edu.umd.cs.findbugs.annotations.CheckForNull to be propagated as well

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Platform: javac 11.0.7 (Windows 10)

**Additional context**
Using spotbugs annotations com.github.spotbugs:spotbugs-annotations:4.6.0

**Comment by Rawi01** [comment]
I cannot reproduce this. Lombok maintains a list of annotations that should be copied, it also contains `@CheckForNull`.
https://github.com/projectlombok/lombok/blob/e1b99751850bc47dd17e983b8f7255fd9b741aca/src/core/lombok/core/handlers/HandlerUtil.java#L147
