### ISSUE TITLE
[FEATURE] Hope an annotation like @StaticField to generate static constant of String for all fields

### ISSUE THREAD

**Issue by Bismarcharis** [projectlombok/lombok#3165]
for exsample,
@StaticField
public class Test{
    private String uniqueId;
    private User user;
    private Date createdAt;
}

to generate,
public class Test{
    private String uniqueId;
    private User user;
    private Date createdAt;

    public static String UNIQUE_ID = "unique_id";
    public static String USER = "user";
    public static String CREATED_AT = "created_at";
}

**Comment by Rawi01** [comment]
Check [`@FieldNameConstants`](https://projectlombok.org/features/experimental/FieldNameConstants)
