### ISSUE TITLE
[BUG] missing getter method when a bean contains both cphone and cPhone fields

### ISSUE THREAD

**Issue by Aibing168** [projectlombok/lombok#3167]
**Describe the bug**
for a bean contains fields cPhone and cphone, the generated class only contains get/set method for field cphone, not cPhone

**To Reproduce**
***define new class***
`@Data
@AllArgsConstructor
public class Resp2 {
        private String cphone;
        private String cPhone;
}`
***generated class***
`public class Resp2 {
        private String cphone;
        private String cPhone;

        public String getCphone() {
            return this.cphone;
        }

        public void setCphone(String cphone) {
            this.cphone = cphone;
        }

        public boolean equals(Object o) {
            if (o == this) {
                return true;
            } else if (!(o instanceof TestObjectMapper.Resp2)) {
                return false;
            } else {
                TestObjectMapper.Resp2 other = (TestObjectMapper.Resp2)o;
                if (!other.canEqual(this)) {
                    return false;
                } else {
                    Object this$cphone = this.getCphone();
                    Object other$cphone = other.getCphone();
                    if (this$cphone == null) {
                        if (other$cphone != null) {
                            return false;
                        }
                    } else if (!this$cphone.equals(other$cphone)) {
                        return false;
                    }

                    Object this$cPhone = this.getCphone();
                    Object other$cPhone = other.getCphone();
                    if (this$cPhone == null) {
                        if (other$cPhone != null) {
                            return false;
                        }
                    } else if (!this$cPhone.equals(other$cPhone)) {
                        return false;
                    }

                    return true;
                }
            }
        }

        protected boolean canEqual(Object other) {
            return other instanceof TestObjectMapper.Resp2;
        }

        public int hashCode() {
            int PRIME = true;
            int result = 1;
            Object $cphone = this.getCphone();
            int result = result * 59 + ($cphone == null ? 43 : $cphone.hashCode());
            Object $cPhone = this.getCphone();
            result = result * 59 + ($cPhone == null ? 43 : $cPhone.hashCode());
            return result;
        }

        public String toString() {
            return "TestObjectMapper.Resp2(cphone=" + this.getCphone() + ", cPhone=" + this.getCphone() + ")";
        }

        public Resp2(String cphone, String cPhone) {
            this.cphone = cphone;
            this.cPhone = cPhone;
        }
    }`

**Expected behavior**
get/set method should be able to generated for both cphone and cPhone fields

**Version info (please complete the following information):**
 - 1.8.22
 - IntelliJ

**Additional context**
no more

**Comment by LiamCX** [comment]
https://github.com/projectlombok/lombok/issues/2130

**Comment by LiamCX** [comment]
hi, developers already discussed about this in 2130

**Comment by LiamCX** [comment]
hi, developers already discussed about this in #2130

**Comment by rzwitserloot** [comment]
This is intentional.
