### ISSUE TITLE
[DOCS] Missing `clearXxx` examples in Builder Singular snippet

### ISSUE THREAD

**Issue by tlinkowski** [projectlombok/lombok#3169]
**Describe the bug**
Methods `clearOccupations`, `clearAxes`, `clearElves`, `clearMinutiae` are missing on the Builder Singular snippet webpage.

**To Reproduce**
1. Go to https://projectlombok.org/features/BuilderSingular
2. Look for methods mentioned above.

**Expected behavior**
The methods should be there (Delombok rerun required).

**Version info (please complete the following information):**
 - Lombok version: N/A
 - Platform: N/A

**Additional context**
There's also https://projectlombok.org/features/Singular-snippet.html webpage (I found it through Google, but I'm not sure if this page is still valid).

**Comment by rzwitserloot** [comment]
I never know how people find this stuff, but, fair enough - you're entirely correct.

**Comment by tlinkowski** [comment]
If it's interesting, I found it like this:

1. I had `@Singular List<Foo> foos` and wrote `toBuilder().foos(extraFoos).build()`
2. a colleague commented that I probably overwrite `foos` instead of appending
3. I explained to him this "quirk" of `@Singular` and directed him to a delomboked example

:wink:
