### ISSUE TITLE
IDEA2020.3 it does not automatically prompt @extensionMethod function

### ISSUE THREAD

**Issue by chinapsu** [projectlombok/lombok#3173]
***You're in the wrong place!***

After IDEA2020.3, can't use the @extensionMethod function of IDEA, plug-ins can't automatically prompt extension methods, is there any way?

Compilation does not generate an error, but when writing code, it does not automatically prompt for the corresponding method, but it does before IDEA2020.3.

![image](https://user-images.githubusercontent.com/6300044/163137108-e282eac7-e380-4b25-ab57-782c7f1302a7.png)

Thank you!

**Comment by Rawi01** [comment]
> **_You're in the wrong place!_**

**Comment by Rawi01** [comment]
Please read the issue template and title next time, you removed the part where this was described. This repository is only for eclipse and `javac`, the IntelliJ plugin is managed in a different [repositoy](https://youtrack.jetbrains.com/).
