### ISSUE TITLE
[BUG] Inner class not made static by @UtilityClass

### ISSUE THREAD

**Issue by TysonMN** [projectlombok/lombok#3176]
**Describe the bug**
The documentation of `@UtilityClass` says it makes all inner classes static, but that doesn't seem to be the case.

**Steps to Reproduce**
Compile this code:
```java
import lombok.experimental.UtilityClass;

@UtilityClass
public class MyOuterClass {
    public void method() {
        new MyInnerClass().method();
    }

    private class MyInnerClass {
        public void method() { }
    }
}
```

**Expected behavior**
The code compiles.

**Actual behavior**
The code does not compile.  Instead, I get this compile error:
> MyOuterClass.java:8: error: non-static variable this cannot be referenced from a static context
>        new MyInnerClass().method();
>        ^

**Workaround**
The code compiles after explicitly adding `static` to the inner class as shown in the following code:
```java
import lombok.experimental.UtilityClass;

@UtilityClass
public class MyOuterClass {
    public void method() {
        new MyInnerClass().method();
    }

    private static class MyInnerClass {
        public void method() { }
    }
}
```

**Additional context**
Here is a screenshot showing where the documentation of `@UtilityClass` says
> All methods, inner classes, and fields in the class are marked static.

<img width="791" alt="Screen Shot 2022-04-15 at 10 34 00 AM" src="https://user-images.githubusercontent.com/34664007/163591762-64e352f9-f802-42ce-ac00-601a8bca527a.png">

**Version info**
 - Lombok version: Not sure.  IntelliJ bundles Lombok and says version it is using is `bundled 213.7172.25`.

<img width="988" alt="Screen Shot 2022-04-15 at 10 52 52 AM" src="https://user-images.githubusercontent.com/34664007/163592393-3fce471a-1576-47b4-8b5d-a7a3c5fec5f3.png">

 - `javac` version: 11.0.12
 - Platform: I am using IntelliJ.  Here is the info obtained from `IntelliJ IDEA -> About IntelliJ IDEA -> Copy`:

> IntelliJ IDEA 2021.3.3 (Community Edition)
> Build #IC-213.7172.25, built on March 15, 2022
> Runtime version: 11.0.14.1+1-b1751.46 x86_64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> macOS 12.3.1
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2048M
> Cores: 16
> Registry:
>     debugger.watches.in.variables=false
> 
> Non-Bundled Plugins:
>     org.antlr.intellij.plugin (1.17)
>     idea.plugin.protoeditor (213.6461.28)
>     org.jetbrains.kotlin (213-1.6.10-release-961-IJ6777.52)
>     PythonCore (213.7172.26)
>     CheckStyle-IDEA (5.62.0)
>     org.intellij.scala (2021.3.20)
> 
> Kotlin: 213-1.6.10-release-961-IJ6777.52

**Comment by rzwitserloot** [comment]
This sounds familiar, as in, already fixed. However, its possible the lombok plugin didn't. It is a separate codebase; the issue should probably be filed on their tracker. It's [here](https://github.com/mplushnikov/lombok-intellij-plugin).

**Comment by TysonMN** [comment]
> This sounds familiar, as in, already fixed.

Ah,  yes.  This issue is a duplicate of #3097.

> However, its possible the lombok plugin didn't. It is a separate codebase; the issue should probably be filed on their tracker. It's [here](https://github.com/mplushnikov/lombok-intellij-plugin).

Thanks for the pointer.  I will follow up there.
