### ISSUE TITLE
Lombok doesn't work with OpenJDK 11 

### ISSUE THREAD

**Issue by argades** [projectlombok/lombok#3178]
**Describe the bug**
I'm creating an example microservice with Spring Boot 2.6.6, it's the first time I use lombok.
When I POST to Postman, the values of the object come back null.
On debug mode when I sent data and lombok configured
![image](https://user-images.githubusercontent.com/15037468/164035749-3498dc26-2244-4fa3-bcd2-41fd62de7fab.png)

![image](https://user-images.githubusercontent.com/15037468/164035653-fb97a5bf-191d-46b2-9c89-e89ea1ae3b41.png)

Without lombok
![image](https://user-images.githubusercontent.com/15037468/164035909-9111c232-bde6-41ef-81dc-a6aeb2c5ed03.png)
![image](https://user-images.githubusercontent.com/15037468/164035962-e45ea3a4-3074-42ec-8536-40f68b7f766c.png)

**To Reproduce**
Create a simple Spring Boot 2.6.6 project with Spring initializer, add lombok, MongoDB, Spring Web.
Follow the steps in this tutorial. https://www.youtube.com/watch?v=-ksmE3KoX9U

It is not necessary to create all the steps, just by making the controller and the entity, the problem can already be detected.

**Expected behavior**
Get the data sent from Postman or from the request of any other app.

**Version info (please complete the following information):**
 - Lombok version: 1.18.22
 - Platform Eclipse. The specific JDK11 is AdoptOpenJDK jdk-11.0.9.101-hotsppot.
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

`
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
`
Thanks

**Comment by argades** [comment]
I have update the data with capture on debug mode

**Comment by rzwitserloot** [comment]
@argades Cannot reproduce. Also, what you claim (that the getters do exist, i.e. no compiler errors, but return `null` / that the setters do exist, but no nothing), is not possible - in other words, an extraordinarily claim, lacking extraordinary evidence.

It's something else.

**Comment by Rawi01** [comment]
I guess it is some kind of configuration problem and it will fail to compile if you try to use one of the getters/setters. You can also confirm this by opening the compiled `.class` file in IntelliJ.

**Comment by argades** [comment]
I have compiled the app and the .class have been regenerated into Eclipse IDE and now it works.
Sorry for the mistake

**Comment by argades** [comment]
I have compiled the app and the .class have been regenerated and now it works. It may be an Eclipse problem.
Sorry for the mistake
