### ISSUE TITLE
[BUG] ClassNotFoundException: lombok.launch.AgentBootstrap after createMavenECJBootstrap

### ISSUE THREAD

**Issue by famod** [projectlombok/lombok#3179]
**Describe the bug**
When following the instructions on https://projectlombok.org/setup/ecj, I'm getting this error on running `mvn`:
```
Exception in thread "main" java.lang.ClassNotFoundException: lombok.launch.AgentBootstrap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:435)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted
```

**To Reproduce**
Run `java -jar lombok.jar createMavenECJBootstrap -o /path/to/project/root` as described on https://projectlombok.org/setup/ecj.
You will end up with `-javaagent:.mvn/lombok-bootstrap.jar` in `.mvn/jvm.config` which contains in `META-INF/MANIFEST.MF`:
```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.10.12
Created-By: 17.0.1+1 (Homebrew)
Premain-Class: lombok.launch.AgentBootstrap
Can-Redefine-Classes: true
```

**Expected behavior**
No such error.

**Version info (please complete the following information):**
 - Lombok version 1.18.24

**Additional context**
Patching the MANIFEST.MF to define this instead:
```
Premain-Class: lombok.launch.MavenEcjBootstrapAgent
```
"fixes" the issue.

`lombok.launch.AgentBootstrap` was added with https://github.com/projectlombok/lombok/commit/110434ff60a14d2dfe8014459ffbea3ce7d6388b and was removed again with https://github.com/projectlombok/lombok/commit/c8607ba782f90ef847488f0fc5bdc365c1e83317, but it's still defined here:
https://github.com/jopatai/lombok/blob/master/buildScripts/compile.ant.xml#L85

PS: After patching the jar, `mvn` is running again but compilation fails because it seems to not execute `hibernate-jpamodelgen` annotation processor. Not sure this is an ECJ or a Lombok integration issue...

**Comment by rzwitserloot** [comment]
I renamed the type and failed to rename in the code that generates the manifest. My mistake.

**Comment by famod** [comment]
@rzwitserloot no worries! Is my workaround ok or do I have to use another class?

**Comment by rzwitserloot** [comment]
Your workaround sounds correct :)
