### ISSUE TITLE
[DOCUMENTATION] Add BigDecimal explanation to EqAndHashCode feature page

### ISSUE THREAD

**Issue by rzwitserloot** [projectlombok/lombok#3182]
BigDecimal has a wonky definition of equality, for example `1E2` is not equal to `100` in the sense that `bigDecimalA.equals(bigDecimalB)` would return `false` because they have different scales. Whilst we defer to BD's authors - that is evidently how they intend for equality to work - it's confusing in any case (not our fault), and often folks want to define equality as: Does it represent the same value?

There IS a way to accomplish this:

```java
@EqualsAndHashCode.Include
private BigDecimal nameOfBigDecimalField() {
  return nameOfBigDecimalField..stripTrailingZeros();
}
```

This should be named on [the feature page of `@EqualsAndHashCode`](https://projectlombok.org/features/EqualsAndHashCode); probably in the smallprint, and including that snippet or at least a link to it.

See issue #1260 where @wacker confirmed that this 'trick' works.

**Comment by droduit** [comment]
It would be even better to provide a null-safe solution, as below :
```
@EqualsAndHashCode.Exclude
private BigDecimal bigDecimalField;
  
@EqualsAndHashCode.Include
private BigDecimal bigDecimalField() {
  return bigDecimalField != null ? bigDecimalField.stripTrailingZeros() : null;
}
```

**Comment by rzwitserloot** [comment]
@droduit Revisiting this, cripes it's nasty. __That code is broken__. It took me a year to see it, so, you know. By no means intended as an insult.

In the infinite wisdom of the designers of the BigDecimal API:

```
BigDecimal a = new BigDecimal(BigInteger.ONE, -2); // 100.
BigDecimal b = new BigDecimal("100"); // also 100.
System.out.println(a.equals(b)); // false
System.out.println(a.compareTo(b)); // 0
System.out.println(a.hashCode() == b.hashCode()); // FALSE!!!!
```

That last line means your suggestion would be broken. After all, the rules state that if 2 things are equal __they must have the same hashcode__. Trying to come up with a hashcode implementation that fulfills the rules and is efficient is, as far as I can tell, incredibly complicated.

The upshot is, if you want any 2 BDs to be equal if `compareTo()` says they are __you cannot do that, period__. Well, not unless you spend quite a while to come up with a fast hashCode impl for this. You can always just `return 1;` but this risks having highly surprising performance characteristics, such as `O(n)` performance hashsets.

The upside for me is, the doc update is now much simpler. Just explain that BD's equality is wonky, caution against trying to fix that, and that's all I have to do.

**Comment by rzwitserloot** [comment]
doc update is now live on [https://projectlombok.org/features/EqualsAndHashCode](https://projectlombok.org/features/EqualsAndHashCode)
