### ISSUE TITLE
Cannot install in Eclipse

### ISSUE THREAD

**Issue by costin3141** [projectlombok/lombok#3183]
Adding https://projectlombok.org/p2 via install new software fails with the message:

Unable to read repository at https://projectlombok.org/p2/content.xml.
Unable to read repository at https://projectlombok.org/p2/content.xml.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This happens with and without our vpn. Other update sites work fine.

**Comment by rzwitserloot** [comment]
Cannot reproduce. Likely cause: You are using a hopelessly out of date OS or, more likely, a JDK7 or JDK6 to run eclipse on, and it does not include the LetsEncrypt root cert. You'll have to fix your obsolete (and most likely security-wise rather vulnerable) OS and/or JDK setup. There isn't much we can do short of shelling out a tidy sum for a less secure certificate, and we're not going to do that.

**Comment by costin3141** [comment]
It is my company laptop running windows 10, JDK 17. So no, not an ourdated OS or outdate JDK AT ALL.

**Comment by rzwitserloot** [comment]
If you'd like to ship me your laptop with international post I'll have a look at it. If that's not possible, what do you propose we do to fix this? I cannot reproduce this on any machine I have here. That the URLs dont 'resolve' is normal, eclipse adds a bunch of stuff. That doesn't mean anything is broken.

There's always just downloading lombok.jar from our site (or letting your build system/dependency manager do it), and double clicking it. You don't have to use the update site.

As an example, `https://projectlombok.org/p2/content.jar` should download with no security warnings or http errors.

**Comment by costin3141** [comment]
Man, what's wrong with you? Why so bitchy?

I reported an issue. You tell me what i can do to help you narrowing it down. If you don't know what to do then so be it. But there is no reasson to talk so naughty to me.

Sending a company laptop to you great idea. If you have a bad day let someone else handle bug reports.
If i would handle stuff like you in my job i would have that job anymore. Feel lucky.

**Comment by Kurti123** [comment]
I'm experiencing the same problem, Eclipse 2024-09, JDK 21, Windows 10...

**Comment by Kunz-sked** [comment]
I get the same problem: Eclipse 2024-12 RAP, JDK 21, Windows 2022 Server
