### ISSUE TITLE
[DOCUMENTATION] missing download links for 1.16.20 1.16.22

### ISSUE THREAD

**Issue by ayeseeem** [projectlombok/lombok#3191]
The page for downloading [older versions](https://projectlombok.org/all-versions) seems to be missing links for versions 1.16.20 and 1.16.22. However, it does appear that those versions are available, at locations following the same format as for 1.16.18.

**Comment by rzwitserloot** [comment]
No idea what happened there. I did change the release process around that time. Fixed, at any rate, thank you for noticing, @ayeseeem !
