### ISSUE TITLE
Seeking source code tutorial

### ISSUE THREAD

**Issue by IDEA-Fang** [projectlombok/lombok#3195]
How can I start the project test locally, is there any tutorial or documentation, I want to add some new functions, stuck in the first compilation stage, like testing DataOnLocalClass1#main

**Comment by rzwitserloot** [comment]
There is no documentation for this beyond the ant targets and none is planned, though we'd accept PRs. Can I surmise from your username that you use IDEA? There is no intent to support lombok development in IDEA from us directly, as the ant target tells you. PRs welcome.
