### ISSUE TITLE
[BUG] Lombok fails silently on static import of a getter

### ISSUE THREAD

**Issue by jmakovecki** [projectlombok/lombok#3200]
**Describe the bug**
Lombok silently fails to generate any code when a static import of a getter generated via `@Getter` is present anywhere in the code. This results in a (potentially huge) number of unrelated errors about missing methods, constructors, etc., while giving no indication of why they were not generated.

**To Reproduce**
Save the following minimal example as `test/MinimalExample.java` and run it with: `javac -cp lombok.jar MinimalExample.java`:
```java
package test;

import lombok.Getter;

import static test.MinimalExample.Hello.getHello;

public class MinimalExample {
  public static class Hello {
    @Getter
    private static String hello = "Hello";
  }

  public static void main(String[] args) {
    System.out.println(getHello());
  }
}
```
What we get is:
```
MinimalExample.java:5: error: cannot find symbol
import static test.MinimalExample.Hello.getHello;
^
  symbol:   static getHello
  location: class Hello
MinimalExample.java:18: error: cannot find symbol
    System.out.println(getHello());
                       ^
  symbol:   method getHello()
  location: class MinimalExample
2 errors
```

**Expected behavior**
The example should compile with no errors. At the very least, Lombok should log an error.

Workarounds include:
- removing `import static test.MinimalExample.Hello.getHello;` and calling the method via `Hello.getHello()`
- removing the `@Getter` annotation and writing a getter by hand (`public static String getHello() { return hello; }`)

**Version info (please complete the following information):**
 - Lombok version: 1.18.24
 - Platform: javac 11.0.15 (openjdk 11.0.15 2022-04-19)

**Additional context**
Initially discovered when running through Gradle in Intellij IDEA.

**Comment by rzwitserloot** [comment]
This is a known bug in javac in regards to annotation processors and non-star static imports. We've looked into it before and there's nothing we can do - lombok isn't even executed. The only 'fix' is to rewrite the entire core launch pipeline of lombok into being a compiler plugin instead. That will probably work but we aren't even sure.

This is one of those 'closed as wontfix with regrets' tickets: Yeah, this is a bug, absolutely. It'sj ust that we cannot fix it - the party that can is wrong but says this isn't a bug, last time I checked.

**Comment by jmakovecki** [comment]
I see. That's an unfortunate situation. It might make sense to put up some sort of a "known issues" page for this and potential similar issues, as it is quite hard to track down. Either way, thank you for your explanation, it's good to know what to look out for.
