### ISSUE TITLE
[FEATURE] Dynamically load lombok into eclipse.jdt.ls

### ISSUE THREAD

**Issue by XiaoYuhao** [projectlombok/lombok#3205]
I am interested in lombok support for vscode. The previous plugin just only added "-javaagent:/path/lombok.jar" to "vmargs" in user setting which is not elegant. This plugin specifies a certain version of lombok, which may be different from the version used by the project.

Now I am developing a new lombok support plugin for vscode. It can get the lombok version from the classpaths and then add "-javaagent:/path/lombok.jar" to eclipse.jdt.ls startup parameters. However, it need to start eclipse.jdt.ls to get classpaths firstly. And vscode needs to be reload to restart eclipse.jdt.ls for lombok support since lombok start as agent in eclipse.jdt.ls which uses the _premain_ to load the agent using -javaagent option.

To avoid restarting eclipse.jdt.ls, I tried to make use of the _agentmain_ to load the lombok agent to eclipse.jdt.ls using the Java Attach API. However, the lombok agent threw an UnsupportedOperationException "class is already loaded and cannot be modified".

Questions:

1. Whether lombok can work properly by using the _agentmain_ to load the lombok agent to eclipse.jdt.ls without restarting eclipse.jdt.ls?
2. Are there other ways to dynamically load lombok into eclipse.jdt.ls without restarting eclipse.jdt.ls?

Thanks for your consideration.

**Comment by rzwitserloot** [comment]
`agentment`? Never heard of it. Is that a typo?

**Comment by XiaoYuhao** [comment]
I'm sorry, it should be `agentmain`.

**Comment by XiaoYuhao** [comment]
> `agentment`? Never heard of it. Is that a typo?


> `agentment`? Never heard of it. Is that a typo?

I'm sorry, it should be `agentmain`.

**Comment by XiaoYuhao** [comment]
@rzwitserloot any thoughts?

**Comment by rzwitserloot** [comment]
I'm sure both are possible, but these questions are not appropriate here - they sound like questions you should be asking team `eclipse.jdt.ls`, not us.

**Comment by XiaoYuhao** [comment]
@rzwitserloot Thank you for providing comments. I'm looking for new ways to dynamically load lombok into Eclipse JDT platform. After some investigation, I have some findings but also some questions I want to get clarified. Appreciate a lot If you could provide some insights.



1. AFAIK, most third party Java tools contribute to JDT capabilities through OSGI bundle. I'm wondering the reason behind why lombok team choose to inject lombok.jar as a Java agent instead of OSGI bundle?



2. In addition, Eclipse JDT provides APT to support annotation processor, do you think is it possible to load lombok.jar as annotation processor of JDT-APT?



Thank you for the great lombok project.

**Comment by Rawi01** [comment]
Lombok hooks into the compiler to modify the AST and also changes some internal methods to hide the AST modifications. Without that eclipse would try to modify the source code of the generated nodes which is impossible because it is not there. To add these hooks lombok changes some of the classes using a javaagent, a normal plugin cannot do that.

I think it is possible to run lombok as anotation processor but this will still require most of the patches. Splitting it up will lead to new problems where the annotation processor and agent use different versions.
