### ISSUE TITLE
[FEATURE] (Super)Builder chaining

### ISSUE THREAD

**Issue by Zegveld** [projectlombok/lombok#3206]
Currently it is required to manually define that you want to use another builder for creating a child object that is also annotated with a builder. It would be easier for usage to have this done inside the builder itself.
### classes
```java
@SuperBuilder
class A {
    @Getter
    @Setter
    B b;
}
@SuperBuilder
class B{
    @Getter
    @Setter
    String field;
}
```

### current usage
```java
A.builder()
  .b(B.builder()
      .field("Hello world")
      .build())
  .build();
```

### suggested usage
```java
A.builder()
  .b()
      .field("Hello world")
      .end()
  .build();
```

### sidenote
Another advantage would be that you can use suppliers to separate the knowledge of how the builder is retrieved while still being able to separate the building of A from B. In production you could use `a::b` while in testing you could use `b::builder`.

**Comment by rzwitserloot** [comment]
It's a somewhat interesting idea, but I'm closing this. Way too many smelly things, not nearly enough upside. I can think of rather a lot of reasons this is not a good idea for lombok. A select few highlights (this is by no means complete):

* Why are you bringing `@SuperBuilder` into this? Don't you just mean `@Builder`? Why do you have a builder on a class that also has mutable fields? None of this feels very well thought through. 
* Lombok doesn't know. Given the file `A.java`, and a field `B b`, how does lombok know that B, itself, has a `@Builder` annotation on it? [Lombok cannot just go and check](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution), so you'd have to specify it. Even if lombok could know, I'm not sure it's a good idea to assume folks would _always_ want this functionality. Even if you think it's a fair assumption to make, changing that now would be backwards incompatible.
* Thus you can't do this without an annotation or something similar on the field/param. That's potentially acceptable but is complicating matters: How would users of lombok know this feature existed?
* We'd need to generate a duplicate, which really should be in `B`, _or_ we generate an entire B-builder inside A. Either way you've now tightly entangled 2 classes which is bad.

That's just a small selection.

**Comment by Zegveld** [comment]
To address these points:
> Why are you bringing `@SuperBuilder` into this? Don't you just mean `@Builder`? 

I mean both. In our case we have an hierarchy structure of classes because of which we are using the `@SuperBuilder` annotation. Previously we had another `Builder` framework generated through xjc, but since we're moving from jaxb-generated model to a manually written model we still want to keep much of the usage the same. One of the things in there was the builder chaining suggested here. For the example I've changed it now to `@Builder`, but I would expect `@SuperBuilder` to have the same functionality.

> Why do you have a builder on a class that also has mutable fields?

Because in our data model, we read from xml. Possible we change a few fields and write back to xml. We also generate the information, that is mostly done through builders and as immutable as possible. But for this `Issue` that is not related, so I've edited it out of the original post.

> Lombok doesn't know. Given the file A.java, and a field B b, how does lombok know that B, itself, has a `@Builder` annotation on it? [Lombok cannot just go and check](https://github.com/projectlombok/lombok/wiki/LOMBOK-CONCEPT:-Resolution), so you'd have to specify it. Even if lombok could know, I'm not sure it's a good idea to assume folks would always want this functionality. Even if you think it's a fair assumption to make, changing that now would be backwards incompatible.

I'm a little bit familiar with APT processing, but wasn't familiar with the fact that because lombok chains in way earlier than other processors they have access to less information than other processors. With other processors I can request information about other `Type`'s and check if an annotation is present on that type, if for lombok this is not possible then indeed it would make this impossible. If this is indeed the case for lombok than it is indeed a valid reason to close this issue. 
However, I assume that the `@SuperBuilder` knows if the parent also has the `@SuperBuilder` annotation. Couldn't the same method be used to determine whether or not a class is annotated with an `@Builder` or `@SuperBuilder` annotation? 

> Thus you can't do this without an annotation or something similar on the field/param. That's potentially acceptable but is complicating matters: How would users of lombok know this feature existed?

This is basically a continuation of the previous point. The field/param shouldn't get an additional annotation. If that is required to make this work then it wouldn't be acceptable (imho).

> We'd need to generate a duplicate, which really should be in B, or we generate an entire B-builder inside A. Either way you've now tightly entangled 2 classes which is bad.

Again a continuation of a previous point. You do not want to generate a duplicate/entire B-builder inside A. You want to reference the other builder that will be/has been created during the processing of that class. The entanglement doesn't change at all, `A` knows that `B` exists. `A.Builder` knows that `B.Builder` exists. The dependency between the classes and the builders are the same.

**Comment by Zegveld** [comment]
Just took a closer look at how this is done in `@SuperBuilder` and it seems to be a documented requirement that all superclasses also have the `@SuperBuilder` annotation. Removing it at one superclass will cause no lombok specific error to be thrown, but only default compiler errors.

After seeing this the builder chaining idea is currently not possible within lombok itself.
