### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project XYZ: Unable to parse configuration of mojo org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile for parameter path: Cannot find 'path' in class org.apache.maven.plugin.compiler.DependencyCoordinate -> [Help 1]

### ISSUE THREAD

**Issue by AbhijitJadhav4u** [projectlombok/lombok#3220]
maven is complaining  after adding micrometer entries.

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project XYZ: Unable to parse configuration of mojo org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile for parameter path: Cannot find 'path' in class org.apache.maven.plugin.compiler.DependencyCoordinate -> [Help 1]

Added following entries in pom
<annotationProcessorPath>
              <path>
                <groupId>io.micronaut.micrometer</groupId>
                <artifactId>micronaut-micrometer-annotation</artifactId>
              </path>
            </annotationProcessorPath>

and 
<dependency>
  <groupId>io.micronaut.micrometer</groupId>
  <artifactId>micronaut-micrometer-core</artifactId>
  <version>${micronaut.version}</version>
</dependency>

<dependency>
  <groupId>io.micronaut.micrometer</groupId>
  <artifactId>micronaut-micrometer-registry-statsd</artifactId>
  <version>${micronaut.version}</version>
</dependency>

<dependency>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-management</artifactId>
  <version>${micronaut.version}</version>
</dependency>

**Comment by janrieke** [comment]
Where is the connection to lombok?
