### ISSUE TITLE
[BUG] generate getter/setter method when field the first char is lowercase and the second char is uppercase

### ISSUE THREAD

**Issue by putekid** [projectlombok/lombok#3222]
**Describe the bug**
There is a object in my project which has a field names uName, lombok generate getter/setter is getUName() and setUName(). When I use java.beans.Introspecotr#getBeanInfo(Class) to get BeanInfo object.Then use BeanInfo to getPropertyDescriptors. The field name that I got is UName. But the real field name is uName. I read the resource code of JDK, found JDK not process field name when first char and second char are uppercase. Then I use Class#getDeclaredField(String) make an exception of NoSuchFieldException. When I use IDEA to generate getter/setter method, it generated names are getuName/setuName. So I think lombok should deal with this special situation. 
I know  this naming is not standard, but it's the history code, I have dealt with this situation alone.
Sorry for my poor english.

**Version info (please complete the following information):**
 - Lombok version 1.18.2
 - Lombok plugin version 203.7717.56
 - Platform jdk8

**Comment by weirhp** [comment]
please add file "lombok.config" in code folder
lombok.config content:

`lombok.accessors.capitalization=beanspec`

If the above operation does not work，Please update lombok to the latest version

**Comment by Rawi01** [comment]
Also mentioned on the website (https://projectlombok.org/features/GetterSetter#supported-configuration-keys)
