### ISSUE TITLE
[BUG] the annotation that is @Data does not take effect，when the type is boolean

### ISSUE THREAD

**Issue by lush-99** [projectlombok/lombok#3226]
this is my Class
`import lombok.Data;

@Data
public class Test {
    private boolean flag;
}`

when i use this flag, it have a error
![image](https://user-images.githubusercontent.com/77112588/177676391-a0c72bd7-c4ca-4086-a74e-05a36cb6feb8.png)

**Comment by mymde** [comment]
test.isFlag()

**Comment by lush-99** [comment]
I want to know why it is designed this way

**Comment by lush-99** [comment]
get = test.isFlag();

set = test.isFlag(param)；

i use true？

**Comment by lush-99** [comment]
am i using the right one

**Comment by janrieke** [comment]
It's the JavaBeans specification.

**Comment by dstango** [comment]
get = test.isFlag();

set = test.setFlag(param)；

**Comment by lush-99** [comment]
ok，i see,  thanks
