### ISSUE TITLE
[BUG] Compiler error when importing static method of a class that uses @UtilityClass

### ISSUE THREAD

**Issue by mattnicee7** [projectlombok/lombok#3229]
**Describe the bug**
When I try to compile this code below I get a compiler error
Console:
![image](https://user-images.githubusercontent.com/81203753/178133261-3c026915-51f7-4fda-8090-9886d513775f.png)

**To Reproduce**

Create a class and put @UtilityClass annotation in it, make any method and in your main program import the function statically (import static), and you will see a compiler error.

Code Example:

The class that uses @UtilityClass:

```java
package com.github.mattnicee7;

import lombok.experimental.UtilityClass;

@UtilityClass
public class LombokUtilityClass {

    public <T> T foo(T t) {
        return t;
    }

}
```

The main application:

```java
package com.github.mattnicee7;

import static com.github.mattnicee7.LombokUtilityClass.foo;

public class LombokTests {

    public static void main(String[] args) {
        foo("Anything");
    }

}
```

The error:

![image](https://user-images.githubusercontent.com/81203753/178133342-f0413ce0-795a-468d-9ea8-0c0542cfcdfe.png)
![image](https://user-images.githubusercontent.com/81203753/178133347-dac39157-a752-4340-b44d-a4a60e05f1d6.png)

**Expected behavior**
I wanted to import the method statically without errors.

**Version info (please complete the following information):**
 - Lombok 1.18.24
 - Java 11 Amazon Coretto version 11.0.14
 - Intellij IDEA 2021.3.2
 - Gradle 7.1
 - Gradle shadowJar 7.1.2

**Additional context**
N/A

**Comment by janrieke** [comment]
That's a know limitation in `javac` that cannot be worked around by lombok. It's also mentioned in the [documentation for `@UtilityClass`](https://projectlombok.org/features/experimental/UtilityClass).

**Comment by mattnicee7** [comment]
Thank you for your help. I achieved!

Main application:

```java
package com.github.mattnicee7;

import static com.github.mattnicee7.LombokUtilityClass.*;

public class LombokTests {

    public static void main(String[] args) {
        foo("Anything");
    }

}
```

Console:
![image](https://user-images.githubusercontent.com/81203753/178165696-0cf9f664-dafd-4d92-8722-1e49790d70b9.png)

**Comment by mattnicee7** [comment]
Hi! Has this limitation been fixed by java? A commit has been attached to this issue.
