### ISSUE TITLE
[BUG]  Cannot have a field with name build in @SuperBuilder 

### ISSUE THREAD

**Issue by taoxinyi** [projectlombok/lombok#3230]
**Describe the bug**
The class annotated with `@SuperBuilder` cannot have a field with exact name `build`. The Intellij IDE shows no error in the following code.

**To Reproduce**
```
@SuperBuilder
public class Obj {
    private final String build;

    public static void main(String[] args) {
        Obj.builder().build("abc").build();
    }
}
```
Error:
```
java: method build in class Obj.ObjBuilder<C,B> cannot be applied to given types;
  required: no arguments
  found: java.lang.String
  reason: actual and formal argument lists differ in length
```
**Expected behavior**
The object can be successfully built with field `build` == `"abc"`

**Version info (please complete the following information):**
 - Lombok version: 1.18.20
 - javac 11.0.4

**Comment by janrieke** [comment]
Can confirm. Works with `@Builder`, but not with `@SuperBuilder`. Looking into it now.

**Comment by janrieke** [comment]
Found and fixed the problem. However, this changes the order of the generated methods, which causes several tests to fail. I have to fix all of them first.
