### ISSUE TITLE
Finding field references not available when using @Builder

### ISSUE THREAD

**Issue by jakobklein** [projectlombok/lombok#3231]
After adding ```@Builder``` or ```@SuperBuilder``` to a class I cannot use >References>Workspace ( Ctrl-Shift-G ) on fields anymore in SpringTools/Eclipse. Instead I get the message: "The operation is unavailable on the current selection. Please select a valid Java element name."

Repro:

```
import lombok.Builder;
@Builder
public class Test {
	String test;
}
```

Ctrl-Shift-G on the field ```test``` works as soon as you remove ```@Builder```.

Win 11 / SpringToolsEclipse 4.15.1.RELEASE / OpenJDK Coretto 17.0.2 / Lombok 1.18.24

**Comment by Rawi01** [comment]
This was fixed by https://github.com/projectlombok/lombok/pull/3198
