### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by missyou1** [projectlombok/lombok#3234]
![7a30d72a2265546ddb9ab99131992d4](https://user-images.githubusercontent.com/30522042/179691389-719a02d5-3246-4a3c-b52f-c3ffc573e6cc.jpg)
![cc0eab39e9dbb886833d199cd4a9d9f](https://user-images.githubusercontent.com/30522042/179691472-3dd1cd6f-b9f0-490b-be44-baf711c0e436.jpg)

hey,Take a look at these two pieces of code，this getResult()  is it true getResult()? Can you only authenticate the name? int == String ???

**Comment by missyou1** [comment]
The types of program variables are inconsistent. How could this be possible it be "result" of  the get()？

**Comment by Rawi01** [comment]
Can you please try to describe your problem again in different words and why you think this is a lombok bug?

**Comment by missyou1** [comment]
This java class 

> 您能否尝试用不同的词语再次描述您的问题以及为什么您认为这是一个龙目岛错误？

In this Java class, the type of the element "result" is "int", and the output value of a new object is turned into "string", which is obviously wrong. This problem exists not only in Lombok, but also in spring

**Comment by missyou1** [comment]
> Can you please try to describe your problem again in different words and why you think this is a lombok bug?

In this Java class, the type of the element "result" is "int", and the output value of a new object is turned into "string", which is obviously wrong. This problem exists not only in Lombok, but also in spring

**Comment by missyou1** [comment]
> Can you please try to describe your problem again in different words and why you think this is a lombok bug?

This is obviously caused by the toString () method, in which the getResult () method is called. I think we should directly take the value of "result". Whether result=2 or the type of result becomes string, it is against the common sense of Java, which is unacceptable.

**Comment by Rawi01** [comment]
You can configure lombok to not use getters: `@ToString(doNotUseGetters = true)` or `lombok.toString.doNotUseGetters = true` in your `lombok.config` if you want to change this beaviour in more than one class.

**Comment by missyou1** [comment]
It can be solved, but I don't quite understand why the default toString () method calls the getResult () method instead of directly calling the value of "result"?

> You can configure lombok to not use getters: `@ToString(doNotUseGetters = true)` or `lombok.toString.doNotUseGetters = true` in your `lombok.config` if you want to change this beaviour in more than one class.

**Comment by rspilker** [comment]
In some cases, especially when the class is not final, or the field is lazy, calling the getter is the preferred way. And it is very strange to have a getter and a field that are inconsistent.

It does not matter why it is how it is now, we're not going to change it and break backwards compatibility.

You can simply modify the behavior in all your coffee by adding the suggested line to your `lombok.config` file.
