### ISSUE TITLE
[FEATURE] Introduce way to define exception type to be thrown for @NonNull marked fields/params

### ISSUE THREAD

**Issue by typekpb** [projectlombok/lombok#3236]
**Describe the feature**

Introduce property on `@NonNull` annotation, that would define exeption to be thrown (having `NullPointerException` as a default).

Current implementation:
```
@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.LOCAL_VARIABLE, ElementType.TYPE_USE})
@Retention(RetentionPolicy.CLASS)
@Documented
public @interface NonNull {
}
```

proposed one:

```
@Target({ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER, ElementType.LOCAL_VARIABLE, ElementType.TYPE_USE})
@Retention(RetentionPolicy.CLASS)
@Documented
public @interface NonNull {

    Class<? extends RuntimeException> value() default NullPointerException.class

    Class<? extends RuntimeException> exception() default NullPointerException.class;
}
```

**Additional context**
Motivation: for the existing implementations, where lombok is introduced, other than `NullPointerException` might be required to be thrown in case of null vals passed

**Comment by janrieke** [comment]
The only other reasonable exception in this case I can think of is `IllegalArgumentException`. You can already do that by configuring `lombok.nonNull.exceptionType = IllegalArgumentException`.

Allowing any arbitrary exception seems a bit over the top to me. Furthermore, lombok cannot know which constructor to use for those exceptions.
