### ISSUE TITLE
The GET and SET methods automatically produced by @data do not match the BeanMap parsing rules

### ISSUE THREAD

**Issue by xiaoyonghaoe** [projectlombok/lombok#3237]
**Describe the bug**
When the attribute name is eCat, aCat, or bCat,The parsed get method is <getECat、getACat、getBCat> BeanMap wants to be <geteCat、getaCat、getbCat>

**Version info (please complete the following information):**
 - Lombok version 1.18.8
 - Platform java 1.8

**Comment by janrieke** [comment]
Use Lombok 1.18.24 and the configuration option `lombok.accessors.capitalization = beanspec`.
