### ISSUE TITLE
[FEATURE] Support for secure logging

### ISSUE THREAD

**Issue by kalpakrg** [projectlombok/lombok#3238]
### Background
I was trying to build a solution for creating a safe `toString` implementation which allows masking values of some of the fields that maybe sensitive to being printed / logged. I have actually managed to write the code which converts the given Java object to JSON with sensitive fields being masked. The sensitive fields are marked with a special annotation. 

I work with companies in the payment industry and they have a mandate (PCIDSS) which requires them to ensure any sensitive data like card information should not be logged in the log files. Having this feature protects (for the most part) from developers logging the sensitive data accidentally. I am sure this will apply to a lot of other type of applications like say something which handles personal information like phone numbers or medical information.

I was hoping to mimic Lombok and generate the `toString` dynamically which is when I looked at Lombok code and realized it was not worth the effort to write this code all over again. While going through the code I figured there was a service discovery mechanism for `lombok.javac.JavacAnnotationHandler` class and I was under impression that I could write an extension for Lombok. Later I realized  that this class is no longer packaged in the actual Lombok jar anymore. It seems the only way to do this is to fork the project.

### Feature Description
The overall idea is to create an implementation of `toString` that will protect from accidentally logging the sensitive data in the log. Take following code example:
```java
log.info("Login request: {}", loginRequest);
``` 
Considering the `LoginRequest` class in this case contains fields `username` and `password`, both the fields will be logged in plain text in the log. like below:
```
Login request: LoginRequst(username=johndoe@domain.com,password=secret123)
```
What I would like it to print instead is:
```
Login request: LoginRequst(username=johndoe@domain.com,password=xxxxx)
```
It is possible to simply omit the `password` field from being logged using `exclude` in the `ToString` annotation but there could be some special cases where we may want to mask the value using some different logic instead of omitting altogether. Take an example of mobile number. I may want the part of mobile number to be masked instead of the entire mobile number being omitted from the output like `XXXXXX4321` 

As it stands, I have managed to define my own annotation `LogSensitive` which has following attributes:
- **value** - Hardcoded value that should be returned as masked value for the given field. There could be default like `XXXX`
- **formatter** - Class that will be used as a formatter if we want to mask the value using some special logic.
- **secureNullValues** - This is trivial but it can help control if null values should be shown as null or even that needs to be protected by printing it as masked value. 

An example class can look like:
```java
@Data
public class PaymentRequest {
    private BigDecimal amount;
    private String oderId;
    private String currency;
    
    @LogSensitive(formatter = CardNumberFormatter.class)
    private String cardNumber;

    @LogSensitive(value = "XX")
    private String expiryMonth;

    @LogSensitive(value = "XX")
    private String expiryYear;

    @LogSensitive(value = "XXX")
    private String cvv;

    @LogSensitive(value = "XXXXXX XXXXXX")
    private String cardHolderName;
}
```
If we create an object and log it using code:
```java
PaymentRequest request = new PaymentRequest();
request.setAmount(100);
request.setCurrency("USD");
request.setOrderId("ORD00001");
request.setCardNumber("4321123400001001");
request.setExpiryMonth("12");
request.setExpiryYear("24");
request.setCvv("123");
request.setCardHolderName("John Doe");

log.info("Payment request: {}", reqeust);
```
The object's `toString` converts it into a masked output like:
```
PaymentRequest(amount=100, currency=USD, orderId=ORD00001, cardNumber=XXXXXXXXXXXX1001, expiryMonth=XX, expiryYear=XX, cvv=XXX, cardHolderName=XXXXXX XXXXXX)
```
### Challenges
**JSON Output**
I would really love for the `toString` to return a JSON as it makes it much easier to format the output and share with others for any debugging. Also JSON is universally understood, it make it easy to communicate with others. The primary challenge here is that we will need a JSON library for this. My current implementation uses Jackson. I understand that adding a Jackson dependency in Lombok will be a complete no no. This is where it would have helped if the service discovery mechanism was able to find my handler class dynamically and use it. Other alternative I can think of is that the entire logic of creating masked JSON can be packaged in another library and in case the library cannot be found on the classpath during code injection time, a warning can be printed and the `toString` generation would fallback to it's default behavior. If the library is found the `toString` code would simply invoke a static method providing it the bean object and the method would return the safe JSON (My current implementation is simply a static method which takes an object and converts it to a JSON masking the sensitive fields) 

**More attributes to be added to `toString` annotation**
Sometimes you may want the JSON to be pretty printed instead of the default. To control this, we could have another attribute at the level of `toString` annotation say `pretty=true` which controls the pretty printing of JSON. Currently I have defined a class level annotation named `SecureLog` which contains this. To avoid confusion I am proposing this could be added to `toString` itself.

We may also have to give an option to users to choose between default `toString` output or the JSON output. We may need to add another attribute say `format=JSON` to control if the output should be JSON or it should provide Lombok default output.

I use Lombok for all my projects. It is really awesome. My appreciation for how cool it is has increased a million times after understanding how it actually does what it does. I think this feature could help a lot of people. Would really help if you guys consider this. Let me know the alternatives in case this cannot be part of Lombok and instead needs to be developed as an extension.

**Comment by kalpakrg** [comment]
Added code syntax highligthing

**Comment by dstango** [comment]
Check out this: https://github.com/projectlombok/lombok/pull/2807#issuecomment-820700812

**Comment by kalpakrg** [comment]
Understood. @dstango thanks for pointing to the correct content to understand the underlying issue. For now, I will develop this as a separate library as it requires the annotations and runtime.

**Comment by dstango** [comment]
> Understood. @dstango thanks for pointing to the correct content to understand the underlying issue. For now, I will develop this as a separate library as it requires the annotations and runtime.

One idea: you might implement a special String/CharSequence-type for your sensitive information, that has a toString() that returns "XXXX" or something similar.

Your class might then look like this:
```java
@Data
public class PaymentRequest {
    private BigDecimal amount;
    private String oderId;
    private String currency;
    
    private SensitiveString cardNumber;

    private SensitiveString expiryMonth;

    private SensitiveString expiryYear;
...
```

**Comment by kalpakrg** [comment]
@dstango Thanks for the suggestion. The intention was to create a low boilerplate solution, so I prefer annotations. 

Have created a library for the same here: https://github.com/techbulls/techbulls-secure-logging. Hope it helps someone if they come looking for something similar.
