### ISSUE TITLE
Project Lombok website and domain migration

### ISSUE THREAD

**Issue by rspilker** [projectlombok/lombok#3243]
**Describe the bug**

We're currently working on replacing the hosting of the Project Lombok website. This also means that some binaries need to move as well.

We did prepare this move, and tested as much as possible.

If a problem occurs that you suspect is related to this migration, please let us know in the comments of this issue.

**Comment by pci-mthompson** [comment]
It looks like something is broken with the Eclipse P2 Update site?  I get this from the Oomph Repo Viewer: 
![image](https://user-images.githubusercontent.com/46202025/184431123-0a4bb4e5-24ac-4433-93fe-8ad5f0a50901.png)
and installer itself:
![image](https://user-images.githubusercontent.com/46202025/184431558-8b765779-9e3b-4b45-a397-8a24eaec0f84.png)

Similar issue with the Help/Install menu:
![image](https://user-images.githubusercontent.com/46202025/184431462-f2e0d663-1845-44d6-8a98-059c2fbb0f09.png)


Is there an alternative P2 URL I should try?  I'm glad to help test it out.  Thanks!

**Comment by rspilker** [comment]
Thanks, I think we forgot to migrate that one, will look into it very soon.

**Comment by pci-mthompson** [comment]
Thanks, it is working now! :)

**Comment by rspilker** [comment]
Let's keep the issue open for another week to see if we broke more

**Comment by edysli** [comment]
#3267 says that `https://projectlombok.org/features/Log` now returns 404 while `https://projectlombok.org/features/log` (lowercase "log") doesn't. Might this be caused by the migration?
If the links in javadoc need to be changed, I can submit a PR to fix #3267.
