### ISSUE TITLE
[BUG] @ExtensionMethod not working with Azul Zulu 17

### ISSUE THREAD

**Issue by gscaparrotti** [projectlombok/lombok#3249]
**Describe the bug**
When using Lombok with Gradle 7.5 and Azul Zulu 17, the following error appears when executing the `assemble` task:

`Lombok annotation handler class lombok.javac.handlers.HandleExtensionMethod failed on [MyClass]: java.lang.NoSuchMethodError: 'java.lang.Iterable com.sun.tools.javac.code.Scope$WriteableScope.getSymbols(java.util.function.Predicate)'
`

The error does not show up when compiling with Amazon Corretto or Oracle JDK.

**Version info (please complete the following information):**
 - Lombok version 1.18.24
 - Not working JDK: Zulu17+33-CA
 - Working JDK: Oracle JDK 17, Corretto-17.0.0.35.1

**Comment by Rawi01** [comment]
Works for me using the latest Zulu JDK. Can you try if an update fixes this problem?

**Comment by Rawi01** [comment]
No response from reporter, closing the issue.
