### ISSUE TITLE
[BUG] Some Lombok decorators do not work unless `SpringToolSuite4.ini` gets a `-javaagent:` property pointing to the Lombok JAR

### ISSUE THREAD

**Issue by kirisakow** [projectlombok/lombok#3253]
(This is a copy of the previously reported issue https://github.com/spring-projects/sts4/issues/828)

**Version:**

`lombok-1.18.24.jar` retrieved from https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.24

**Describe the bug**

* As described [here on StackOverflow](https://stackoverflow.com/questions/56596416/lombok-constructor-is-undefined/) in 2019 (and experienced by myself earlier today with the latest `sts-4.15.3.RELEASE` for Linux), using Lombok decorators such as `@Data`, `@NoArgsConstructor`, `@AllArgsConstructor` doesn't seem to produce the expected effect, and results in compilation errors and a `Constructor ... is undefined` error message during runtime.

**Hacky solution:**

* There is [a solution](http://codeomitted.com/setup-lombok-with-stseclipse-based-ide/) (which works) which consists in copying a Lombok JAR or its symbolic link to the STS installation directory, and putting a special mention about that JAR in the `SpringToolSuite4.ini` file, also located in the STS installation directory: `-javaagent:lombok.jar`.

**Comment by janrieke** [comment]
That's not a hack, that's exactly what the Lombok installer would do. So is the actual problem that the Lombok installer does not work with current STS versions?

**Comment by kirisakow** [comment]
I didn't use the Lombok installer, just —like I said— retrieved the information about the dependency from https://mvnrepository.com/artifact/org.projectlombok/lombok/1.18.24. 

Then, at runtime, I got the error message in console. But unfortunately no guidance from Lombok about what I could do — although it would be nice it there was guidance. You know, the same kind of message Spring Cloud dependencies show sometimes in console, when the problem seems to be well-known, and the fix easy to explain.

**Comment by janrieke** [comment]
Lombok is not a regular annotation processor. To do its work, it has to hook into the eclipse compiler. It cannot do that just by being on the classpath when compiling. Thus, you need to install Lombok to your IDE, as described [here](https://projectlombok.org/setup/eclipse).
Without that plugin, eclipse simply does not know about Lombok. Therefore, its compiler cannot know what went wrong or give you an advice how to solve it.
