### ISSUE TITLE
[BUG] Jacoco scan says Lombok Builder (generated code) is not ignored , and has no coverage

### ISSUE THREAD

**Issue by djangofan** [projectlombok/lombok#3277]
**Describe the bug**
[BUG] Jacoco scan says Lombok Builder (generated code) is not ignored , and has no coverage

**To Reproduce**
To reproduce, do a Jacoco scan of a Pojo class that has a @Builder on it.   Mark the class with @Generated , but After the scan you will notice the Builder inner class has no coverage.

**Expected behavior**
Builders generated from @Builder annotation should be marked as @Generated and therefore Jacoco knows not to scan it.

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Maven 3.6 Jacoco plugin

**Additional context**
Straight up issue, nothing tricky.

**Comment by djangofan** [comment]
My coverage report looks like this:
<img width="1997" alt="PAS_timeline" src="https://user-images.githubusercontent.com/810894/194612953-b9b8ed22-3fc2-46be-9238-143c91639f1f.png">

**Comment by djangofan** [comment]
My code coverage scan looks like this:
<img width="537" alt="Screen Shot 2022-10-07 at 10 10 35 AM" src="https://user-images.githubusercontent.com/810894/194613034-b1bf9e89-a964-431c-af91-6b9e667316c4.png">

**Comment by janrieke** [comment]
Have you tried adding `lombok.addLombokGeneratedAnnotation = true` to your `lombok.config` file?

**Comment by djangofan** [comment]
Sounds like that might work for me.  I'll try it today and let you know.

**Comment by djangofan** [comment]
yep, that setting works as described.  Thank you!
