### ISSUE TITLE
[BUG] @JsonUnwrapped not copied to @Builder methods in Eclipse IDE for record

### ISSUE THREAD

**Issue by MathiasDamMC** [projectlombok/lombok#3315]
**Describe the bug**
In Eclipes IDE lombok fails to copy the Jackson annotation @JsonUnwrapped from a **record** to the method on @Builder's. This works fine outside of Eclipse IDE. This issue seems related to https://github.com/projectlombok/lombok/issues/2736

Notice, this seems to work fine if used with **class** rather than **record**

**To Reproduce**
Run the following test case, this will fail in Eclipse as the @JsonUnwrapped is not copied to the builder() class method inner(). The same test case will work outside of Eclipse.
```
package test;

import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;

import com.fasterxml.jackson.annotation.JsonUnwrapped;

import java.util.Arrays;

import lombok.Builder;
import lombok.extern.jackson.Jacksonized;

class RecordAnnotationsNotCopiedTest {
    @Builder
    @Jacksonized
    record Example(@JsonUnwrapped Inner inner) {}
    
    record Inner(String s) {}
    
    @Test
    void testLombok() throws NoSuchMethodException, SecurityException {
        var method = Arrays.asList(Example.builder().getClass().getMethods()).stream().filter(m -> m.getName().equals("inner")).findFirst().get();
        assertThat(method.getAnnotations().length).isEqualTo(1);

    }
}
```

**Expected behavior**
This should also work in Eclipse IDE.

**Version info (please complete the following information):**
 - Lombok v1.18.24
 - Platform Eclipse  Version: 2022-06 (4.24.0)

**Comment by Rawi01** [comment]
This issue affects all copyable annotations on record components and is not limited to `@Jacksonized` or `@JsonUnwrapped`.

**Comment by namannigam** [comment]
@rzwitserloot after this change, the intent was to also imply this over classes(not ony records)?

**Comment by rzwitserloot** [comment]
@namannigam I'm not quite sure what, specifically, is failing. How does `@Json` relate to your snippet in any way? I'm not all that familiar with serialization or mocking, so you're going to have to spell out exactly -stick this in a source file, compile it like this, using these libraries and tools (e.g. Jsonthisorthat).

Or, if it's solely about the fact that your `CustomResponse.builder().messages(new String[]{"mock"}).build();` used to work but no longer does, and this has nothing to do with `@JsonUnwrapped`, I'm not sure this question belongs in this issue.

**Comment by namannigam** [comment]
The difference is in the auto generated `.class` file where the latest version 1.18.30 takes annotations like `@Nonnull` into considerations and throws NullpointerException while with previous version this wasn't the case. If you stil need a reproducible example, let me know and I would share that as soon as I get some time off work.

**Comment by Rawi01** [comment]
@namannigam I think you skipped 1.18.28 because we added support for `jakarta.annotation.Nonnull` in this release. That is unrelated to annotations on record components.

Changelog:
> FEATURE: Jakarta has some non-null annotations (such as jakarta.annotation.Nonnull) which we now support. [Issue #3346](https://github.com/projectlombok/lombok/issues/3346).

**Comment by namannigam** [comment]
@Rawi01 Got it, that should resolve my concern. My bad for not specifying that I was relying on the version upgrade of _Lombok via `spring-boot`_.
