### ISSUE TITLE
[BUG] lombok.config does not take effect for @Data

### ISSUE THREAD

**Issue by renci-zz** [projectlombok/lombok#3320]
I used lombok.config set lombok.toString.callSuper = CALL
When I use @Data annotation, toString() did not call super, when I use @ToString, toString() called super
equalsAndHashCode has the same problem

org.projectlombok:lombok:1.18.24

java version "17.0.5" 2022-10-18 LTS
Java(TM) SE Runtime Environment (build 17.0.5+9-LTS-191)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)

> lombok.config:
```java
config.stopBubbling = true
lombok.equalsAndHashCode.callSuper = CALL
lombok.toString.callSuper = CALL
lombok.sneakyThrows.flagUsage = ERROR
```

> BaseEntity.java:
```java
@Data
@MappedSuperclass
public abstract class BaseEntity<ID extends Serializable> implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public ID id;
}
```

> User.java
```java
@Data
public class User extends BaseEntity<Integer> {
    private String username;
}
```

**Comment by Rawi01** [comment]
Works for me. There also is a test case for it:
https://github.com/projectlombok/lombok/blob/3705ac615a34191e3f05bf02329a9ffe09d5fa65/test/transform/resource/before/DataConfiguration.java#L1-L8
https://github.com/projectlombok/lombok/blob/3705ac615a34191e3f05bf02329a9ffe09d5fa65/test/transform/resource/after-delombok/DataConfiguration.java#L1-L42

Please check if your setup is correct or/and provide a small sample project.

**Comment by renci-zz** [comment]
I test again, unable to reproduce the problem, invalid question.
