### ISSUE TITLE
Copy Spring @Value on fields to generated constructor parameter

### ISSUE THREAD

**Issue by camproto** [projectlombok/lombok#3322]
**Describe the feature**
I'm using lombok in Spring context, especially for generating constructors with @RequiredArgsConstructor for final fields (constructor injection). This replaces the @Autowired annotation on fields perfectly elegant with the Lombok constructor.

Using the Spring @Value annotation on fields breaks this elegance, because I need to put the full constructor code with @Value annotation on the constructor parameters, see sample code https://docs.spring.io/spring-framework/docs/5.3.14/reference/html/core.html#beans-value-annotations.

Would love Lombok would support that scenario and copy the @Value annotation from the field to the respective constructor parameter. This would make Lombok working even more smooth together with the very spread Spring framework.

**Describe the target audience**
Java projects using Lombok and Spring CDI together. 

**Additional context**
n/a

**Comment by avmohan** [comment]
@camproto This is already supported. 
Add below lines to lombok.config
```
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Value
lombok.copyableAnnotations += org.springframework.beans.factory.annotation.Qualifier
```
See https://github.com/rzwitserloot/lombok/issues/745

**Comment by camproto** [comment]
Thank you very much, missed that in the docs.
