### ISSUE TITLE
[FEATURE] setter and getter for @FieldNameConstants(asEnum = true)

### ISSUE THREAD

**Issue by Tobias4git** [projectlombok/lombok#3328]
**Describe the feature**
The existing annotation FieldNameConstants adds an inner enum with one value per field. I would like to have two methods generated for each value of the enum:

Object getValue(OriginatingClass instance);
and
void setValue(OriginatingClass instance, Object newValue);

In fact very similar to
Object java.lang.reflect.Field.get(Object obj)
and
void java.lang.reflect.Field.set(Object obj, Object value)

That would allow to iterate easily over all fields to implement specific marshaling or write a custom toString methods to hide passwords or hash personal data.

Example:
`@Data
@FieldNameConstants(asEnum = true, innerTypeName = "jobProps")
public class LombokTest {
    
    private String name;
    private String password;
    
    public String toString() {
        StringBuilder result = new StringBuilder();
        for (jobProps value : jobProps.values()) {
            if (value != value.password) {
                result.append(value.name() + "=" + value.getValue(this));
            }
        }
        return result.toString();
    }
}
`

**Describe the target audience**
Anyone with specific needs for marshaling and/or toString implementations.
(In fact toString is kind of an serialization)

**Comment by ManOki** [comment]
I'd prefer using setter/getter instead of reflection (or make it configurable to users).

In addition there should be a flag if the field is final (i.e., the setter/reflection will probably fail).

**Comment by Tobias4git** [comment]
> I'd prefer using setter/getter instead of reflection (or make it configurable to users).
> In addition there should be a flag if the field is final (i.e., the setter/reflection will probably fail).

I made the reference to reflection only to describe my idea. Yes, I prefer to have generated code instead of reflection.
Indeed, good point to skip or flag static/final/... (did I miss something) fields. 
On a second thought static fields may be useful to have a handle to.

**Comment by rzwitserloot** [comment]
The simple code snippet doesn't work, in that it produces `key=valuekey2=value2key3=value3` which looks cruddy. In other words, your 'look how easy this would make things' is misleading. It's not quite _that_ easy.

I dislike having an `Object` anywhere. Java is strongly typed. Having to resort to a bunch of `instanceof` and casts is a code smell. This doesn't cross the bar.
