### ISSUE TITLE
[BUG] Missing generated annotation on record

### ISSUE THREAD

**Issue by carlphilipp** [projectlombok/lombok#3339]
**Describe the bug**
When using:
```
lombok.addLombokGeneratedAnnotation = true
```
and:
```
@Builder
public record UserRecord(String name) {}
```
I would expect that the generated code contains the `@Generated` annotation on the method:
```
public String name() {
   return this.name;
}
```
Now, I guess this is debatable, as this is a method part of the record. I'm not too sure how that works internally, but maybe the other solution would be to not have that method at all in the generated record?

The root of the issue here is that by switching from normal class with `@Builder` to record with `@Builder`, we end-up having some code not covered with JaCoCo. At first sight it did not make a lot of sense why.

**To Reproduce**
I have created a sample project [here](https://github.com/carlphilipp/lombok-issue).
Just run
```
./gradlew clean build 
```
And you can check the generated classes and also jacoco report.

**Version info (please complete the following information):**
 - Lombok version: 1.18.24
 - Platform: Gradle 7.6
 - Java: Seen the issue on Java 17 and 19

**Comment by Rawi01** [comment]
Lombok marks everything it generates with this annotation. Why should it do the same for record components? This is a problem in JaCoCo and will also happen without lombok.

**Comment by pzygielo** [comment]
- Could https://github.com/jacoco/jacoco/issues/1215 be related?

**Comment by carlphilipp** [comment]
Thanks @pzygielo I bumped jacoco to latest snapshot and it seems that the report is correct now!
