### ISSUE TITLE
[BUG] toString is in infinite loop when 2 objects are cross referencing

### ISSUE THREAD

**Issue by hugoezgz** [projectlombok/lombok#3351]
In JPA classes with join relationship toString generated code is causing an infinite loop

@Data
public class ClassA{
  private ClassB b;
}

@Data
public class ClassB{
  private ClassA a;
}

public class Execute{
  public void infiniteLoop(){
      ClassA a=new ClassA();
      ClassB b=new ClassB();
      b.setA(a);
      a.setB(b);
      a.toString();
  }
}

**Comment by janrieke** [comment]
Due to technical limitations for annotation processors, Lombok cannot look into referenced classes to detect such cycles. Even if it could, it will always be a manual decision how to resolve this

PS: Same problem exists for `@EqualsAndHashcode`.

**Comment by janrieke** [comment]
See also #2255.

**Comment by hugoezgz** [comment]
Many thanks
