### ISSUE TITLE
[FEATURE] Add support for JDK 20

### ISSUE THREAD

**Issue by Rawi01** [projectlombok/lombok#3353]
**Describe the feature**
Add support for JDK 20. Release date is 2023-03-21.

**Additional context**
https://openjdk.org/projects/jdk/20/

**Comment by rzwitserloot** [comment]
Available on [edge](https://projectlombok.org/download-edge).

**Comment by SimSonic** [comment]
@rzwitserloot thanks a lot! Is any planned release date?

**Comment by SimSonic** [comment]
@rspilker maybe you can help?
