### ISSUE TITLE
Javac compilation and delombok failed (cannot find symbol / module)

### ISSUE THREAD

**Issue by seynax** [projectlombok/lombok#3363]
**Describe the bug**
Compiling through java or delombok command line of one of my projects fails with lombok use.

**To Reproduce**
- Clone the git project created for the occasion on which it does not work: git clone https://github.com/OnseaStudio/OnsieaEngine
- Launch compile and delombok batch scripts : "compile.bat" or "delombok.bat"
- Clone the git projet created for the occasion on wich it work: git clone https://github.com/OnseaStudio/AeisonLauncher
- Launch compile and delombok batch scripts : "compile.bat" or "delombok.bat"

Compile or delombok on AeisonLauncher it work, but on OnseaEngine I get :

- For compilation
```
sources\<file>.java:<line> error: cannot find symbol
                        <specific_line>
                                      ^
  symbol:   method <specific method>()
  location: variable <specitif_variable> of type <specific_type>
```
for example :
```
sources\common\fr\onsiea\engine\common\OnsieaGearings.java:230: error: cannot find symbol
                        this.sync(this.dataCounter.loopStartTime, this.dataCounter.secsPerFrame());
                                                                                  ^
  symbol:   method secsPerFrame()
  location: variable dataCounter of type DataCounter
```

- For delombok in module info
```
J:\Programmations\java\git\OnsieaEngine\sources\common\module-info.java:<line>: error: module not found: <module>
        requires <module>
                          ^
```
For example :
```
J:\Programmations\java\git\OnsieaEngine\sources\common\module-info.java:57: error: module not found: org.lwjgl.glfw
        requires org.lwjgl.glfw;
                          ^
```

**Expected behavior**
I must be missing something, but I expect the behavior to be the same as with AeisonLauncher

**Version info :**
 - Lombok version 1.18.26
 - Platform javac / java version 19.0.2
 - Windows

**Additional context**
tests :
- with --<...>path %..._path% and --<...>_path=%..._path%
- with sources in same folder
- by specifying the module-info directly or its directory in source or module path
- lombok added in module path AND/OR class path
- Others Java(c) and Lombok versions

**Comment by seynax** [comment]
Tests for the "javac" command

I come back to you, I tried to create a project from 0 with the same sources, as I had imagined, in vain.

I then tried to create a main class, adding (and compiling) as and when content similar to the project. First Lombok, then the LWJGL. No problem.

But when I started using the sources of my project again, the problem arises. I noticed that it's not so much my project that's the problem, but the fact that multiple classes come into play.

I then said to myself that when you specify a source via the sourcepath argument, these sources are used without lombok processing, because when I compile them by specifying it alongside the main class in the input argument, it does not there is no problem.
BUT, I then tried to move a contained class into another that uses lombok (getter, constructor etc). No problem even without specifying it in the sources input argument. I create another in the same place, I create a dummy variable with @Getter in front and there impossible to recover this method.

**Comment by seynax** [comment]
https://stackoverflow.com/questions/6623161/javac-option-to-compile-all-java-files-under-a-given-directory-recursively
If I use :
dir /s /B *.java > sources.txt
javac @sources.txt [...]
(thank you microsoft ...)

It work. Now, I search for delombok command.

**Comment by Rawi01** [comment]
The `bat` files you shared use completly different commands to run delombok. I'm not sure why you try to delombok the project but it also supports `@args.txt`.

As mentioned in the linked stackoverflow thread I recommend you to use a build tool. That will probably fix all your compilation problems.

**Comment by seynax** [comment]
> Les `bat`fichiers que vous avez partagés utilisent des commandes complètement différentes pour exécuter delombok. Je ne sais pas pourquoi vous essayez de supprimer le projet, mais il prend également en charge `@args.txt`.
> 
> Comme mentionné dans le thread stackoverflow lié, je vous recommande d'utiliser un outil de construction. Cela résoudra probablement tous vos problèmes de compilation.

Bonjour,

En fait j'utilise bien des outils de constructions (IDE et Maven), mon but était de créer un code qui peut télécharger des sources via github et les recompiler automatiquement, une sorte de système de mise à jour pour projet en cours de dev.

- _PS : je sais que télécharger des sources puits les compiler plutôt que de télécharger des sources déjà compilé semble étrange, en fait j'avais des contrainte de connexion et plutôt que de publier un jar complet avec tout ce que ça implique, je mettais juste à jour les sources qui avait changé, ce qui réduit la quantité de données à envoyer._

Le soucis c'est que la commande Javac échouée à cause de Lombok, j'ai alors voulu ajouter une étape dans mon système, téléchargement->délombok->compilation.

Mais cette commande aussi échouée

la commande pour delombok que j'utilise est celle-ci (les autres lignes ne sont pas directement lié à lombok :

- `%java_exe% --module-path %modules_path% -Dfile.encoding=UTF-8 %delombok% -v --module-path %modules_path% --classpath %classes_path% %sources_path% -d %destination_path%`

- _D'ailleurs je viens de voir qu'il manque une variable pour %delombok% mais ça n'a pas d'importance elle était bien là lors de mes tests_

en effet c'est assez différent de ce que dit la documentation :

- `java -jar lombok.jar delombok src -d src-delomboked`

mais j'ai bien commencé par faire exactement ce que dis la doc, comme cela ne fonctionné pas (sauf avec un projet plus petit), j'ai tenté des trucs et cette commande était ma dernière itération de test qui ne fonctionnait toujours pas.

**Je vais essayer avec @sources.txt**

Merci pour votre réponse en tout cas.
