### ISSUE TITLE
[BUG] Expression appears twice in the generated AST

### ISSUE THREAD

**Issue by igfoo** [projectlombok/lombok#3364]
**Describe the bug**

When the `@Builder` annotation is used, a `JCExpression` for the the build method return type is [created](https://github.com/projectlombok/lombok/blob/e5c324c615c1e304b2a9a64bc7f8608a67b0a74e/src/core/lombok/javac/handlers/HandleBuilder.java#L305). This is then passed to [generateBuildMethod](https://github.com/projectlombok/lombok/blob/e5c324c615c1e304b2a9a64bc7f8608a67b0a74e/src/core/lombok/javac/handlers/HandleBuilder.java#L738), which uses it twice, when generating a `new` expression and when generating the method.

I don't know if this is the best fix, but it looks like
```
returnType = cloneType(maker, returnType, job.sourceNode);
```
around line 798 fixes it.

**To Reproduce**

```
package com.mycompany.app;

import lombok.Builder;
import lombok.Singular;
import java.util.List;

public class App 
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );
    }
}

@Builder
class BuilderClass {
    @Singular
    private List<Integer> someIntegers;
}
```

**Expected behavior**

I expected that expression nodes would only have a single parent in the AST.

**Version info (please complete the following information):**
 - Lombok version: 1.18.26 and master (e5c324c615c1e304b2a9a64bc7f8608a67b0a74e)
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.: javac 17.0.6

**Additional context**

**Comment by igfoo** [comment]
I don't have full details, but I think there's a similar problem with `@Getter(lazy=true)`, e.g. using the example from the docs:
```
package testProject;

import lombok.Getter;

public class App {
  @Getter(lazy=true) private final double[] cached = expensive();

  private double[] expensive() {
    double[] result = new double[1000000];
    for (int i = 0; i < result.length; i++) {
      result[i] = Math.asin(i);
    }
    return result;
  }
}
```
which seems to be fixed by
```
--- a/src/core/lombok/javac/handlers/HandleGetter.java
+++ b/src/core/lombok/javac/handlers/HandleGetter.java
@@ -463,6 +463,6 @@ public class HandleGetter extends JavacAnnotationHandler<Getter> {
        }
        
        public JCExpression copyType(JavacTreeMaker treeMaker, JCVariableDecl fieldNode) {
-               return fieldNode.type != null ? treeMaker.Type(fieldNode.type) : fieldNode.vartype;
+               return fieldNode.type != null ? treeMaker.Type(fieldNode.type) : cloneType(treeMaker, fieldNode.vartype, null);
        }
 }
```
(although I'm sure that this one isn't the best fix; at the very least we should pass something better than `null`)

**Comment by igfoo** [comment]
That sounds great, thanks!

**Comment by rzwitserloot** [comment]
Available on [edge](https://projectlombok.org/download-edge).

**Comment by igfoo** [comment]
Awesome, thanks!
