### ISSUE TITLE
[BUG] Lombok stop working on Eclipse 4.18.0

### ISSUE THREAD

**Issue by danibs** [projectlombok/lombok#3374]
**Describe the bug**
Annotation `@Data` doesn't create fluent setter.

**To Reproduce**
```java
@Data
public class ResultBean {
	private String id;
	private String code;
}

final ResultBean r1 = new ResultBean().setId( "1" ).setCode( "c1" );
  --> _Cannot invoke setCode(String) on the primitive type void_
```

**Version info (please complete the following information):**
 - Lombok version: 1.18.26
 - Eclipse Version: 4.18.0.RELEASE ( Spring Tool Suite 4 ) - Build Id: 202303131455
- S.O. Ubuntu 18.04
- Java 17

**Comment by dstango** [comment]
I think you mixed up versions here: Spring Tools 4.18.0 is based on Eclipse 2023-03 (aka Eclipse 4.27).

Anyhow: your error seems to be related to https://github.com/projectlombok/lombok/issues/3332, as the error message indicates that your lombok.config might contain `lombok.accessors.fluent = true` (see https://projectlombok.org/features/experimental/Accessors).

**Comment by danibs** [comment]
In my case the property is `lombok.accessors.chain = true` but yes, I think you catch the real problem!

**Comment by dstango** [comment]
yes, I picked the wrong config option, sorry :-)

**Comment by luca-bassoricci** [comment]
also `lombok.log.fieldName` stops to work after Eclipse upgrade

**Comment by dstango** [comment]
> also `lombok.log.fieldName` stops to work after Eclipse upgrade

All this seems to be a result of https://github.com/projectlombok/lombok/issues/3332, so I'd guess these issues all to be duplicates of #3332.

**Comment by Rawi01** [comment]
#3332 is fixed and there will be a release soon
