### ISSUE TITLE
[Eclipse 4.27] Lombok ignores lombok.config

### ISSUE THREAD

**Issue by danibs** [projectlombok/lombok#3382]
I tried with Eclipse:
Version: 2023-03 (4.27.0)
Build id: 20230309-1520

**Lombok**:
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: 14.3-b01-101 (Apple Inc.)
Premain-Class: lombok.launch.Agent
Agent-Class: lombok.launch.Agent
Can-Redefine-Classes: true
Main-Class: lombok.launch.Main
Lombok-Version: 1.18.27
Automatic-Module-Name: lombok

As you can see, still doesn't work. `setC1()` return `void` instead of class it-self

![immagine](https://user-images.githubusercontent.com/30932554/227721154-6327e572-674b-4270-bb27-f1251875f58c.png)

_Originally posted by @danibs in https://github.com/projectlombok/lombok/issues/3332#issuecomment-1483830304_

**Comment by Rawi01** [comment]
Works for me:
![img](https://user-images.githubusercontent.com/5850477/227765020-ae42cc1e-a1fb-42ae-9da8-9f6f4f00890a.png)

Can you check that the right lombok version shows up in the "About Eclipse" dialog?

**Comment by zeroinformatique** [comment]
The bugfix is available in the "Edge" download section:
https://projectlombok.org/download-edge

**Comment by danibs** [comment]
Sorry, my mistake! 😢
The .ini file was configured with the wrong path of Lombok...
Fixed that, it works for me too.

Sorry again...

**Comment by mxmlnglt** [comment]
> The bugfix is available in the "Edge" download section: https://projectlombok.org/download-edge
> 
> It works on my side. Are you sure you installed it correctly?

Repo URL is down... you can only download the .jar by yourself... see https://github.com/projectlombok/lombok/issues/3414
