### ISSUE TITLE
How to import the project into my IDEA

### ISSUE THREAD

**Issue by YcccByHe** [projectlombok/lombok#3384]
How to import the project into my IDEA，Do I need to introduce additional lib packages?I have a lot of problems after importing，For example, there is no objectweb package

**Comment by Rawi01** [comment]
Lombok uses `ant` as build system. If you run `ant` in your lombok directory it shows the quickstart guide. `ant help` will show you a longer list of `ant` commands that you might need. In your case `ant intellij` should generate a IntelliJ project that can be used for development.

Most contributors use eclipse and the IntelliJ support is experimental, it might not work out of the box.

**Comment by YcccByHe** [comment]
Thanks

**Comment by YcccByHe** [comment]
thanks
