### ISSUE TITLE
[BUG] NoDefClassError in Eclipse with Edgy Guinea Pig

### ISSUE THREAD

**Issue by drewshz** [projectlombok/lombok#3388]
**Describe the bug**
Eclipse fails to compile with following message:

Internal compiler error: java.lang.NoClassDefFoundError: Could not initialize class lombok.launch.PatchFixesHider$ExtensionMethod at org.eclipse.jdt.internal.compiler.ast.MessageSend.resolveType(MessageSend.java:1003)

**To Reproduce**
Happens in all Eclipse versions with Lombok Edgy Guinea Pig

**Version info (please complete the following information):**
 - Lombok v1.18.27 "Edgy Guinea Pig"
 - Platform Eclipse Version: 2023-03 (4.27.0), Build id: 20230309-1520

**Comment by Rawi01** [comment]
This was fixed in #3378
