### ISSUE TITLE
[BUG] Eclipse reports import cannot be resolved when using @ToString with Edgy Guinea Pig, or Eclipse errors with default non null annotations

### ISSUE THREAD

**Issue by Ravynne** [projectlombok/lombok#3390]
**Describe the bug**
Eclipse code editor is showing various imports in red with the message that the import cannot be resolved. However, Eclipse problems tab or package explorer does not report an error.

**To Reproduce**
I'm having difficulties making a standalone project to reproduce the problem. I hope what I wrote could be used to help track down this issue.

I use Eclipse null annotations processing and have defined a lombok.config with
lombok.addNullAnnotations = spring

With Lombok 1.18.26, Eclipse 4.27.0 had an issue with my usage of @lombok.Value because it was ignoring lombok.config. I learned I could make the error go away by replacing @Value with @Getter, @AllArgsConstructor, and @ToString. (I didn't need the hashcodes and equals methods).

Then I learned of Edgy Guinea Pig. Eclipse compiler would no longer report errors with my use of @Value. But for the cases that I previously changed to @Getter, @AllArgsConstructor, @ToString, I now get an Eclipse error in the editor window only in other classes that import these classes. This error goes away if I remove @ToString or revert back to @Value.

These classes with @Value or @Getter, @AllArgsConstructor, @ToString are in a package with package-info.java and use of @org.springframework.lang.NonNullApi and 
@org.springframework.lang.NonNullFields.

The classes with @Value that were changed to @Getter, @AllArgsConstructor, @ToString just demonstrate the problem only when the fields are not @Nullable

Examples:
`import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@AllArgsConstructor
@ToString
public class SiteRevisionSummarySiteName {

    private final String siteName;

}

---------------------

import org.springframework.lang.Nullable;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@AllArgsConstructor
@ToString
public class LatestSiteDetailStatus {

    private @Nullable String dataStatus;

}
`
![image](https://user-images.githubusercontent.com/5552917/228881961-364c4dc0-f65e-4ebb-8a90-f176a7fc81f7.png)

So LatestSiteDetailStatus works fine because it defines the field as @Nullable. But SiteRevisionSummarySiteName is not working as expected because it relies on default @NonNull as defined in package-info. References to that class get the error "SiteRevisionSummarySiteName cannot be resolved to a type"

But the error only shows in the editor window, not the problems tab. (And no, I don't have a filter to hide problems - Package Explorer has no decorations for errors.

I just now did a test and found that:
``import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@AllArgsConstructor
@ToString
public class SiteRevisionSummarySiteName {

    private final @NonNull String siteName;

}`

Adds an Eclipse warning about redundant nullness annotation (because package-info already says non-null by default), but the errors in other code file that Lombok was generating now goes away.

So now it's looking like some kind of interaction with package-info , default non-null, and not having an annotation.

**Expected behavior**
No error messages in the Eclipse editor.

**Version info (please complete the following information):**
 - Lombok version - Edgy Guinea Pig as of March 28
 - Platform Eclipse Version: 2023-03 (4.27.0) Build id: 20230309-1520

**Comment by Rawi01** [comment]
Works for me:
![img](https://user-images.githubusercontent.com/5850477/229273160-dde21ade-577d-43f3-90d5-63e32e944a8d.png)

**Comment by Ravynne** [comment]
I got a new computer and used newest version of Edgy Guinea Pig. I can't reproduce anymore. Closing.
