### ISSUE TITLE
[BUG] lombok 1.8.26 incompatible with JDK21

### ISSUE THREAD

**Issue by jnaalisv** [projectlombok/lombok#3393]
**Describe the bug**
Lombok 1.8.26 does not work with JDK21 (EA build 16)

**To Reproduce**
```
import lombok.Data;

@Data
public class Person {

    private String name;
}
```

```
$ javac -version
javac 21-ea
$ javac -cp lombok-1.18.26.jar Person.java
```
will fail with this error:
```
An annotation processor threw an uncaught exception.
Consult the following stack trace for details.
java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
	at lombok.javac.JavacImportList.getFullyQualifiedNameForSimpleNameNoAliasing(JavacImportList.java:53)
	at lombok.core.TypeResolver.typeRefToFullyQualifiedName(TypeResolver.java:60)
	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:247)
	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:79)
	at lombok.javac.JavacNode.traverse(JavacNode.java:132)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:222)
	at lombok.javac.JavacNode.traverse(JavacNode.java:90)
	at lombok.javac.JavacAST.traverse(JavacAST.java:218)
	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:328)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1017)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:933)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1261)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1376)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1252)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:934)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Expected behavior**
Lombok should work with JDK21

**Version info:**
 - Lombok 1.8.26
 - Platform javac 21-ea, build 16

**Comment by jnaalisv** [comment]
I probably should have opened this as a "Feature Request"?

**Comment by Rawi01** [comment]
Whether you consider this a bug or a feature is debatable. In any case, thanks for creating it.

**Comment by kangarko** [comment]
@Rawi01 is lombok compatible with Java 20? Last changelog only mentions JDK 19

**Comment by dstango** [comment]
@kangarko https://github.com/projectlombok/lombok/issues/3353

**Comment by kangarko** [comment]
My apologies, I have missed that!

**Comment by SimSonic** [comment]
Very slow release cycle for 20 and 19 Java versions. I understand that odd versions are interpreted as cutting edge and even as stable, but maybe we need to split releases which adds only support for new Java releases and feature-rich releases?

**Comment by jnaalisv** [comment]
When can we expect the fix to be integrated? I just tested with the latest build (21.ea.26-open) and it fails with the same stacktrace. That build is now feature complete, so there should not be any big changes before the GA release in September.

**Comment by Rawi01** [comment]
There are some more failing tests using the latest ea build. I will try to fix that this week,

**Comment by NotArchon** [comment]
Any workarounds?

**Comment by minsaram** [comment]
Is the fix released?

**Comment by evantoli** [comment]
Just wondering if there is any news on this or any workarounds?

**Comment by matthiasblaesing** [comment]
This is also a problem for NetBeans, which builds on top of javac and no renders all lombok using classes as broken.

**Comment by Rawi01** [comment]
You can use my jdk21 branch or download the ci build artifact if you really need to use JDK21 now.

**Comment by estekhin** [comment]
@Rawi01 please release a central version with these changes.

I tried edge snapshot from https://projectlombok.org/download-edge locally with JDK 21 ea b34, and my code base builds and passes tests - thanks a lot for the fix!

I would like to use it in CI builds that run against Java 21 EA, but i can't due to constraints on which repositories i can use there.

**Comment by lennart-bos** [comment]
Edge snapshot indeed works much better, but `@SneakyThrows` isn't working yet:
```
Error during the transformation of 'xxx'; post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 65
[ERROR]         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
[ERROR]         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
[ERROR]         at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
[ERROR]         at lombok.bytecode.AsmUtil.fixJSRInlining(AsmUtil.java:37)
[ERROR]         at lombok.bytecode.SneakyThrowsRemover.applyTransformations(SneakyThrowsRemover.java:46)
[ERROR]         at lombok.core.PostCompiler.applyTransformations(PostCompiler.java:44)
[ERROR]         at lombok.core.PostCompiler$1.close(PostCompiler.java:87)
[ERROR]         at jdk.compiler/com.sun.tools.javac.jvm.ClassWriter.writeClass(ClassWriter.java:1548)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.genCode(JavaCompiler.java:770)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1709)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.generate(JavaCompiler.java:1677)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:978)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:136)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:183)
[ERROR]         at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1140)
[ERROR]         at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:199)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR]         at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR]         at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
```

**Comment by dgcooke** [comment]
I am finding even with the edge version I am still getting the same result,

java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' 

openjdk version "21" 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

**Comment by alison-gravley** [comment]
I just wanted to throw in with this. Java 21 and eventually 22 will be **VERY** important to me and my team as we are starting to use Panama for our projects, which will be out of pre-release starting in Java 22 (March 2024). 

I was able to get past the error above, once I included the repository and changed to the edge release, but this came up.

```text
Compilation failure
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
```
  
Here are the changes I made to my pom.xml to get it to compile again. For some reason I had to specifically add the org.slf4j dependency as well to get things to work.

```xml
<project ...>
...
    <repositories>
        <repository>
            <id>projectlombok.org</id>
            <url>https://projectlombok.org/edge-releases</url>
        </repository>
    </repositories>
...
    <dependencies>
...
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.7</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>edge-SNAPSHOT</version>
        </dependency>
    </dependencies>
...
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compilerplugin.version}</version>
                <configuration>
                    <source>21</source>
                    <target>21</target>
                    <enablePreview>true</enablePreview>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>edge-SNAPSHOT</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            ...
        </plugins>
    </build>
...
</project>
```

**Comment by Rawi01** [comment]
The message about annotation processing was backported to 21 but should not break the compilation, it is only a warning and it disappears if you add lombok as explicit annotation processor (as you did).

Slf4j is not required for lombok and it should not change anything expect you `@Slf4j` somewhere in your code.

You should also add `<scope>provided</scope>` to the lombok dependency in your `pom.xml` to not include it at runtime.

**Comment by dgcooke** [comment]
> I am finding even with the edge version I am still getting the same result,
> 
> java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
> 
> openjdk version "21" 2023-09-19 OpenJDK Runtime Environment (build 21+35-2513) OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

This is resolved using edge-SNAPSHOT, I had missed the annotation processor
<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>

**Comment by lpandzic** [comment]
For me it works without maven plugins configuration, a simple dependency sufficed.

```xml
<dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>edge-SNAPSHOT</version>
		</dependency>
               ... spring-boot-dependencies or some other bom
```

```xml
<repositories>
	<repository>
		<id>projectlombok.org</id>
		<url>https://projectlombok.org/edge-releases</url>
	</repository>
</repositories>
```

**Comment by danjee** [comment]
I still get the same error with 1.18.28

```[ERROR] java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
[ERROR] 	at lombok.javac.JavacImportList.getFullyQualifiedNameForSimpleNameNoAliasing(JavacImportList.java:53)
[ERROR] 	at lombok.core.TypeResolver.typeRefToFullyQualifiedName(TypeResolver.java:60)
[ERROR] 	at lombok.javac.HandlerLibrary.handleAnnotation(HandlerLibrary.java:247)
[ERROR] 	at lombok.javac.JavacTransformer$AnnotationVisitor.visitAnnotationOnType(JavacTransformer.java:79)
[ERROR] 	at lombok.javac.JavacNode.traverse(JavacNode.java:132)
[ERROR] 	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:223)
[ERROR] 	at lombok.javac.JavacNode.traverse(JavacNode.java:95)
[ERROR] 	at lombok.javac.JavacAST.traverseChildren(JavacAST.java:223)
[ERROR] 	at lombok.javac.JavacNode.traverse(JavacNode.java:90)
[ERROR] 	at lombok.javac.JavacAST.traverse(JavacAST.java:219)
[ERROR] 	at lombok.javac.JavacTransformer.transform(JavacTransformer.java:63)
[ERROR] 	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:324)
[ERROR] 	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:187)
[ERROR] 	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:241)
[ERROR] 	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:90)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:1021)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:937)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1265)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1380)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1271)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:948)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:319)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
[ERROR] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :domain-core
➜  as-api git:(master) ✗ java -version
openjdk version "21" 2023-09-19 LTS
OpenJDK Runtime Environment Corretto-21.0.0.35.1 (build 21+35-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.0.35.1 (build 21+35-LTS, mixed mode, sharing)
➜  as-api git:(master) ✗ cat pom.xml | grep lombok.version
        <lombok.version>1.18.28</lombok.version>
```

**Comment by linghengqian** [comment]
- @danjee This fix is ​​in 1.18.29, not 1.18.28.  Reference https://github.com/projectlombok/lombok/blob/master/src/core/lombok/core/Version.java .

**Comment by szantopeter** [comment]
@linghengqian When will 1.18.29 become available in maven central? As of now 1.18.28 is the latest here :

https://central.sonatype.com/artifact/org.projectlombok/lombok/versions

**Comment by linghengqian** [comment]
> @linghengqian When will 1.18.29 become available in maven central? As of now 1.18.28 is the latest here :
> 
> https://central.sonatype.com/artifact/org.projectlombok/lombok/versions

- @szantopeter I'm not a Lombok Committer, I don't know anything about it. 

- According to https://groups.google.com/g/project-lombok/c/gdpmprn1B40/m/VYOuh6g3AQAJ , Lombok will be release in today. Or tomorrow?

**Comment by rzwitserloot** [comment]
odd numbers are edge releases. We'll release 1.18.30 which is JDK21 compatible shortly (preferably today).

**Comment by emmysteven** [comment]
> @Rawi01 is lombok compatible with Java 20? Last changelog only mentions JDK 19

Yes, Lombok is compatible with Java 20, but it is not yet compatible with the newly released Java 21 LTS

**Comment by emmysteven** [comment]
> * @danjee This fix is ​​in 1.18.29, not 1.18.28.  Reference https://github.com/projectlombok/lombok/blob/master/src/core/lombok/core/Version.java .

Please when will the fix be made available?

**Comment by rzwitserloot** [comment]
@emmysteven Read 2 comments up. Come on man, give open source devs a break and take 30 seconds to do some effort before asking.

**Comment by rzwitserloot** [comment]
v1.18.30 is out now. Reload your maven caches - might take about an hour. It supports JDK21.

**Comment by PolarisDraco** [comment]
> v1.18.30 现已发布。重新加载您的 maven 缓存 - 可能需要大约一个小时。它支持 JDK21。

Thank you for the update. It's very timely

**Comment by noear** [comment]
哈哈。。。我的 [Solon Java Framework](https://github.com/noear/solon) 在 JDK21 上编译也出这个错了。

**Comment by CasaSky** [comment]
not working :/ using gradle plugin 8.3 even with updated maven repositories.

**Comment by noear** [comment]
测试通过了。。。感谢！

**Comment by mkorman9** [comment]
> not working :/ using gradle plugin 8.3 even with updated maven repositories.

Gradle 8.3 doesn't yet work with JDK 21

**Comment by emmysteven** [comment]
> @emmysteven Read 2 comments up. Come on man, give open source devs a break and take 30 seconds to do some effort before asking.

Apologies, forgive my impatience 🤦‍♂️

**Comment by BenTown** [comment]
> > not working :/ using gradle plugin 8.3 even with updated maven repositories.
> 
> Gradle 8.3 doesn't yet work with JDK 21

It works with Gradle 8.2.1.

**Comment by mkorman9** [comment]
> > > not working :/ using gradle plugin 8.3 even with updated maven repositories.
> > 
> > 
> > Gradle 8.3 doesn't yet work with JDK 21
> 
> It works with Gradle 8.2.1.

But it's not officialy supported yet - https://docs.gradle.org/current/userguide/compatibility.html

Full support is expected in 8.4

**Comment by jwtodd** [comment]
> not working :/ using gradle plugin 8.3 even with updated maven repositories.

❓ what parts of gradle:8.3 don't work with jdk:21?

i did a quick smoke test of ./gradlew clean build (test) atop jdk:21 (corretto) and it built/tested cleanly, then ran the code albeit from intellij/jdk:21

i have yet to gradle:jib on jdk:21 though 🤔

**Comment by Jzow** [comment]
thanks

**Comment by CasaSky** [comment]
The plugin as I said. When I replaced it by vanilla dependencies everything is just working fine. Probably the Lombok plugin was not fetching the latest Lombok version.

**Comment by Desoroxxx** [comment]
Still getting:
```
java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'
```
When using Lombok with JDK 21

**Comment by archfish** [comment]
if you are using idea, check `.idea/misc.xml` file, and find `ProjectRootManager` check `languageLevel` and `project-jdk-name`.

**Comment by sepe81** [comment]
Could you please also include this patch (dependency update) within a new release of lombok-maven-plugin?

The [older versions <= 1.18.20.0](https://mvnrepository.com/artifact/org.projectlombok/lombok-maven-plugin) only work under Java 21 by explicitly adding/overriding lombok 1.18.30.

```
            <plugin>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-maven-plugin</artifactId>
                <version>1.18.20.0</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>delombok</goal>
                        </goals>
                        [...]
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.projectlombok</groupId>
                        <artifactId>lombok</artifactId>
                        <version>1.18.30</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by rzwitserloot** [comment]
@sepe81 That plugin is separately maintained by @awhitford - see http://anthonywhitford.com/lombok.maven/lombok-maven-plugin/

**Comment by MeqdadDev** [comment]
Fixed in 1.18.30
I've just upgraded my lombok version in pom.xml to:
```
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version>
            <optional>true</optional>
</dependency>
```

**Comment by vladimirvs** [comment]
Only upgrading to `1.18.30` helps, as @MeqdadDev  suggested, worked.

**Comment by yasin-herken** [comment]
// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// Mapstruct
	compileOnly "org.mapstruct:mapstruct:${mapstructVersion}"
	annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
	testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
def mapstructVersion = "1.5.3.Final"
it runs with java 21

**Comment by fulus06** [comment]
需要清楚缓存，或者查找是否有其他版本lombok

**Comment by fulus06** [comment]
需要清楚缓存，或者查找是否有其他版本lombok

![image](https://github.com/projectlombok/lombok/assets/12890684/0bdb4fe6-b2f7-4b35-b74f-cc2279c7e1b8)

**Comment by youngclown** [comment]
compileOnly 'org.projectlombok:lombok:1.18.30'
//    implementation 'org.projectlombok:lombok:1.18.30'
    **annotationProcessor 'org.projectlombok:lombok:1.18.30'**

**Comment by mohssinassel** [comment]
to solve it follow those steps in this web site
https://projectlombok.org/download-edge

**Comment by Romulo-S** [comment]
Fixed by updating springboot to 3.1.4.

The error should be more friendly tough.

https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n

**Comment by Rohan-Rathod** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.2</version>
		<relativePath/> 
	</parent>
	<groupId>com.example</groupId>
	<artifactId>dettol</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>dettol</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>17</java.version>
	</properties>
	
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.28</version>
		</dependency>
		
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.24</version>
		</dependency>


		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

**Comment by Rohan-Rathod** [comment]
//getting these below error while running above code 

java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

**Comment by Renas63** [comment]
Getting this error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project HE Automation: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x21e97905) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x21e97905 -> [Help 1]
Any help will be appreciated!
