### ISSUE TITLE
[BUG]  the class that implements the interface have @Data annotations that need to overload the set method but not the get method

### ISSUE THREAD

**Issue by ordinary-s** [projectlombok/lombok#3395]
**Describe the bug**
the class that implements the interface have @Data annotations that need to overload the set method but not the get method

**To Reproduce**
entity.FunctionHistory is not abstract and does not override the abstract method setPhysicalData(service.IBaseHistory.entity.PhysicalData)

public interface IBaseHistory {
    String getCoId();
    void setPhysicalData(PhysicalData physicalData);
}
@Data
public class FunctionHistory  implements Serializable,IBaseHistory{
private String coId;
private PhysicalData physicalData;
}
**Expected behavior**
give me an answer for this question

**Version info (please complete the following information):**
 - Lombok version 1.18.22
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.

**Additional context**

**Comment by Rawi01** [comment]
Please do not use the issue tracker for coding questions.
```java
public class FunctionHistory implements Serializable, IBaseHistory{
	@Getter
	private String coId;
	@Setter
	private PhysicalData physicalData;
}
```
