### ISSUE TITLE
[BUG]  QUESTION about super() calls from annotations

### ISSUE THREAD

**Issue by Guarmanda** [projectlombok/lombok#3412]
**Describe the bug**
Not a but, but there's no section to expose my issue
I have a parent class, and a child class that extends it.
I want to make constructors that calls 'super()' and I have so many questions, because there's nothing in the doc about it :/
- Does @ Data constructor calls super?
- Does @ NoArgsConstructor calls super?
- Does @ RequiredArgsConstuctor calls super?

And if not, is there a way to do it?

**Comment by Rawi01** [comment]
In Java a constructor always have to call a constructor of the parent class. If you do not specify one it calls `super()`.

There is no special magic in Lombok for constructor annotations so they always call the no-args parent constructor.
