### ISSUE TITLE
[BUG] @Log4j2 Not the output I expected with two params

### ISSUE THREAD

**Issue by zxk1111** [projectlombok/lombok#3413]
Describe the bug
**code**
log.info("param1:{},param2:{}", "Test1","{}");
**console print**
param1:Test1,param2:Test1
**Expected behavior**
param1:Test1,param2:{}
**Version**
```java
<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
            <version>1.18.26</version>
</dependency>
```
**Additional context**
Only when the latter parameter value is {} will the previous parameter value be printed

is this a bug?

**Comment by janrieke** [comment]
Maybe a log4j2 bug, but definitely not a Lombok bug.
Check log4j2 docs or ask at StackOverflow.

**Comment by rspilker** [comment]
Agreed
