### ISSUE TITLE
[BUG] Serialize abstract class with SuperBuilder using Jackson does not serialize any attribute in parent class

### ISSUE THREAD

**Issue by Ezyhoo** [projectlombok/lombok#3421]
**Describe the bug**
Serialize abstract class with SuperBuilder using Jackson does not serialize any attribute

**To Reproduce**
```
@NoArgsConstructor
@AllArgsConstructor
@Data
@SuperBuilder
public abstract class Parent {
    private String parentA;
    private String parentB;
}
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class ChildOne extends Parent{
    private String childOneA;
    private String childOneB;
}
@Data
@NoArgsConstructor
@EqualsAndHashCode(callSuper = true)
@SuperBuilder
public class ChildTwo extends Parent{
}

public static void main(String[] args) {

    Map<Parent, List<String>> parent2Strs = new HashMap<>();
    parent2Strs.put(ChildTwo.builder().parentA("A").parentB("B").build(), List.of("1", "2"));
    parent2Strs.put(ChildTwo.builder().parentA("C").parentB("D").build(), List.of("1"));

}
```

When I print Jackson's writeValueAsString(parent2Strs) method, it doesn't print any attribute in parent class.

**Expected behavior**
All attributes in child/parent should be serialized/printed out

**Version info (please complete the following information):**
 - Lombok version: 1.18.24
 - Platform (IntelliJ, javac 1.8.0_292)

**Comment by janrieke** [comment]
Not a bug, neither in Lombok nor in Jackson: JSON keys must be strings, so Jackson uses `toString()` to serialize them.
