### ISSUE TITLE
[BUG] Eclipse handlers don't support enum constants

### ISSUE THREAD

**Issue by vladtimofeev000** [projectlombok/lombok#3427]
**Describe the bug**
For enum constants JDT leaves null TypeReference in `org.eclipse.jdt.internal.compiler.ast.FieldDeclaration`, but `lombok.eclipse.handlers.HandleGetter` doesn't ready for it so there will be several problems:

1. NPE at [isBoolean](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/EclipseHandlerUtil.java#L1425)
2. Null return type at [createGetter](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleGetter.java#L241) so it will be generated as void method
3. [Not static modifier ](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleGetter.java#L202)

Looks like It can be reproduced with other annotation handlers.

**To Reproduce**
Case:
```
public enum EnumTest {
    @Getter
    AAA
}
```
Result:
```
Lombok annotation handler class lombok.eclipse.handlers.HandleGetter failed
java.lang.NullPointerException
at lombok.eclipse.handlers.EclipseHandlerUtil.isBoolean(EclipseHandlerUtil.java:1425)
at lombok.eclipse.handlers.HandleGetter.createGetterForField(HandleGetter.java:193)
at lombok.eclipse.handlers.HandleGetter.createGetterForFields(HandleGetter.java:164)
at lombok.eclipse.handlers.HandleGetter.handle(HandleGetter.java:153)
at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnField(TransformEclipseAST.java:245)
at lombok.eclipse.EclipseNode.traverse(EclipseNode.java:110)
```

**Expected behavior**
Javac handler works well in this case and generate method:
```
public static EnumTest getAAA() {
    return AAA;
}
```

**Version info:**
Platform Eclipse: 

-  Version: 2023-03 (4.27.0)
-  Build id: 20230309-1520
-  Lombok v1.18.26 "Envious Ferret" is installed

**Comment by yzy-1995** [comment]
you might have to create the getter methods manually for each enum constant.

**Comment by Rawi01** [comment]
Obviously lombok should not fail with an NPE and it is not that difficult to fix this but I don't get why you need a getter for an enum constant. It might be better to also remove the `javac` support for this.

**Comment by vladtimofeev000** [comment]
@Rawi01 , 

>  I don't get why you need a getter for an enum constant

Me too. I just want to sync `eclipse` and `javac` behaviors. Prevent NPE and remove the 'javac' support - will be nice.
