### ISSUE TITLE
[BUG] @Singular does not work on record class

### ISSUE THREAD

**Issue by blackdiz** [projectlombok/lombok#3435]
**Describe the bug**
`@Singular` added on a field of a record class is not processed properly.

**To Reproduce**
Having a following record class:
```
@Builder
public record GetCustomerOrderOutput(
    @Nullable String orderId,
    @Nullable Long date,
    @Nullable String currency,
    @Nullable Double amount,
    @Singular("addCustomField") List<CustomFieldOutput> customFields,
    @Singular("addItem") List<ItemOutput> items) {
}
```
When compiling I got a error indicating:
```
error: cannot find symbol
public record GetCustomerOrderOutput(@Nullable String orderId, @Nullable Long date, @Nullable String currency, @Nullable Double amount, @Singular("addCustomField") List<CustomFieldOutput> customFields, @Singular("addItem") List<ItemOutput> items) {
                                                                                                                                         ^
  symbol:   class Singular
  location: class GetCustomerOrderOutput
```
And the `@Singular` annotation remains in the compiled code:
```
public record GetCustomerOrderOutput(@Nullable String orderId, @Nullable Long date, @Nullable String currency, @Nullable Double amount, @Singular("addCustomField") List<CustomFieldOutput> customFields, @Singular("addItem") List<ItemOutput> items) {
}
```   

**Expected behavior**
The `@Singular` should be processed. The compiled code should not contain the `@Singular` annotation and add the `addCustomField` method.

**Version info (please complete the following information):**
 - Lombok version `1.8.26`
 - Platform `OpenJDK Runtime Environment Corretto-17.0.5.8.1 (build 17.0.5+8-LTS)`

**Additional context**

**Comment by Rawi01** [comment]
The remaining annotation problem was fixed in #3420. `@Singular` on records is supported since lombok 1.18.20
