### ISSUE TITLE
[FEATURE] Allow deliberate suppression of warnings when there is a default initializer value on a @Singular field for @Builder and @SuperBuilder

### ISSUE THREAD

**Issue by Steve973** [projectlombok/lombok#3441]
Please allow an annotation parameter for `@Singular` annotations when the field has a default initializer value.  While the intent may be to use a 'lomboked' class with a builder, there may also be cases where the class is instantiated via a default constructor, and we want to ensure default values.  In some cases, the warnings are very helpful.  In other cases, the default initializations are intentional, and the extra noise in the build output is unnecessary (or unwelcome).  The warning sates:

`@Builder will ignore the initializing expression entirely.  If you want the initializing expression to serve as default, add @Builder.Default.  If it is not supposed to be settable during building, make the field final.`

This appears to miss the case for `@Singular`, where the `@Builder` functionality might not be used when creating an instance.  In that case, it is perfectly acceptable to initialize the field.  We cannot use `@Singular` and `@Default` together, and making the field `final` probably breaks nearly every use case for the class.

Suggestion:
The Singular class could look like this:
```java
public @interface Singular {

  String value() default "";

  boolean ignoreNullCollections() default false;

  boolean ignoreInitializingExpression() default false;
}
```

This way, the intention to alert the developer of a likely-improper implementation will, by default, alert the user.  Where the developer has a valid reason to provide initialization, this will eliminate the warning, thereby cleaning up the build output and reducing false positives in tools that report build metrics that include warnings, etc.

If this goes against something important that I am failing to take into consideration, is there another way to address this use case?

**Comment by Steve973** [comment]
Bumping this because it seems like at least *somebody* should have looked at this by now.  Anybody interested?  If not, you can close this.  I have had it open for a half year at this point.

**Comment by rzwitserloot** [comment]
It's a lot more complicated than you think. For example, `String value()` wouldn't work - you'd need to stick a java expression into a string which we veto for being _horrible_.

I'm going to close it; if somebody comes up with a great way to do this, I'm sure it'll resurface.

**Comment by Steve973** [comment]
Why would you close it as complete if you're not going to do the work?  A
resolution indicating that you rejected it would be better.  I have to
admit that I'm disappointed in the response.
