### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Johnson0125** [projectlombok/lombok#3442]
**Describe the bug**
Could not working well if the model class **extends a hashmap**
the reason is because it's extends a hashmap of course

**To Reproduce**
Code, note: you can use your own json library
```java
@Data
public class Sample extends HashMap<String, Object> {
    private String name;
    private Long id;

    public static void main(String[] args) {
        String json = "{\"name\":\"fff\",\"id\":44}";
        Sample sample = JSON.parseObject(json, Sample.class);
        System.out.println(sample.getName() + "----" + sample.getId());
        System.out.println(JSON.toJSONString(sample));
    }
}
```

![image](https://github.com/projectlombok/lombok/assets/5418137/7943ed48-1e8a-44e3-9d5f-7469e5299d69)

**Expected behavior**
it could get the right value rather than null

**Version info (please complete the following information):**
 - Lombok version (both 1.18.26 and 1.18.20 will not working well)
 - Platform (idea jdk8 and jdk17)

**Additional context**

**Comment by dstango** [comment]
Looks like a problem with your JSON-library, as this does not reproduce the problem:

```java
@Data
public class Sample extends HashMap<String, Object> {
	private String name;
	private Long id;

	public static void main(String[] args) {
		Sample sample1 = new Sample();
		sample1.setId(5L);
		System.out.println(sample1.getId());

		Sample sample2 = new Sample();
		sample2.id = 5L;
		System.out.println(sample2.getId());

	}
}
```
Most likely the JSON-lib you're using will detect the class is a Map, and thus insert the values from your json-string via the put method ...

**Comment by Rawi01** [comment]
I agree with @dstango that this is a problem of your json library. The inline debug variable output in line 20 confirms that the map has a size of 2.

**Comment by Johnson0125** [comment]
**while i change the json library to jackson, it meets the same issues**
```java
       String json = "{\"name\":\"fff\",\"id\":44}";
        ObjectMapper om = new ObjectMapper();
        Sample result = om.readValue(json, Sample.class);
        System.out.println(result.getId()+"--"+result.getName());
        result.setName("name-jackson");
        System.out.println(result.getId()+"--"+result.getName());
```

![image](https://github.com/projectlombok/lombok/assets/5418137/9bc4c2e3-b311-4be7-8e57-ccdf08a03a55)

maybe the because the value comes from json?
@Rawi01 
@dstango

**Comment by dstango** [comment]
Please reread my first response and especially the last paragraph.

**Comment by Johnson0125** [comment]
thanks @dstango
