### ISSUE TITLE
[BUG] Lombok causes the javadoc task of Gradle to fail when including images in a doc-files folder

### ISSUE THREAD

**Issue by nlisker** [projectlombok/lombok#3446]
Create a Java gradle project with the following files:

build.gradle
```groovy
plugins {
    id 'application'
    id 'io.freefair.lombok' version '+'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(20)
    }
}

ext.lombokVersion = "1.18.28";
lombok {
	version = lombokVersion
}
```

Library.java
```java
package doctest;

import lombok.AccessLevel;
import lombok.experimental.FieldDefaults;

/**
 * Some text.
 * <p>
 * <img src="doc-files/PIC.svg" alt="some text">
 */
@FieldDefaults(level = AccessLevel.PRIVATE)
public class Library {

	/**
	 * Creates a library.
	 */
	public Library() {
	}
}
```

in the following project structure:

```
src/main/java
 - doctest
 - - Library.java
 - - doc-files
 - - - PIC.svg [any resouce]
build.gradle
```

The doc-files folder is what the javadoc tool uses to find external resources for the generated docs, it's not an arbitrarily chosen name.

Gradle is set to Gradle Version: 8.1.1

Run the `javadoc` task, the following error happens:
```
> Task :generateEffectiveLombokConfig UP-TO-DATE
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :delombok UP-TO-DATE

> Task :javadoc FAILED
error: Illegal package name: "C:\projectName\build\generated\sources\delombok\java\main\doctest\doc-files\PIC.svg"
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':javadoc'.
```

If you remove the `@FieldDefaults` annotation and the Lombok plugin and configuration from the gradle file (making it a simple Java project), the task finishes successfully.

**Comment by Rawi01** [comment]
This is not a lombok issue.

You used delombok to prepare the sources for javadoc generation. This creates a copy of all files in a new folder for generated sources. Javadoc is unable to resolve the relative path for the generated files because it the image does not get copied to that folder. I guess that you have to add some parameters to the javadoc task or move the image to the ressources folder.
