### ISSUE TITLE
[FEATURE] add javadoc to fields and props of a java record

### ISSUE THREAD

**Issue by nimo23** [projectlombok/lombok#3453]
**Describe the feature**

Imagine something like this:

```
/**
 * @param firstname   the firstname
 * @param surname     the surname
 * @param tasks       all tasks of the user
*/
public record User(String firstname, String surname, List<Taks> tasks){}
```
It would be nice if lombok could add the javadoc based on the constructor's javadoc. For example, when accessing `user.firstname()`, the javadoc defined in the constructor should be used. Is this possible?

Actually, lombok uses the javadoc defined in fields when we use getter/setter-methods generated by `@Getter/@Setter`. Something like this would be good for Java `record` as well.

**Comment by Rawi01** [comment]
If the javadoc tool or your IDE does not support something like this, I would recommend filling an issue in the appropriate issue tracker. There is no reason lombok should modify a record without a lombok annotation.

**Comment by Rawi01** [comment]
Adding comments is some kind of modification. Lombok can do that, yes, but shouldn't that be part of the java standard/IDE? 

According to [this stackoverflow post](https://stackoverflow.com/questions/61445534/how-to-document-java-record-parameters) it works in `javadoc` and IntelliJ. I doesn't work in eclipse for me too, only adding a comment at the record component itself seems to work (`record User(/** comment */ String name, ...)`).

Github only know open or closed as status but I added a label to the issue for you :smiley:
