### ISSUE TITLE
[FEATURE] add @RecordBuilder-Pattern to record

### ISSUE THREAD

**Issue by nimo23** [projectlombok/lombok#3454]
**Describe the feature**
Would be nice to add new builder annotations for java records, like those described in https://github.com/Randgalt/record-builder.

For example:

```
@RecordBuilder
public record Person(String name, int age);
```

would generate this:

```
record Person(String name, int age) {
     Person withName(String name) {
        return new Person(name, age);
    }
}
```

**Comment by janrieke** [comment]
That's `@With`, and it should work for records, too. Just put it on the fields/parameters of the record.

**Comment by Rawi01** [comment]
Thats already possible, there also is test case for that: 
https://github.com/projectlombok/lombok/blob/9e5e0c3803dd5e4306bb54b4976d1c03ec1a8ee2/test/transform/resource/before/WithOnRecordComponent.java#L1-L6
