### ISSUE TITLE
FEATURE: Fields annotations in @RequiredArgsConstructor

### ISSUE THREAD

**Issue by GeniusDP** [projectlombok/lombok#3459]
**Before submitting**
Please check our [wiki](https://github.com/projectlombok/lombok/wiki) because some feature requests are asked _a lot_ and there are good reasons (as explained on the wiki) why we can't (yet) implement them or why we won't implement them.
I have checked:)

**Describe the feature**
Well, I use Spring Framework for my every-day work and very often use `@RequiredArgsConstructor(or @AllArgsConstrcutor)` for bean creation. And typical service looks like this:

```
@Service
@RequiredArgsConstructor
class SomeService {
    
    private final DependencyBeanOne one;
    private final DependencyBeanTwo two;
    
    //... some methods
}
```

Imagine the situation, when we have several beans of DependencyBeanTwo type. Then we needda get rid of perfect lombok annotation and use plain constructor declaration to set `@Qualifier` annotation:

```
@Service
class SomeService {

    private final DependencyBeanOne one;
    private final DependencyBeanTwo two;

    public SomeService(
        DependencyBeanOne one,
        @Qualifier("theNeededOne")
        DependencyBeanTwo two
    ) {
        this.one = one;
        this.two = two;
    }
//... some methods
}
```
Or another case: using `@Lazy` annotation for injecting bean lazily. 
Sometimes number of dependencies reaches 10+ and such constructor looks owful.

Main proposal: could you, please implement `@RequiredArgsConstructor` annotation to generate constructor, which would take in account all the annotations placed upon fields and give us an opportunity to  replace the last block of code by the following one:
```
@Service
@RequiredArgsConstructor
class SomeService {

    private final DependencyBeanOne one;
    @Qualifier("theNeededOne")
    private final DependencyBeanTwo two;

//... some methods
}
```

From my point of view, it would be a perfect enhancement.

**Describe the target audience**
Java Backend Spring Framework developers ( at least, but not the last:) )

**Comment by Rawi01** [comment]
You can set a list of copyable annotations using the [configuration system](https://projectlombok.org/features/configuration) and the config key `lombok.copyableAnnotations`.

A general solution is not possible because lombok does not know how to handle all the different annotations out there. We tried that for nullable annotations but it is a lot of work to collect all the information to create and maintain this list.

**Comment by GeniusDP** [comment]
Ok, thnx
