### ISSUE TITLE
[BUG] @Embeddable data creation does not work with lombok's @Builder

### ISSUE THREAD

**Issue by nurmanbetovbekbolot** [projectlombok/lombok#3462]
**Describe the bug**
When an object is created with lombok's @Builder, the @Embedable created date does not work.

**To Reproduce**

Let's consider we have an entity Test. We want to do simple creation of Test object.
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Builder
@ToString
@Table(name = "test")
public class Test {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    @Embedded
    private Dates dates = new Dates();

//Embeddable Dates
@Embeddable
@Access(AccessType.PROPERTY)
@Getter
@Setter
public class Dates {

    @Column(name = "updated_date")
    @Temporal(TemporalType.TIMESTAMP)
    private LocalDateTime updatedDate;

    @Column(name = "created_date", updatable = false, nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private LocalDateTime createdDate;

    @PrePersist
    protected void onCreate() {
        createdDate = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedDate = LocalDateTime.now();
    }
}

        // not working
    
        public void createTest() {
            Test test = Test.builder()
                    .build();
             create(test);

           //createdDate is null
    }
    
        // working

        public void createTest() {
            Test test = new Test();
            create(test);
            
            //createdDate successfully persisted!
    }

**Comment by Rawi01** [comment]
You can use `@Builder.Default` for this.
