### ISSUE TITLE
[BUG] @Jacksonized SuperBuilder not working with @JsonIdentityInfo

### ISSUE THREAD

**Issue by ilmirons** [projectlombok/lombok#3464]
Jacksonized SuperBuilder does not work with JsonIdentityInfo annotation. The injected builder is cached instead of the actual instance when deserializing an object from an id. 

Here is the test that made me realize the bug:

```java

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIdentityReference;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import lombok.extern.jackson.Jacksonized;

import org.junit.jupiter.api.Test;

class JacksonizedTest {

  @JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
  @JsonSubTypes({@JsonSubTypes.Type(value = Item.class, name = "item")})
  private interface ItemIfc {

    @JsonIdentityReference
    String getId();
    
    void setId(String id);

  }
  
  @Jacksonized
  @SuperBuilder
  private static class Item implements ItemIfc {
    @JsonIdentityReference @Getter @Setter String id;
  }

  @Data
  private static class Wrapper {
    @JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
    List<ItemIfc> wrapped;
  }

  @Test
  @DisplayName("Use compact form for storing items")
  void compactDeserialize() throws JsonProcessingException {
    var input = "{ \"wrapped\": [{ \"@type\": \"item\", \"id\": \"id1\" }, \"id1\"] }";
    Wrapper w = new ObjectMapper().readValue(input, Wrapper.class);
    var wList = w.getWrapped();
    assertNotNull(wList.get(0));

    // next assert fails as
    // Expected : JacksonizedTest$Item@4c60d6e9
    // Actual   : JacksonizedTest.Item.ItemBuilder(id=id1)

    assertSame(wList.get(0), wList.get(1));
  }

```

**Expected behavior**
Same object should be returned when deserializing reference.

**Version info (please complete the following information):**

 - lombok 1.18.28
 - java -version 
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

**Additional context**
Error changes if a hierarchy of classes is not involved: In that case a new instance of the class is returned, yet is not the same object.
There is a related issue on Jackson repo https://github.com/FasterXML/jackson-databind/issues/1496

**Comment by janrieke** [comment]
I don't see what lombok can do better here if this does not work in Jackson in the first place. At least this is how I understand the issue at https://github.com/FasterXML/jackson-databind/issues/1496.

If my assumption is wrong, it would be great if you could post a working example of what `@Jacksonized @(Super)Builder` should generate. As the issue seems to be the same for `@Builder` and `@SuperBuilder`, I suggest you use `@Builder`, as the delomboked code is easier to understand and tweak.

**Comment by gotounix** [comment]
Don't use `@Data`, because `@ToString` makes it not working.

Using `@Getter` and `@Setter` replace `@Data`.

Related https://github.com/projectlombok/lombok/issues/3523

**Comment by rzwitserloot** [comment]
closing due to no further feedback on janrieke's query.
