### ISSUE TITLE
[BUG] The topic attribute of @Slf4j will cause log.isDebugEnabled() to fail

### ISSUE THREAD

**Issue by tang226** [projectlombok/lombok#3466]
**Describe the bug**
Using the annotation @Slf4j(topic = "myClass") on the entity class will cause log.isDebugEnabled() to always return false

**To Reproduce**
```java
package com.example;

import lombok.extern.slf4j.Slf4j;

@Slf4j(topic = "myClass")
public class MyClass {

    public void myMethod() {
        if (log.isDebugEnabled()) {
            log.debug("Debug message");
        }
    }

    public static void main(String[] args) {
        new MyClass().myMethod();
    }
}
```

logback.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">

    <property name="CUSTOM_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}-%msg%n"/>
    <!-- 控制台输出 -->
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>${CUSTOM_LOG_PATTERN}</pattern>
        </encoder>
    </appender>

    <logger name="com.example" level="debug"/>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
```

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>slf4jtest</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.6</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.6</version>
        </dependency>
    </dependencies>
</project>
```

**Expected behavior**
I just want to enable the debug log for the com.example package and set the topic attribute of @Slf4j

**Version info (please complete the following information):**
 - Lombok version 1.18.24
 - Platform IDEA 2023
 - logback-core 1.2.6
 - logback-classic 1.2.6

**Comment by rspilker** [comment]
Can you run `delombok` on the code and see if the generated code is what you would have types yourself? 

I'm not an expert on Slf4J, but could it be that you would have to specify the topic in the `logback.xml` as well?

**Comment by tang226** [comment]
@rspilker thanks！I added the corresponding topic in logback.xml, and then re-run the project to take effect!

<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="false">

    <property name="CUSTOM_LOG_PATTERN" value="%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50}-%msg%n"/>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>${CUSTOM_LOG_PATTERN}</pattern>
        </encoder>
    </appender>


    <logger name="myClass" level="debug"/>

    <root level="INFO">
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>
