### ISSUE TITLE
[FEATURE] @Factory annotation, Google guice addition.

### ISSUE THREAD

**Issue by marlester-dev** [projectlombok/lombok#3469]
**Before submitting**
Please check our [wiki](https://github.com/projectlombok/lombok/wiki) because some feature requests are asked _a lot_ and there are good reasons (as explained on the wiki) why we can't (yet) implement them or why we won't implement them.

I saw that.

**Describe the feature**
A clear and concise description of what the feature request/enhancement is. What is the goal of adding this feature request? This should include 2 java snippets: One 'lomboked' version, which is java code with (for example) an annotation that is short and boilerplate free, and a second snippet that shows precisely what lombok will do under the hood. Lombok can only turn java code that is valid java syntax into different java code.

Creating factories can be hard, to create a factory you needed to do something like this:
```java
public interface PlayerFactory {
    Player create(String name);
}
```
```java
public class Player {
    @AssistedInject
    public Player(@Assisted String name, Main main) {

    }
}
```

Here's my suggestion on how to fix it with `@Factory`:

```java
//auto generated code:
public interface PlayerLombokFactory {
    PlayerLombok create(String name);
}
```
```java
@Factory
public class PlayerLombok {
    @AssistedInject
    public PlayerLombok(@Assisted String name, Main main) {

    }
}
```

**Describe the target audience**
This will be beneficial for programmers that use Google Guice dependency injection with AssistedInject addition and create factories:
- [guice](https://github.com/google/guice)
- [assistedinject](https://github.com/google/guice/wiki/AssistedInject)

**Additional context**
This is a very specific one, but will be helpful because it reduces boilerplate code. I would like to see it.

**Comment by Rawi01** [comment]
I cannot see why lombok should be necessary for this feature. Generating a new class/interface is something that can be done with a regular annotation processor.
