### ISSUE TITLE
[FEATURE] Ability to access any code elements as strings constants with me having to define each string.. that make compiler more powerful

### ISSUE THREAD

**Issue by nagkumar** [projectlombok/lombok#3471]
```
@RestController
public class RateLimitController
{
    private static final String STUDENT_RATE_LIMITER_API = "studentRateLimiterApi";
    private static final String RATE_LIMITING_FALLBACK = "rateLimitingFallback";

    @GetMapping(value = "/student/{aID}")
    @RateLimiter(name = STUDENT_RATE_LIMITER_API, fallbackMethod = RATE_LIMITING_FALLBACK)
    public final ResponseEntity getStudentById(@PathVariable int aID)
    {
	return ResponseEntity.ok("Details requested for " + aID);
    }

    public final ResponseEntity rateLimitingFallback(final int aID, final RequestNotPermitted aRequestNotPermitted)
    {
	final HttpHeaders lHttpHeaders = new HttpHeaders();
	// retry after one second
	lHttpHeaders.set("Retry-After", "60s");

	// send retry header
	return ResponseEntity.status(HttpStatus.TOO_MANY_REQUESTS)
			     .headers(lHttpHeaders)
			     .body("Too Many Requests - Retry After 1 Minute");
    }
}
```

In above code if change method rateLimitingFallback name, then my compiler would fail to recognise it.. is it possible to refer method name automatically in annotations or for any other reason so that I don't have to use this method i.e. defining

`    private static final String RATE_LIMITING_FALLBACK = "rateLimitingFallback";
`
and trusting that method name will not change at all etc..

such strong-based linking is not refactoring-friendly.. I belive lombok can define constants automatically with say if I have annotation such as

```
@RestController
@Stringify
public class RateLimitController
{
    public final ResponseEntity rateLimitingFallback(final int aID, final RequestNotPermitted aRequestNotPermitted)
    {
}
}
```

then I must given constants available such as

RateLimitController.className
RateLimitController.method.rateLimitingFallback

etc..

it is just a sample to give the idea of how make most of the code strings are available as string constants..

**Comment by Rawi01** [comment]
This is already possible for fields using `@FieldNameConstants`. A `@MethodNameConstants` was propsed in #1944 but rejected because of method overloads. As you presented an additional use case @rzwitserloot might reconsider this. I'm closing this anyway and he can reopen it if he thinks it fulfils all the requirements for a new feature.
