### ISSUE TITLE
[FEATURE] @Delegate.Override or automatic exclusion existing methods from @Delegate

### ISSUE THREAD

**Issue by ancap-kun** [projectlombok/lombok#3495]
**Describe the feature**
Excluding methods from `@Delegate` is ugly, you have to create additional class to do that. It can become less ugly, if `@Delegate` will not create methods, that already declared. If there some problems with this, then will not create methods that already declared and marked with `@Delegate.Override`. 

**Describe the target audience**
Every programmer that uses `@Delegate`.

**Comment by Rawi01** [comment]
Lombok already skips methods that are implemented and does not override/replace these methods.

**Comment by ancap-kun** [comment]
Idea plugin bug confused me. It says that it's impossible.
