### ISSUE TITLE
[FEATURE] Exclude ToString from @Builder Annotation

### ISSUE THREAD

**Issue by ShubamVirdi** [projectlombok/lombok#3500]
Currently 
@Builder Annotation includes ToString along with it. can we remove it from builder by adding exclusion to it.

**Comment by rzwitserloot** [comment]
I have no idea why you would want this. The odds we'd accept this feature is less than 1% - we don't want our annotations to grow 50 parameters, and it feels like, if `@Builder(omitToString = true)` is a feature, then it feels like about 50 other exotic, hard-to-come-up-with-a-use-case options should also be a thing, and that means `@Builder` has 50 parameters, and that is worse than the current situation.

I'll re-open this if you bowl us over with a whopper of a use-case.
