### ISSUE TITLE
[FEATURE] Swap underscored properties with non-underscored

### ISSUE THREAD

**Issue by ancap-kun** [projectlombok/lombok#3507]
**Describe the feature**
Now lombok uses trick to implement properties that receive annotations. Placeholder-properties looks like normal properties, and phantom properties, that actually used, are underscored at the end. It wil be look better if we can use normal properties and leave underscored ones at annotation sources.

It will be breaking change, but since lombok used only in compile time and non-underscored properties previously wasn't used, nothing bad will happen because of it, everyone will should just remove underscores. Also it can be implemented without breaking old code, just make placeholder underscored twice and leave old way to do this with one underscore as deprecated option.

**Comment by rzwitserloot** [comment]
We do the trick for a good reason. This issue tracker is not the place for political statements.
