### ISSUE TITLE
[BUG] Wrong problem with printing class name using @Data toString()

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [projectlombok/lombok#3522]
**Describe the bug**
Regarding the `toString()` method exception of the `@Data` annotation, do not fix the string when printing the class name. This will result in that when using `@Data` in an abstract parent class, its subclass cannot obtain the correct instance object when printing the this keyword name

**To Reproduce**
```Java
public class Main {
    private static A a;
    public static void main(String[] args) {
        a = new AA();
        a.say();
        System.out.println("I hope it is: "+a.getClass()); // I hope it is: class com.w.application.AA
    }
}
@Data
abstract class A {
    abstract void say();
}
class AA extends A {
    @Override
    void say() {
        System.out.println("I got it: "+this); // I got it: A()
    }
}
```
**Expected behavior**
`toSting()` prints the correct instance object name
```java
public class Main {
    private static A a;
    public static void main(String[] args) {
        a = new AA();
        a.say();
        System.out.println("I hope it is: "+a.getClass()); // I hope it is: class com.w.application.AA
    }
}

abstract class A {
    abstract void say();

    @Override
    public String toString() {
        return this.getClass().getName();
    }
}
 class AA extends A {
    @Override
    void say() {
        System.out.println("I got it: "+this); // I got it: com.w.application.AA
    }
 }

```
**Version info (please complete the following information):**
 - Lombok version 1.18.30 
 - Platform javac 1.8.0_171

**Additional context**
This kind of exception will cause me to have a wrong understanding of Java `this` keyword.

**Comment by Rawi01** [comment]
If you use `this` and add it to a `String` java will call the `toString` method to convert the object into a `String`. You only added a `toString` method to the parent class using `@Data` and thats the method that gets called. This one prints the name of the implementing class as [documented](https://projectlombok.org/features/ToString). To print the name of the subclass you also have to add `@ToString` to it.
