### ISSUE TITLE
[BUG] `@ToString` will make `@JsonIgnore` not working.

### ISSUE THREAD

**Issue by gotounix** [projectlombok/lombok#3523]
**Describe the bug**

While using `@ToString` or `@Data` in entity class, `@JsonIgnore` and other annotations will become invalid.

**To Reproduce**

```
@Data
@Entity
public class User {
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "user_role",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private List<Role> roles;
}

@Data
@Entity
public class Role {
    @JsonIgnore  // Not Working !!!
    @ManyToMany(mappedBy = "roles")
    List<User> users;
}
```

**Expected behavior**

Ignore `users` field when serializing roles.

**Version info (please complete the following information):**
 - Lombok version: 1.18.30
 - Platform: java 21
 - Spring Boot: 3.1.4
 - Jackson: 2.15.2

**Comment by Rawi01** [comment]
Why should `@ToString` change the behaviour of jackson? Adding `@ToString`/`@EqualsAndHashcode` creates an infinte loop in your example but that is unrelated to jackson. Please explain why you think this is a lombok problem.

**Comment by victorwss** [comment]
"now working" - I think that you meant "not working".

**Comment by rzwitserloot** [comment]
Closing for lack of detail or misunderstanding of the feature. Not sure which one.

If you still feel this is an issue, we need a detailed formula for reproducing the issue. Something like: "Take this lombok code, run it with these dependencies (including precise info on how to install them. For example, maven Group/artifact/version IDs), compile it with these commands, then run it like so. This exception occurs; I expected instead that this sysout would print that".
