### ISSUE TITLE
[FEATURE] Additional @With implementation which accepts a function T → T to make nested updates less verbose

### ISSUE THREAD

**Issue by chriskiehl** [projectlombok/lombok#3524]
**Describe the feature**

Motivating problem: making complex updates using Withers is painful due to the need to manually drill data across each level of nesting. e.g. 

```java
@With record Foo(Bar bar){};
@With record Bar(Baz baz){};
@With record Baz(Integer version){};

foo.withBar(   
    // at each level of nesting 
    foo.getBar().withBaz(
          // You've got to drag the outer context down    
          foo.getBar().getBaz().withVersion(
               // If your next value is computed from the current 
               // one it is especially painful
               foo.getBar().getBaz().getVersion() + 1
        )    
    )
);
```

Accepting a function automatically carries that context for you removing a lot of the visual noise and need for repeatedly traversing the same object. 

```java
foo.withBar(bar -> bar.withBaz(baz -> baz.withName(baz.getversion() + 1))); 
```

**Without Lombok:** 

```java
record Foo(Bar bar){
    public Foo withBar(Bar bar) {
        return new Foo(bar);
    }
    public Foo withBar(Function<Bar, Bar> f) {
        return this.withBar(f.apply(bar()));
    }
};

record Bar(Baz baz){
    public Bar withBaz(Baz baz) {
        return new Bar(baz);
    }
    public Bar withBaz(Function<Baz, Baz> f) {
        return this.withBaz(f.apply(baz()));
    }
};

record Baz(Integer version){
    public Baz withVersion(Integer version) {
        return new Baz(version);
    }
    public Baz withVersion(Function<Integer, Integer> f) {
        return this.withVersion(f.apply(version()));
    }
};
```

**With Lombok**

```
@With record Foo(Bar bar){};
@With record Bar(Baz baz){};
@With record Baz(String name){};
``` 

**Describe the target audience**

Any programmers using records or other immutable data constructs in Java. 

**Additional context**

None.

**Comment by Rawi01** [comment]
[`@WithBy`](https://projectlombok.org/api/lombok/experimental/WithBy)?

**Comment by chriskiehl** [comment]
@Rawi01 oh -- hey! Yeah, that's exactly what I'm after! Any background on why its not documented the experiments section of the website? Seems super useful to my eye. 

Thanks for pointing me towards it. 👍

**Comment by rzwitserloot** [comment]
@chriskiehl Because @rspilker came up with this like 8 years ago and for whatever reason 'just add the docs' has remained on his plate for, like, 5 years. It's been in lombok for a very long time at this point. Roel, ffs mate, write them docs already :)
