### ISSUE TITLE
support static field nameof

### ISSUE THREAD

**Issue by Silentdoer** [projectlombok/lombok#3528]
like title

**Comment by rzwitserloot** [comment]
Feature requests should include a precise 'this is what I would write' and then 'this is what lombok would turn that into (this would be vanilla java)". "like title" is inappropriate, as is throwing flyby feature requests at an open source project without scanning for debates and issues about it first.

Any further low-effort issues will result in a ban, @Silentdoer. I'd rather spend my lombok time writing features than dealing with issues like these.
