### ISSUE TITLE
[BUG] UI Error when a generated Field is used on annotation

### ISSUE THREAD

**Issue by c-koell** [projectlombok/lombok#3529]
**Describe the bug**
We are using lombok 1.18.30 within eclipse 2023-09.

We use the @FieldNameConstants Annotation a InnerClass with static final Fields will be generated.

If we use the static final Fields on a annotation there is no Compile Error but we see a Error on the Classs itself
![Eclipse IDE](https://github.com/projectlombok/lombok/assets/4134346/306dd202-17cd-4ff7-9b7f-3bf46eaccf77)

**To Reproduce**
The Problems View is empty, and the code works if you run it ...

You will find a sample eclipse project here
[Sample-Project.zip](https://github.com/eclipse-jdt/eclipse.jdt.ui/files/13043088/Sample-Project.zip)

I have also created a issue in jdt-ui https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/865 but a project member thought it is maybe a problem of lombok.

Thanks for any help.

**Comment by rspilker** [comment]
Does using a fully qualified name fix the problem? For example: `com.example.Person.Fields.id`. If it does, then this is a known probleem, and not something we can easily fix.

**Comment by c-koell** [comment]
Hi @rspilker !

Also with full qualified name the problem exists :-(

thanks for your help !

**Comment by Rawi01** [comment]
Can reproduce this in eclipse, two files are required. I have already found out that at some point the initializer of the generated field gets replaced with `null`.

**Comment by c-koell** [comment]
@Rawi01 do you have some plan how to fix it ?

**Comment by Rawi01** [comment]
Yes, I have almost finished my patch for this problem

**Comment by c-koell** [comment]
@Rawi01 that sounds great ! I would also test your patch if you like.

**Comment by c-koell** [comment]
@Rawi01 do you know when this fix will be available ? Thanks !

**Comment by c-koell** [comment]
@Rawi01 any news here ? It would be great if we could have some fix for it .. thanks lot !

**Comment by Rawi01** [comment]
Oh, I forgot to create a pull request for the changes, sorry.

**Comment by c-koell** [comment]
@Rawi01 thank you for the fix ! How often will the Snapshot be build so that i can try it ?

**Comment by rzwitserloot** [comment]
@c-koell Anytime we do something even remotely significant. Possibly tonight (thursday evening), @rspilker and I usually find some time to do some work.

**Comment by c-koell** [comment]
@rzwitserloot the edge-release page says always ```version: 1.18.31 (2024-01-12 00:13:12 UTC)```
should it contain that fix ?

**Comment by rspilker** [comment]
This is part of the latest [edge release](https://projectlombok.org/download-edge), all feedback is welcome.

**Comment by getzabelz** [comment]
Now It's even worse to me, everytime I change a java class file the errors for the constants comes back

Only workaround I found is everytime i change a class file to do a maven package

**Comment by c-koell** [comment]
@getzabelz i see no more problems .. that's interesting that you have now more problems ..

**Comment by Rawi01** [comment]
@getzabelz Can you share a full example and also check if there is an error in your eclipse error log?

**Comment by getzabelz** [comment]
@Rawi01 
> @getzabelz Can you share a full example and also check if there is an error in your eclipse error log?

Checked eclipse logs and I don't see anything related to Lombok. I've been doing tests in a fresh setup and It seems that It breaks whenever I use QueryDSL with Lombok and @FieldNameConstants, could it be a conflict in between processors? I can't find any information or workaround, anyone got any clue?
