### ISSUE TITLE
[BUG] Lombok does not generate code when invoked via `javac` using JDK 22.

### ISSUE THREAD

**Issue by sageserpent-open** [projectlombok/lombok#3533]
**Describe the bug**

Lombok fails to generate code when run as part of `javac` compilation using JDK 22.

**To Reproduce**

(Performed under OS/X, Sonoma 14.1)

1. Install JDK 20 and JDK 22. Verify installations with: `/usr/libexec/java_home -V`.

2. Clone repository: https://github.com/sageserpent-open/americium
Remote: git@github.com:sageserpent-open/americium.git

3. Checkout minimised example on branch `lombok-jdk-22-bug`; this has a single Java file `./src/main/java/com/sageserpent/americium/java/OptionalLimits.java`.

5. Make a throwaway output directory `cabbages`: `mkdir cabbages` in the top-level of the working tree.

6. Select JDK 20 with `export JAVA_HOME=`/usr/libexec/java_home -v20`.

7. Invoke Java compiler with `javac -d cabbages -cp <location of Lombok JAR>/lombok-1.18.30.jar  ./src/main/java/com/sageserpent/americium/java/OptionalLimits.java`

8. Verify correct compilation: `echo $?`, this yields 0.

9. Select JDK 22 with `export JAVA_HOME=`/usr/libexec/java_home -v22`.

10. Again, invoke Java compiler with `javac -d cabbages -cp <location of Lombok JAR>/lombok-1.18.30.jar  ./src/main/java/com/sageserpent/americium/java/OptionalLimits.java`.

This yields an error:

```
./src/main/java/com/sageserpent/americium/java/OptionalLimits.java
./src/main/java/com/sageserpent/americium/java/OptionalLimits.java:9: error: cannot find symbol
            OptionalLimits.builder().build();
                          ^
  symbol:   method builder()
  location: class OptionalLimits
./src/main/java/com/sageserpent/americium/java/OptionalLimits.java:25: error: cannot find symbol
        return builder()
               ^
  symbol:   method builder()
  location: class OptionalLimits
2 errors
```

8. Verify incorrect compilation: `echo $?`, this yields 1.

**Expected behavior**

The behaviour when running under JDK 22 should  be the same as when running under JDK 20, namely a correct compilation.

**Version info (please complete the following information):**
 - Lombok version: 1.18.30
 - Platform javac, version 20.0.1 under JDK 20 and 22-ea under JDK 22 (currently early access).

**Additional context**
Raised as a result of tickets: https://github.com/sageserpent-open/americium/issues/67 and https://github.com/sbt/sbt/issues/7421.

Also, running the `delombok` task works **correctly** under both JDKs:

```
/usr/libexec/java_home -v20 --exec java -jar ~/Downloads/lombok.jar delombok -p src/main/java/com/sageserpent/americium/java/OptionalLimits.java > delomboked_jdk_20

/usr/libexec/java_home -v20 --exec java -jar ~/Downloads/lombok.jar delombok -p src/main/java/com/sageserpent/americium/java/OptionalLimits.java > delomboked_jdk_22

diff delomboked_jdk_2*

(Only difference is generation time).

fgrep builder < delomboked_jdk_20

    public static OptionalLimits defaults = OptionalLimits.builder().build();
        return builder().complexity(complexity).shrinkageAttempts(shrinkageAttempts).build();
    public static OptionalLimits.OptionalLimitsBuilder builder() {

fgrep builder < delomboked_jdk_22

    public static OptionalLimits defaults = OptionalLimits.builder().build();
        return builder().complexity(complexity).shrinkageAttempts(shrinkageAttempts).build();
    public static OptionalLimits.OptionalLimitsBuilder builder() {
```

So the code transformation is the same under both JDKs.

I should add that as per the other tickets, I have successfully worked around this by excising some deprecated code early on, but felt it worth reporting as an FYI; it is not urgent for me right now. 😄

**Comment by estekhin** [comment]
`@RequiredArgsConstructor` generates constructor without any parameters.

**Comment by alison-gravley** [comment]
Is there any potential timeline for Java 22 compatibility, in the edge snapshots? Java 22 releases in 2 months and we are using Panama/Foreign Function & Memory features that will be in the full release. Currently, we are still using Java 21 with enable preview turned on.

**Comment by Rawi01** [comment]
Works for me

[jdk22.mov](https://github.com/projectlombok/lombok/assets/5850477/1d15fea6-de81-4c12-90f9-5a2ce9b4e6b1)

**Comment by sageserpent-open** [comment]
Confirmed it's compiling correctly with Lombok from https://projectlombok.org/download-edge (I couldn't see the Lombok version in the video above).

@rzwitserloot:  That's a reasonable position to take. 😄 

Thanks all, for taking a look.

**Comment by alison-gravley** [comment]
> Confirmed it's compiling correctly with Lombok from https://projectlombok.org/download-edge (I couldn't see the Lombok version in the video above).
> 
> @rzwitserloot: That's a reasonable position to take. 😄
> 
> Thanks all, for taking a look.

I must have done something wrong. I definitely tried the edge release, but let me give it another shot today. If I run into a different problem, I will update this with more info.

**Comment by alison-gravley** [comment]
I had to fix some other things, but I got the compilation error down to sneaky throws. Once I removed all of those, I was able to compile and run.

`post-compiler 'lombok.bytecode.SneakyThrowsRemover' caused an exception: java.lang.IllegalArgumentException: Unsupported class file major version 66`

**Comment by estekhin** [comment]
> edge release already supports it. We'll release that in a stable release _before_ JDK22GA. Until then, hey, you're using a beta of JDK22, you can use a beta of lombok.

Please publish stable release sooner than later.

I can work with custom repo and edge/snapshot releases on my machine, but i can't (easily) add a custom repo to CI builds due to "reasons".
