### ISSUE TITLE
Enhancement Request: Support Including Method Results in @ToString’s ‘of’ Attribute

### ISSUE THREAD

**Issue by modernmsh** [projectlombok/lombok#3555]
Dear Lombok Team,

I hope this message finds you well. I would like to suggest a new feature for Lombok that would enhance the functionality of the @ToString annotation.

Currently, the of attribute in @ToString allows users to specify the fields they want to include in the generated @toString() method. However, it does not support including the results of methods.

Here’s an example scenario to illustrate the use case:

@ToString(of = {"cardNumber", "isGroupTransfer", "mask()"})
public class GetAccountTransactionsResultItem {

    private Double amount;
    private Double balance;
    private String cardNumber;
    private String description;
    private String fromAccountNumber;
    private String iban;
    private String identifier;
    @Builder.Default
    private Boolean isGroupTransfer = Boolean.TRUE;

    private String mask() {
        return HelperUtil.maskAccountNumber(this.accountNumber);
    }

}

In the above example, I would like to include the result of the mask() method in the @toString() output. However, currently, Lombok only supports including fields with the of attribute.

Therefore, my feature request is to extend the functionality of @ToString and allow users to include method results in the of attribute. This enhancement would provide more flexibility and customization options when generating the @toString() output.

Thank you for considering this feature request. I believe it would greatly benefit the Lombok community by making the @ToString annotation even more powerful and versatile.

Best regards,
Mohammad Shahbandloo

Email: [Mohammadsh_315@outlook.com]

**Comment by rspilker** [comment]
You can include the result of a method by annotating it with `@ToString.Include(name = "foo")`. This can both be used to implement an override of the default field value rendering, and to add a new "field".

We might want to document this behavior better.
