### ISSUE TITLE
[FEATURE] make lombok.val deprecated

### ISSUE THREAD

**Issue by hgschwibbe** [projectlombok/lombok#3557]
**Describe the feature**
Since Java 10 introduced var, lombok.val is obsolete for local variables.

Please mark it for deprecation and remove it afterwards.

See also the OpenJDK FAQ why they introduced a var and not Scalas val for local variables:
https://openjdk.org/projects/amber/guides/lvti-faq#Q3

Quote:
"Java allows the use of var only for local variables, not for fields. Immutability is much more significant for fields, whereas immutable local variables are comparatively rarely used."

**Comment by magicprinc** [comment]
Please, don't!!!

I use `val` often than `var`.

You can disable it in your projects using lombok.config

**Comment by hgschwibbe** [comment]
No problem, if val has been used so much, the most IDEs can search and replace.

**Comment by magicprinc** [comment]
val must stay

The whole Project Lombok are heretics.

True Java developers must write their getters and setters.

**Comment by hgschwibbe** [comment]
Please consider the new Feature Lombok introduced with 1.18.22:
![Lombok-Feature](https://github.com/projectlombok/lombok/assets/1725648/64be1ffe-3a35-4799-898a-abe14e294524)

**Comment by magicprinc** [comment]
An example from your link
`final var person = new Person();`
Every time someone writes such code, a fairy dies.

We have a problem in Java (the dark side of stability): don't extend the language at all.
Project Lombok has this issue too, BTW.

**Comment by hgschwibbe** [comment]
In 99,99% of the use cases you write:
`var person = new Person()` instead of `val person = new Person()`

Only in 0.01 % you need immutability where you write `final var`.

And there are better frameworks for immutability, e.g.: 
[Immutables](https://immutables.github.io/)

**Comment by magicprinc** [comment]
About https://immutables.github.io/

Lombok and JDK's records are enough for me.
I like val, but "I’m not really a welder" 😅

**Comment by hgschwibbe** [comment]
Its a little bit off topic, but Lombok vs JDK's records?

JDK records can only be used in combination with Lombok `@Builder ` or something similar.
Because a constructor with more than three parameters is a code smell.

**Comment by Rawi01** [comment]
Lombok still supports Java 6 and Java 8. Both versions do not have nativ support for `var` and you cannot simply search and replace it. `val` is still useful in modern java versions because you it allows you skip the `final` keyword. Whether this is useful for you or not is a another story, but if you think that it should not be used in your project, you can disable it in your config file.

**Comment by hgschwibbe** [comment]
Archaeologists and historians who still use Java 6 have no problems using a historical Lombok version.

A modern framework should not carry historical load around.

It should be deactivated in the config by default, lovers could activate it actively in the config.

**Comment by rspilker** [comment]
Thanks for sharing your opinion. 

By replacing `val` with `final var` in modern compilers, I think we now have a nice balance between supporting both developers that can use the latest versions while helping this that for some reason still need to use old technology.

On a different note, in my opinion the JDK should have added `val` next to `var`.
