### ISSUE TITLE
[BUG] Data Fields Not set data Properly

### ISSUE THREAD

**Issue by insane51** [projectlombok/lombok#3566]
**Describe the bug**
When making the variable name like 'aName,' 'A,' 'Name,' it creates an issue and is unable to set the variable value. In other cases, like when the variable name is 'user,' 'userName,' 'u,' it will work fine.

**To Reproduce**
1.Make an entity User(id,uName,city).
2.Add a controller for Post request and post data in request body.
3.Receive data direct in User object from request(@RequestBody User user).
4. Now Print or return the same data to see different results.
5. Expected you receive some of names as null.

**Version info (please complete the following information):**
 - Lombok version = 1.18.30
 - Platform (Intellij IDEA)
**Additional context**
Trial code : https://github.com/insane51/lombok-bug.git

**Comment by bhavesh1208** [comment]
I understand your explanation. but can you make it clear weather this happens all the time or alternatively, What I am trying to understand is does it happen with a specific type of naming or only a specific name?

**Comment by bhavesh1208** [comment]
> **Describe the bug** When making the variable name like 'aName,' 'A,' 'Name,' it creates an issue and is unable to set the variable value. In other cases, like when the variable name is 'user,' 'userName,' 'u,' it will work fine.
> 
> **To Reproduce** 1.Make an entity User(id,uName,city). 2.Add a controller for Post request and post data in request body. 3.Receive data direct in User object from request(@requestbody User user). 4. Now Print or return the same data to see different results. 5. Expected you receive some of names as null.
> 
> **Version info (please complete the following information):**
> 
> * Lombok version = 1.18.30
> * Platform (Intellij IDEA)
>   **Additional context**
>   Trial code : https://github.com/insane51/lombok-bug.git

Hi,
  The bug actually is that when you have a uppercase right after single lowercase letter in name, the getter and setter is generated as follows  : 
  parameter name : uName
  getter : getUName()
  setter : setUName()

but the compiler is not recognising this as default getter and setter 
what the compiler actually recognises is 
getter : getuName()
setter : setuName()

and this are the getter and setter that u normally get if you use a Ide getter and setter generator. hence we have to consider this as a special case and generate appropriate getter and setter according to compiler recognition standards.

**Comment by janrieke** [comment]
Use [lombok.accessors.capitalization = beanspec](https://projectlombok.org/features/GetterSetter#supported-configuration-keys) in your lombok.config (available since lombok v1.18.24).
