### ISSUE TITLE
[FEATURE] @Retention(RetentionPolicy.RUNTIME) not allow for onParam and onMethod

### ISSUE THREAD

**Issue by liam-kincaid** [projectlombok/lombok#3576]
During my test redaction, i will may use also annotation of retension policy type SOURCE or RUNTIME, ex:
- @NotBlank
- @PodamIntValue

Here is an TGZ who explain the issue.
This sample is just a immutable entity with his builder (use of custom hibernate validation build method)
[sample-1.0.0.tar.gz](https://github.com/projectlombok/lombok/files/13800614/sample-1.0.0.tar.gz)

May we have some evolution on the point ?

**Comment by rzwitserloot** [comment]
This is too low quality - your question is too vague, insufficient effort has been done to explain it. If I don't know what you're on about within about 30 seconds, I won't read any further. I definitely am not going to download some random tarball. Whatever's in there - format it nicely and put it directly in the issue.
