### ISSUE TITLE
[FEATURE] Lombok 1.18.30 still accesses JDK internal APIs

### ISSUE THREAD

**Issue by tudousitang** [projectlombok/lombok#3582]
We're trying to upgrade our maven project to Java 17. In the `pom.xml` file, we have set the latest lombok version dependency as shown below:
```
<dependency>
       <groupId>org.projectlombok</groupId>
       <artifactId>lombok</artifactId>
       <version>1.18.30</version>
</dependency>
```
We can build and compile our project using Java 17 successfully. However, when we use `jdeps` to analyze the dependency, we noticed that lombok code still uses some JDK internal APIs, see below:
```
lombok.javac.apt                -> com.sun.tools.javac.processing            JDK removed internal API
lombok.javac.apt                -> com.sun.tools.javac.util                   JDK removed internal API
lombok.launch                   -> sun.misc                                JDK removed internal API
```
Could lombok code make an enhancement to upgrade the dependencies that do not use these encapsulated JDK internal APIs? Thank you.

**Comment by Rawi01** [comment]
No, we cannot remove the references because thats how lombok works but you can do that by setting the scope of the dependency to `provided` or mark the dependency as optional. [(Documentation)](https://projectlombok.org/setup/maven)

**Comment by rzwitserloot** [comment]
@tudousitang wrote:

> Could lombok code make an enhancement to upgrade the dependencies that do not use these encapsulated JDK internal APIs? Thank you.

You're misreading the report from your tools. It's not that lombok depends on some library that then depends on javac internals. Lombok _itself_ depends on them. No, we can't replace it with something else; if we could, we would, but despite asking, the OpenJDK team hasn't provided anything we can use. As Rawi said, your tool shouldn't be mentioning this (it's an optional dependency - at runtime lombok isn't used at all. If it compiles, you're good to go).

Shipping lombok as a thing maven understands as a compiler (where lombok-the-compiler is just a very thin wrapper that launches javac-the-compiler straight from your JDK installation, passing the appropriate `--add-opens` is in progress.
