### ISSUE TITLE
[FEATURE] Builder static default / empty constant

### ISSUE THREAD

**Issue by anuragagarwal561994** [projectlombok/lombok#3590]
**Describe the feature**
A lot of times when using builder, we try to have a static constant such as
```
@Value
@Builder
public class Class {
    private static final Class DEFAULT = Class.builder().build()

    int a;
    String b;

    public static void getDefault() {
        return DEFAULT;
    }
}
```

There are some other patterns as well like `defaultInstance` or `empty` or `instance` that is being used. Most of the times I prefer to use `getDefault` because it is verbose enough, but since `default` is a keyword here it does a lot of other boilerplate code. These type of default helps user define default fallbacks when and prevents them from checking for nulls where possible. 

**Describe the target audience**
I think this is a simple thing and it does reduce less boiletplate but it starts to grow when we have 100s of Data objects and application starts to grow, then it feels like cumbersome and we start losing the consistency between getInstance, getDefault and sometimes one even starts to expose the instance publicly. Personally I don't like exposing it publicly.

Lets discuss on what others feel about this feature request.

**Comment by Rawi01** [comment]
You can add `@Getter` to your static variable but the name of the generated getter is probably not what you want and that doesn't solve your consistency problem.

**Comment by anuragagarwal561994** [comment]
Yes that is where a functionality either with Builder or another annotation would be nice.

I can use getter when defining constant like `instance` which can give me `getInstance` which is fine.
But I think it is by choice if somone wants to keep their constants as UPPER _CASE or lower, my probelm is when we have builder why to even bother about creating the constant ourselves, when we can simply assign Class.builder().build()

**Comment by rzwitserloot** [comment]
@anuragagarwal561994 I'm not sure what you're suggesting. Generally a feature request, or even an attempt to start a debate on a feature request, should probably include at least an attempt at 'this is what it looks like with lombok' vs 'this is what lombok would make of it, i.e. the output of delombok'.

A serious issue is, well, you said it: Consistently. There does not appear to be a community consensus on this. Specifically, most builderized types don't have a 'default', and even if they do, there is no consistent naming scheme.

I'm not sure a consistent naming scheme is even a good idea. Take `java.lang.String`, for example. If we're going to have a default value at all, the right answer is __obviously__ `empty` or `blank`, and `getDefault` is __obviously__ a bad idea. Obvious in that it _is_ a subjective question (it's about which name is less confusing and more 'readable', all human concepts - subjective. Opinion, taste, and all that) - but as far as subjective questions go, this one has very clear answers and I'd bet a lot of money if I go around a java conference and ask whether one would think such a thing would be called 'empty' or 'default', 90%+ would say 'empty', and many will comment on how 'default' seems like a very bad choice indeed.

Also, there's `.of()` which is beginning to be a bit of a community consensus, as the standardized name of static methods that act like constructors. However, any such thing that accepts a list of arguments (e.g. via varargs), then ends up having `.of()` to be __the__ canonical way to make an empty ('default') object. This is already the case in __extremely__ commonly used code today:

```
List<String> list = List.of();
```

So, here, `of()` is the default, and I think that's a correct take here. __It would be a mistake if `java.util.List` also had an `getDefault()` method or a `DEFAULT` field with an unmodifiable empty list__.

And hence, your feature request would be a mistake.

Closed - but feel free to attempt to make a convincing argument as to why it's a good idea. Closed issues can be re-opened.

**Comment by anuragagarwal561994** [comment]
@rzwitserloot sure I think that is fair to say that the information above is incomplete, may be because it is my first time writing an issue in the lombok project. I will try to check other feature requests and try to come up with a descrptive argument before I would open this issue again.
