### ISSUE TITLE
@Data annotation have some strange phenomenon

### ISSUE THREAD

**Issue by ex34toway** [projectlombok/lombok#3598]
**Describe the bug**
  @Data have some strange phenomenon

**To Reproduce**
  @Data
  @Accessors(chain = true)
  static class MyVo {
    private String eId;
  }

  will generate setEId/getEId getter setter...，json tool work strange. When use IDEA generate getter setter  seteId/geteId，json tools work well

**Expected behavior**
    final MyVo vo = new MyVo();
    vo.seteId("test");
    final ObjectMapper mapper = new ObjectMapper();
    // {"eId": "test"}
    System.out.println(mapper.writeValueAsString(vo));

**Version info (please complete the following information):**
 - Lombok version 1.18.24
 - Platform javac 11.0.8

**Additional context**

**Comment by Rawi01** [comment]
Use [lombok.accessors.capitalization = beanspec](https://projectlombok.org/features/GetterSetter#supported-configuration-keys) in your lombok.config
