### ISSUE TITLE
[BUG] Fix getter annotation for Boolean class field definition

### ISSUE THREAD

**Issue by lookcriss** [projectlombok/lombok#3607]
@Getter annotation for a field of class Boolean should have **is** prefix instead of **get**, just like the primitive type.

To reproduce, from how I find out: Create an interface and an implementation class. In the interface create a method that returns Boolean (eg. Boolean isValid()), have a field in the implementation class called (eg. valid) and annotate the class or field with @Getter, the compiler will complain about the fact that the class did not implemented all the interface methods, and will create a getter getValid(), instead of isValid().

Suggestion: to have the same implementation for Boolean class, just like in the primitive boolean.

 - Lombok version: 1.18.28

**Comment by dstango** [comment]
Recently I had a similar case, and the same wish as you have.

Yet, some web search turned out, Lombok is following the Java Beans specification here correctly. See e.g. here: https://stackoverflow.com/q/39307379
