### ISSUE TITLE
[BUG]  @ExtensionMethod replacing bug in Stream#map

### ISSUE THREAD

**Issue by lc77254** [projectlombok/lombok#3614]
**Describe the bug**
When I use the @ExtensionMethod in **Stream#map**, I except it would replace it in the **map** function, but it was out of this method.

**To Reproduce**
```java
@ExtensionMethod(Extensions.class)
public class ExtensionMethodExample {

    public static void main(String[] args) {
        String title = "title";
        List<Message> list = Stream.of("content1", "content2", "content3").map(title.of()::setContent).collect(Collectors.toList());
        System.out.println(list);
    }
}

@ToString
class Message {
    String title;
    String content;

    public Message(String title) {
        this.title = title;
    }

    public Message setContent(String content) {
        this.content = content;
        return this;
    }
}

class Extensions {
    public static Message of(String title) {
        return new Message(title);
    }
}
```

**Expected behavior**
It would produce 3 Message Instances with same title and different conetent but actully 3 of same instance.
reslult:
`
[Message(title=title, content=content3), Message(title=title, content=content3), Message(title=title, content=content3)]
`

**Version info (please complete the following information):**
1.18.12

**Additional context**
Decompile:
```java
    public static void main(String[] args) {
        String title = "title";
        Stream var10000 = Stream.of("content1", "content2", "content3");
        Message var10001 = Extensions.of(title);
        Objects.requireNonNull(var10001);
        List<Message> list = (List)var10000.map(var10001::setContent).collect(Collectors.toList());
        System.out.println(list);
    }
```
Below works:
```java
    public static void main(String[] args) {
        String title = "title";
        List<Message> list = Stream.of("content1", "content2", "content3").map(content -> title.of().setContent(content)).collect(Collectors.toList());
        System.out.println(list);
    }
```

**Comment by Rawi01** [comment]
This is not a bug, the output is identical if you use the static method without lombok (`Stream.of("content1", "content2", "content3").map(Extensions.of(title)::setContent).collect(Collectors.toList());`). This is a method reference that is bound to the result of `title.of()`.
