### ISSUE TITLE
[BUG] SuperBuilder cannot set properties

### ISSUE THREAD

**Issue by small-thanks** [projectlombok/lombok#3629]
**Describe the bug**
Properties cannot be set using superBuilder, the screenshot is as follows
![image](https://github.com/projectlombok/lombok/assets/68092501/def26b54-7219-491b-867d-d4d224343fc7)
My class structure is as follows
![image](https://github.com/projectlombok/lombok/assets/68092501/fe15ff1b-73b9-4872-a7a1-77f590d9166e)

**Version info (please complete the following information):**
 - Lombok version is 1.18.22
 - java version "1.8.0_391"
Java(TM) SE Runtime Environment (build 1.8.0_391-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
**Additional context**

**Comment by janrieke** [comment]
You have to use `@SuperBuilder` on all classes in your inheritance chain. Here, `AbstractInfoDTO` does not have it, only `@Builder`, which is not compatible with `@SuperBuilder`.
