### ISSUE TITLE
[BUG]  @Data注解在生成的字节码里equals方法一个有判定父类equals，一个没有（未配置callSuper=true）

### ISSUE THREAD

**Issue by HumorChen** [projectlombok/lombok#3631]
**Describe the bug**
第一个情况未生成判定父类equals
![image-20240318095720398](https://chpic.oss-cn-shanghai.aliyuncs.com/202403180957575.png)

![在这里插入图片描述](https://chpic.oss-cn-shanghai.aliyuncs.com/202403180957238.png)

查看生成的字节码里是没有调父类的equals

![在这里插入图片描述](https://chpic.oss-cn-shanghai.aliyuncs.com/202403181002510.png)

第二个情况却生成了对父类equals的判定
![在这里插入图片描述](https://chpic.oss-cn-shanghai.aliyuncs.com/202403181003646.png)

![在这里插入图片描述](https://chpic.oss-cn-shanghai.aliyuncs.com/202403181003699.png)
查看生成的字节码里是有调父类的equals
![在这里插入图片描述](https://chpic.oss-cn-shanghai.aliyuncs.com/202403181004973.png)

这是为啥？
@FieldNameConstants测试过不会影响这个callSuper

**To Reproduce**
Steps to reproduce the behavior, preferably in the form of the smallest java source file you can make that will show the problem when compiled with `javac -cp lombok.jar ExampleFile.java` or as sole java file in a fresh new eclipse project.

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.

**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.

**Additional context**

**Comment by Rawi01** [comment]
Please use English as the majority of people here don't understand Chinese.

The only way to generate super calls without setting the attribute on the annotation is through the lombok configuration system. Please check if there is a `lombok.config` file somewhere in your project.

**Comment by HumorChen** [comment]
got it
