### ISSUE TITLE
[BUG] Lombok fail when using @Singular annotation 

### ISSUE THREAD

**Issue by eitan-rosenberg** [projectlombok/lombok#3635]
I install Eclipse 2024-03 (4.31) and today I install Lombok v1.18.32 "Envious Ferret".

The project is Maven and use:

```
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.32</version>
</dependency>

```
There is a problem when using the Singular annotation.

This is the class that used to work just fine:

```
package myTestClasses;

import java.math.BigDecimal;
import java.time.YearMonth;
import java.util.Map;

import lombok.Builder;
import lombok.Data;
import lombok.Singular;

@Data
@Builder
public class MySeries {

	@Data
	@Builder
	public static class MyObsValue {

		private final BigDecimal obsValue;
		private final YearMonth timePeriod;

	}

	private final String currencySource;
	private final String currencyTarget;

	@Singular(value = "putMyObsValue")
	private final Map<YearMonth, MyObsValue> myObsValues;

	private final Double unitMultiplier;

}
```

I am getting:
- Lombok annotation handler class lombok.eclipse.handlers.HandleBuilder failed - See error log.
- The method builder() is undefined for the type MySeries.

Help...

Here is the log:
[.log](https://github.com/projectlombok/lombok/files/14668644/default.log)

**Comment by Rawi01** [comment]
The eclipse team merged these changes to the Java 22 support plugin, we didn't anticipated that and released the latest lombok version without the fix for it to not further delay it. You can find a build with the fix [here](https://github.com/projectlombok/lombok/actions/runs/8350007437).

**Comment by eitan-rosenberg** [comment]
Thanks,

Seems to solve the problem.

When it will be on Maven ?

**Comment by eitan-rosenberg** [comment]
Version 1.18.32 that reside in maven is not working when using @Singular annotation.
I test this today. 
Had to use the jar from here:
https://github.com/projectlombok/lombok/actions/runs/8350007437

**Comment by eitan-rosenberg** [comment]
Version 1.18.32 that reside in maven is not working when using "Singular" annotation.
I test this today.
Had to use the jar from here:
https://github.com/projectlombok/lombok/actions/runs/8350007437
