### ISSUE TITLE
[BUG] STS4 4.22.0 + Lombok 1.18.32 + JDK22 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by sergey-morenets** [projectlombok/lombok#3638]
**Describe the bug**

When I tried to migrate from STS 4.21 to STS 4.22 I got an error in STS UI and the stacktrace in the log:

```
java.lang.NoSuchMethodError: 'void org.eclipse.jdt.internal.compiler.ast.CaseStatement.<init>(org.eclipse.jdt.internal.compiler.ast.Expression, int, int)'
	at lombok.eclipse.Eclipse.createCaseStatement(Eclipse.java:285)
	at lombok.eclipse.handlers.singulars.EclipseJavaUtilListSingularizer.appendBuildCode(EclipseJavaUtilListSingularizer.java:75)
	at lombok.eclipse.handlers.HandleBuilder.generateBuildMethod(HandleBuilder.java:821)
	at lombok.eclipse.handlers.HandleBuilder.handle(HandleBuilder.java:563)
	at lombok.eclipse.HandlerLibrary$AnnotationHandlerContainer.handle(HandlerLibrary.java:106)
	at lombok.eclipse.HandlerLibrary.handleAnnotation(HandlerLibrary.java:237)
	at lombok.eclipse.TransformEclipseAST$AnnotationVisitor.visitAnnotationOnType(TransformEclipseAST.java:269)
```

I look into the code and it seems that CaseStatement class from Eclipse JDT doesn't have constructor that accepts Expression/int/int.
It was changed 3 weeks ago:

```
public CaseStatement(Expression[] constantExpressions, int sourceStart, int sourceEnd) {
	this.constantExpressions = constantExpressions;
	this.sourceStart = sourceStart;
	this.sourceEnd = sourceEnd;
}
```

**To Reproduce**

Open any workspace project in STS 4.22.0.

**Expected behavior**

No error should occur

**Version info (please complete the following information):**
 - Lombok 1.18.32
 - STS 4.22.0
 - JDK 22.0.0

**Comment by Rawi01** [comment]
The eclipse team merged these changes to the Java 22 support plugin, we didn't anticipated that and released the latest lombok version without the fix for it to not further delay it. You can find a build with the fix [here](https://github.com/projectlombok/lombok/actions/runs/8350007437).

**Comment by sergey-morenets** [comment]
Hi @Rawi01 

Thank you for the quick response. Does edge version contain this fix? When will it be released as stable version?

**Comment by rzwitserloot** [comment]
I think this warrants an emergency stable release. I'll discuss it with @rspilker – Until then, current [edge release](https://projectlombok.org/download-edge) includes this patch.

**Comment by jdimeo** [comment]
Thank you all SO MUCH for keeping up with the Eclipse releases and changes
