### ISSUE TITLE
[Eclipse annotation processor][LoggerFactory]

### ISSUE THREAD

**Issue by freedom1b2830** [projectlombok/lombok#3639]
**Describe the bug**
The eclipse annotation processor warns about the possible null value of the logger created by lombok.

I can’t attach screenshots, I use GH for reporting

**To Reproduce**
1.install lombok to eclipse
2.write:
```java

import org.eclipse.jdt.annotation.NonNullByDefault;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@NonNullByDefault
public class LombokNULLGEN {
	static {
		LombokNULLGEN.log.info("todo");
	}
}
```
3.change eclipse null processor:
```
	1.Java compiller
	2.Errors/Warnings
	3.Null analysis
	4.Enable annotation-based null analysis
	5.switch "Unchecked conversion from non-annotated type to @NonNull type: Warning/Error"
	6.Use default annotations for null specifications (Configure) (add lombok.NonNull)
```	
4.see warn:
```
Null type safety (type annotations): The expression of type 'Logger' needs unchecked conversion to conform to '@NonNull Logger'
```	

**Expected behavior**

Lombok must (OR):
a) change the operation of the eclipse annotation processor
b) generate code similar to this:
```java
import java.util.Objects;

import org.eclipse.jdt.annotation.NonNullByDefault;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lombok.NonNull;

@NonNullByDefault
public class LombokNULLGEN {
	@NonNull
	private static final Logger log = Objects.requireNonNull(LoggerFactory.getLogger(LombokNULLGEN.class));

	static {
		LombokNULLGEN.log.info("todo");
	}
}
```

**Version info (please complete the following information):**
 - Lombok version
```
v1.18.31 "Edgy Guinea Pig" - 2024-01-12
```

Eclipse:
```
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437
```

**Comment by janrieke** [comment]
In my opinion, this is a deficiency of the Eclipse analyzer. The Eclipse handler (and the javac handler, too) creates the following code:
```
class LoggerSlf4jWithStaticInitializer {
  private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(LoggerSlf4jWithStaticInitializer.class);
  static {
    log.debug("test");
  }
}
```
The [JLS spec describes in section 12.4.2](https://docs.oracle.com/javase/specs/jls/se17/html/jls-12.html#jls-12.4.2) how the initialization process works:
> `6.` [...] Then, initialize the static fields of C which are constant variables [...]
> `9.` Next, execute [...] the class variable initializers and static initializers of the class [...], in textual order, as though they were a single block.

So `log` cannot be `null` in the static initializer code.
