### ISSUE TITLE
[BUG] I found this phenomenon in an unintentional debugging and do not understand it

### ISSUE THREAD

**Issue by chenhaoran12** [projectlombok/lombok#3652]
**Describe the bug**
java classes that use the Lombok@Data annotation do not have this compile-time problem when they create objects through reflection and the resulting object set function has a return value instead of the expected void type.

**Expected behavior**
 I want to use BeanMap to assign values to object Fields. I may have acted foolishly, hope to get a reply, thank you. My English is very poor, please forgive me!

**Version info (please complete the following information):**
 - Lombok version 1.18.30
 - Platform  Intellij IDEA2023.1, JDK17

**Additional context**
```
BpmImportUserGroupVO groupVO = BpmImportUserGroupVO.class.getDeclaredConstructor().newInstance();
org.springframework.cglib.beans.BeanMap.Generator gen = new org.springframework.cglib.beans.BeanMap.Generator();
gen.setBean(groupVO);
gen.setContextClass(groupVO.getClass());
BeanMap beanMap = gen.create();
beanMap.put("firstGroupName", "123");
System.out.println(groupVO);
```
```
@Data
public class BpmImportUserGroupVO{

    /**
     * 组群名
     */
    private String firstGroupName;

    /**
     * 创建人
     */
    private String creator;

    /**
     * 组名
     */
    private String secondGroupName;

    /**
     * 成员用户编号数组
     */
    private List<String> members;
}
```
Phenomenon :
![6C9323DB-0EBE-4fa5-B85C-3A9B1BF21812](https://github.com/projectlombok/lombok/assets/42337011/d2387dfc-b7bc-492c-8fe9-388f6e9468ed)
Result :
![20D0939D-C2A6-48bc-A831-7FF64D5CBD98](https://github.com/projectlombok/lombok/assets/42337011/eee29b08-f914-4d23-9bd4-88bff17a7f8c)

Improvement :
![CB6E3B89-3D27-4fb2-B5A2-8F5B2E4B1F07](https://github.com/projectlombok/lombok/assets/42337011/dfa06194-525f-4569-8bd3-2176a9225ff1)

Notice ! The improved solution is to remove the chain call, which needs to be specified manually, and the default attribute in the annotation does not take effect.

**Comment by rspilker** [comment]
Did you check `lombok.config`, where it might be configured to chain for the whole directory or even the whole project? See also https://projectlombok.org/features/configuration

**Comment by chenhaoran12** [comment]
Thank you, guru！This is an oversight on my part,the project configuration was actively configured.
