### ISSUE TITLE
[FEATURE] finish the job and make generating `@lombok.Generated` default behaviour

### ISSUE THREAD

**Issue by rzwitserloot** [projectlombok/lombok#3667]
As per the [javadoc of `@Generated`](https://projectlombok.org/api/lombok/Generated) the plan is that it'll be default.

In the words of someone wiser than I, [Let's go already!!!](https://www.youtube.com/watch?v=VrJaUzfKABU).

**Comment by rzwitserloot** [comment]
If you want to disable this, add to [`lombok.config`](https://projectlombok.org/features/configuration):

```
lombok.addLombokGeneratedAnnotation = false
```

**Comment by brychcy** [comment]
For Eclipse, I always need to upgrade to the latest Lombok version. When working on a project that still uses Lombok 1.18.32 in Eclipse (with Lombok 1.18.38) and then running maven on it, i now got weird errors like:

```
[INFO] --- dependency:3.6.0:analyze-only (default-cli) @ basket.api ---
[ERROR] Used undeclared dependencies found:
[ERROR]    org.projectlombok:lombok:jar:1.18.32:provided
```

(We always use Lombok with scope "provided" so it doesn't leak into depending projects that may use newer Java versions and breaks their build)

Workaround was to exclude Lombok from the analysis:
 ```
     <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
[...]
        <configuration>
          <ignoredUsedUndeclaredDependencies>
              <ignoredDependency>org.projectlombok:lombok</ignoredDependency>
```


In a time, where Java and Eclipse are updated every few months both of which always require Lombok updates, it would help a lot if you would avoid any further breaking changes.
