### ISSUE TITLE
[BUG] @Delegate does not respect --source and --target

### ISSUE THREAD

**Issue by jbb01** [projectlombok/lombok#3681]
**Describe the bug**
Java 21 added the `SequencedCollection` interface and modified `List` to extend `SequencedCollection`. When generating delegate methods for a `List` with `@Delegate` on JDK 21 with --source and --target set to 17, a delegate for `SequencedCollection reversed()` is generated even though `SequencedCollection` did not yet exist in JDK 17. This causes an error when loading the class containing the delegate method. The problem does not occur when using --release 17 instead of --source and --target.

**To Reproduce**
Compile the following example
```java
// Test.java

@RequiredArgsConstructor
public class Test<X> implements List<X> {
    @Delegate
    private final List<X> delegate;

    public static void main(String... args) {}
}
```
with JDK 21 like this
```
> javac --class-path lombok-1.18.32.jar --processor-path lombok-1.18.32.jar --source 17 --target 17 Test.java
```
then inspect the generated class with `javap`:
```
> javap Test.class
Compiled from "Test.java"
public abstract class Test<X> implements java.util.List<X> {
  // ...
  public java.util.SequencedCollection reversed();
}
```
Try running the class with JDK 17
```
> java Test
Error: Unable to initialize main class Test
Caused by: java.lang.NoClassDefFoundError: java/util/SequencedCollection
```

For comparison, now try compiling with --release like this
```
> javac --class-path lombok-1.18.32.jar --processor-path lombok-1.18.32.jar --release 17 Test.java
```
This time no `SequencedCollection reversed()` method is generated as can be seen with `javap` and the class can be run without an error.

**Version info (please complete the following information):**
 - Lombok version: 1.18.32
 - javac 21.0.2

**Comment by janrieke** [comment]
That is exactly the reason why `--release` was introduced. `--source/--target` just sets the language level, not the API you are programming against.
