### ISSUE TITLE
[BUG] Lombok 1.18.34 (Edit updated) not working with eclipse 24-06

### ISSUE THREAD

**Issue by WendyLg1** [projectlombok/lombok#3699]
**lombok eclipse plugin does not appear to be working in the latest version of eclipse. Windows 11**
None of the generated builder classes are being "generated", none of the getters or setters are being "generated" none of the constructors are being "generated". Lombok isn't listed in the about window.

**To Reproduce**
Update eclipse to the latest version and install the plugin on windows

I am using maven as my compile system and when using that on the command line everything works correctly (checked by decompiling the .class file) it is just inside eclipse it isn't working.
 here is the smallest class I have, everywhere that is trying to use it eclipse is reporting compilation problems using the builder, the constructor or any of the setter.
 ```
import java.time.LocalDateTime;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

@Builder
@AllArgsConstructor
@Data
@SuppressWarnings("squid:S1068") //Lombok Configuration Issue
public class ClientAccount {

    @Size(max = 30)
    private String accountName;

    @Size(max = 50)
    private String accountReference;

    @NotNull
    @Size(max = 32)
    private String clientId;

    @NotNull
    @Size(max = 64)
    private String clientSecretKey;

    private LocalDateTime keyLastUpdated;
}
```
**Expected behavior**
The code to compile inside eclipse

**Version info (please complete the following information):**
 - Lombok version 1.18.34
 - Platform Eclipse version Version: 2024-06 (4.32.0) the installed version within eclipse is java.runtime.version=21.0.3+9-LTS

**Additional context**
I have annotations enabled
![image](https://github.com/projectlombok/lombok/assets/138771460/f0b60ae9-c4b9-46b6-ba60-e6cc69316b7e)
This is what the outline view shows, i have seen this is meant to show the post lombok view
![image](https://github.com/projectlombok/lombok/assets/138771460/2b13f645-8aeb-45b5-b99d-667d341f4231)A snippet of the error messages
![image](https://github.com/projectlombok/lombok/assets/138771460/cb695101-caf9-444d-8a93-74072e622701)

**Comment by janrieke** [comment]
Use Lombok 1.18.34.

**Comment by WendyLg1** [comment]
Just updated and that has solved everything except the compile problems, still nothing compiles

**Comment by WendyLg1** [comment]
I closed and cleaned the project, tidied up my java version in eclipse (I have no idea where it got the idea I was using java 17) and now it is working.

**Comment by matucsom** [comment]
use intellij, eclipse sucks

**Comment by vikasg2009** [comment]
- 
Reason : Lombok JAR not installed in Eclipse
- Download lombok.jar 1.18.38
- Run the JAR from Bash
         java -jar lombok.jar
- In the installer UI, point it to your Eclipse installation directory and click Install/Update.
- Restart Eclipse and rebuild the project.
-It works.

**Comment by atom888888** [comment]
> use intellij, eclipse sucks

That is a very hateful comment and not relevant to helpful to the resolution of the problem.
