### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Nerdy-bug** [projectlombok/lombok#3721]
**Describe the bug**
When java entity classes use the @`Data` annotation then post request using org.springframework.web.bind.annotation
@RequestBody annotation uses entity classes to receive parameters if attributes of entity classes like this ,for example, tId aId, the format is single letter plus capitalization format , The value corresponding to the key cannot be obtained through the parameters accepted by the entity class.

**To Reproduce**
Java Class attribute like this and user lombok annotation @Data
```
@Data
public class EntityForTestDemo {
    private String tId;
    private Integer uId;
}
```
controller receive args with @ReqeustBody 
```
@RestController
@RequestMapping("/testdemo")
public class TestDemoController {
    @PostMapping
    public EntityForTestDemo handleDataSubmit(@RequestBody EntityForTestDemo data) {
        return data;
    }
}
```
 Then use the request tool to request that this interface parameter be passed in json mode.
If my request args is following (The letter i is capitalized)
```
{
    "tId": "222",
    "uId":"199"
}
```
the interfave return following
```
{
    "tId": null",
    "uId":null
}
```
while my request args is following(etter i lowercase)
```
{
    "tid": "222",
    "uid":"199"
}

```
this case the return is following
{
    "tid": "222",
    "uid":"199"
}
**Expected behavior**
Expect this problem to be fixed

**Version info:**
 - Lombok version lastest version
 - jdk 17

**Comment by Rawi01** [comment]
You can control the name of getters for tricky cases like this using [`lombok.accessors.capitalization`](https://projectlombok.org/features/experimental/Accessors#supported-configuration-keys) but if I understand your problem correctly you have to set a custom json property name e.g. using `@JsonProperty`.
