### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by NoClient** [projectlombok/lombok#3724]
@Data 
public class UserEntity implements Serializable {
    private Long cUserId;
}

**Comment by NoClient** [comment]
A property field composed of multiple words, where the first word consists of only one letter, getting and setting will become invalid.

Web page to backend interface request

**Comment by Rawi01** [comment]
You can control the name of getters/setters for tricky cases like this using [`lombok.accessors.capitalization`](https://projectlombok.org/features/experimental/Accessors#supported-configuration-keys).
