### ISSUE TITLE
[FEATURE] Add @ToJson and @FromJson Annotations for Automatic JSON Serialization and Deserialization

### ISSUE THREAD

**Issue by abdelhak-zaaim** [projectlombok/lombok#3739]
I would like to propose an enhancement to Lombok by introducing two new annotations: **@ToJson** and **@FromJson**. These annotations would automatically generate methods for JSON serialization and deserialization in a class, streamlining the process of converting objects to and from JSON. This feature would reduce the need for external libraries or manual implementations in Java classes.

`@ToJson
@FromJson
public class MyClass {
    private String field1;
    private int field2;
}
`

**Expected Behavior:**

- **@ToJson:** Automatically generates a toJson() method that converts the object into a JSON string.
- **@FromJson:** Automatically generates a static fromJson(String json) method that creates an instance of the class from a JSON string.

**Proposed Method Signatures:**

1. `String toJson();`
2. `static MyClass fromJson(String json);`

**Benefits:**

- Reduced Boilerplate: Simplifies JSON (de)serialization by eliminating the need for manual implementation or relying on external libraries (like Jackson or Gson).
- Cleaner Code: Provides a clean, Lombok-style way to handle JSON operations directly in the class definition.
- Integration: Could work well with other Lombok annotations like @Builder and @Data, making JSON handling part of the fluent Lombok experience.

**Comment by janrieke** [comment]
That has been suggested and denied several times. This feature is out of scope for Lombok, and there are several frameworks that can do it much better than Lombok could ever do.
