### ISSUE TITLE
[BUG] Error in JDK 23, does it support JDK 23?

### ISSUE THREAD

**Issue by imgoby** [projectlombok/lombok#3752]
version: jdk 23

error:
cannot find symbol
[ERROR]   symbol:   variable log

code:
` log.info("test");`

**Comment by SimonTaylor** [comment]
I'm seeing the same issue after upgrading to Spring Boot 3.3.4 and JDK 23. Slightly different error message as I have a Lombok config file to set the log variable name to uppercase.

I am also seeing compilation errors when trying to create instances of classes annotated with '@AllArgsConstructor'.

**Comment by SimonTaylor** [comment]
From the [JDK 23 release notes](https://jdk.java.net/23/release-notes#:~:text=As%20of%20JDK%2023%2C%20annotation,on%20the%20javac%20command%20line.):

> As of JDK 23, annotation processing is only run with some explicit configuration of annotation processing or with an explicit request to run annotation processing on the javac command line.

Adding the `-proc:full` compiler option makes things work as they did for earlier versions.

**Comment by imgoby** [comment]
I test javac is OK.

step 1:
sdk install java 23.ea.24-graal
sdk use java 23.ea.24-graal
sdk default java 23.ea.24-graal

step 2:

```
import lombok.Data;

@Data
public class Main {
    private Integer age;

    public static void main(String[] args) {
        Main main=new Main();
        main.setAge(100);
        System.out.println(main.getAge());
    }
}

```

step 3:


`javac -proc:full -cp lombok-1.18.34.jar   Main.java `

But in maven project, it is not  OK.
mvn -Dmaven.compiler.proc=full  clean package

**Comment by imgoby** [comment]
maven is OK.We should pay attention to the setting:
(1)maven ,Update to a newer version.Mine is: apache-maven-3.9.9
(2)upgrade sprintboot to :3.3.0,
pom.xml 's setting:
```

 <maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
 <spring-boot.version>3.0.9</spring-boot.version>

        <java.version>1.23</java.version>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>


        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <inherited>true</inherited>
                <configuration>
                    <parameters>true</parameters>
                    <source>23</source>
                    <target>23</target>
                </configuration>
            </plugin>
...
        </plugins>
```

(3)mvn package
mvn  -Dmaven.compiler.proc=full  clean package

**Comment by melbeltagy** [comment]
In maven projects, in pom files, setting up `maven.compiler.proc` property with `full` value should also fix the issue without needing to pass the argument in command line.
All details are mentioned here: https://dzone.com/articles/using-lombok-library-witk-jdk-23

**Comment by imgoby** [comment]
thank you for your advice.It is helpful.
