### ISSUE TITLE
[BUG] When source contains jooq generated User Defined Type code, lombok fails to compile

### ISSUE THREAD

**Issue by superxiao** [projectlombok/lombok#3782]
**Describe the bug**  
[Demo repo](https://github.com/superxiao/lombok-jooq-bug-demo)  
The repository contains [code generated by jOOQ](https://github.com/superxiao/lombok-jooq-bug-demo/tree/main/src/main/java/generated). It compiles successfully before adding Lombok. After adding Lombok, the annotations are not recognized, resulting in a compilation error. Adding `org.jetbrains:annotations` as a dependency resolves the issue.

**To Reproduce**  
[Demo repo](https://github.com/superxiao/lombok-jooq-bug-demo)  
Run `./gradlew compileJava`. The following compilation errors occur:

```
> Compilation failed; see the compiler output below.
  error: cannot access ApiStatus
    class file for org.jetbrains.annotations.ApiStatus not found
  /home/xiaojian-wang/lombok-jooq-bug-demo/src/main/java/com/example/DemoApplication.java:21: error: cannot find symbol
                log.info("Person ${}", Person.builder().name("John").build().getName());
                                             ^
    symbol:   method builder()
    location: class Person
  /home/xiaojian-wang/lombok-jooq-bug-demo/src/main/java/com/example/DemoApplication.java:21: error: cannot find symbol
                log.info("Person ${}", Person.builder().name("John").build().getName());
                ^
    symbol:   variable log
    location: class DemoApplication
  3 errors
```

Adding `org.jetbrains:annotations` as a dependency fixes the compilation. However, before Lombok is added, the project compiles without needing `org.jetbrains:annotations`.

**Expected behavior**  
Adding Lombok should not introduce new dependencies that are otherwise not required.

**Version info (please complete the following information):**
- Lombok version: 1.18.36
- Platform: Java, Gradle, Ubuntu latest

**Additional context**

**Comment by Rawi01** [comment]
This seems to be a general problem if you use an annotation processor (like lombok) with jooq. I used your example, replaced the lombok with mapstruct (`annotationProcessor("org.mapstruct:mapstruct-processor:1.6.3")`), removed the demo code and still get the `class file for org.jetbrains.annotations.ApiStatus not found` error.

**Comment by superxiao** [comment]
Thanks. I will report this issue back to jooq.

**Comment by superxiao** [comment]
I think this issue can be closed. It's easy enough that anyone run into this to just include the `org.jetbrains:annotations` dependency. The error message does mention that the annotation cannot be found.
