### ISSUE TITLE
[BUG] @SneakyThrows does not work with JDK23 and InterruptedException

### ISSUE THREAD

**Issue by snuyanzin** [projectlombok/lombok#3790]
**Describe the bug**
 There is a piece of code working with jdk 22 and below
```java
        @SneakyThrows
        public FSDataOutputStream create(final Path filePath, final WriteMode overwrite)
                throws IOException {
            ...
            createTriggerLatch.await(); // could throw InterruptedException
            ...
        }
```
the full snippet is available at 
https://github.com/apache/flink/blob/be25a140f011e6ff93a23f28b3826d376a1c0ba7/flink-core/src/test/java/org/apache/flink/core/fs/InitOutputPathTest.java#L285-L303

If this is not possible, give us enough to reproduce the problem. If you have stack traces or error messages please include all of them, and include screen shots if that will help explain the problem.
the trace
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:testCompile (default-testCompile) on project flink-core: Compilation failure
[ERROR] flink/flink-core/src/test/java/org/apache/flink/core/fs/InitOutputPathTest.java:[301,37] unreported exception java.lang.InterruptedException; must be caught or declared to be thrown
```
**Expected behavior**

**Version info (please complete the following information):**
 - Lombok version 1.18.36
 - Platform (javac or eclipse, and if so, what is the output of `javac -version` / the version listed in the _about..._ dialog of eclipse.
```
Java version: 23.0.1, vendor: Eclipse Adoptium
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.8.0-49-generic", arch: "amd64", family: "unix"
```
**Additional context**

**Comment by Rawi01** [comment]
Since JDK 23 you have to enable annotation processing using `-proc:full` as compiler flag or add your annotation processor to the processor path. https://inside.java/2024/06/18/quality-heads-up/

**Comment by snuyanzin** [comment]
yep, thanks, with `-proc:full` the problem disappears
