### ISSUE TITLE
[FEATURE] No Constructor Annotation

### ISSUE THREAD

**Issue by sylphrena0** [projectlombok/lombok#3792]
**Describe the feature**
Frequently, I make utility classes that should not be constructed -> in order to ensure API users do not construct instances of these classes,  I need to make a private constructor, or use a lombok constructor with the access level configured. While this is possible with lombok, it seems clunky and non-intuitive.

Current Java Solution
```java
public class MyUtilityClass {
    private MyUtilityClass() {
        throw new IllegalStateException();
    }
    ...
}
```

Current Lombok Solution
```java
@NoArgsConstructor(access = AccessLevel.NONE)
public class MyUtilityClass {
    ...
}
```

Suggested Lombok Solution:
```java
@NoConstructor
public class MyUtilityClass {
    ...
}
```

or, perhaps, `@UtilityClass`.

While avoiding the base java boilerplate is currently implemented with lombok, I think it would be prudent to add a more intuitive decorator that obviously serves this purpose.  

**Describe the target audience**
This applies to any user that creates utility classes and does not want them to instantiated.

**Comment by janrieke** [comment]
There already is `@UtilityClass`, see https://projectlombok.org/features/experimental/UtilityClass. Does this cover your use case?

**Comment by sylphrena0** [comment]
That does, thank you!
