### ISSUE TITLE
New feature like @Adder

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#391]
_Migrated from Google Code (issue 318)_

**Comment by victorwss** [comment]
Any chance to revisit this? This is very useful to almost all objects having collections (anything that extends java.util.Collection). A @Clearer and a @Remover would be handy too. Note that for @Builder, we already have @Singular.

I'd read the e-mails (back to 2012) and I disagree with the conclusion. @Delegate won't work. The constraint to "a specific" type is instead a very broad type in practice. Having being force to use a setter might violate encapsulement.
