### ISSUE TITLE
Lombok doesn't work with GWT in hosted mode

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#410]
_Migrated from Google Code (issue 337)_

**Comment by nekqy** [comment]
Fix of the problem is https://github.com/Xenoage/lombok/ isn't it?

**Comment by rzwitserloot** [comment]
Sounds like this was due to a bug in GWT (they mistakenly didn't treat `$` as valid java identifiers), which has since been fixed in GWT, making this bug moot.
