### ISSUE TITLE
@Getter and @Setter on a Date

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#420]
_Migrated from Google Code (issue 347)_

**Comment by yx726843014** [comment]
sss

**Comment by avnerAtLili** [comment]
Guys I understand your point with regarding to not being able to support ALL mutable fields,
but dates are a very common use-case, and not having support for date fields in many cases just makes Lombok not usable for creating class builders, and adds a burden of adding special getters and setters just for Date fields.

Please reconsider having a special treatment for dates, or for the very least allow registering a global clone-factory for certain types. e.g. 

@CloneFactory(class = java.util.Date, factory = MyDateCloner.class)

**Comment by peter-sattler** [comment]
If you don't make a defensive copy of all mutable instance fields (like Date), then you don't have an immutable object!!! This also holds true for @Value which sells itself as an "easy way" to create immutable objects. So, users think they have immutability based on the documentation, but that may not be true. Very dangerous and misleading behavior for such a widely used API.
