### ISSUE TITLE
@Setter/@Getter and @Deprecated create Eclipse AST problems

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#481]
_Migrated from Google Code (issue 408)_

**Comment by goelrohi** [comment]
Hi,

I'm getting the same error while using eclipse Version: Oxygen Release (4.7.0) with Lombok v1.16.16 "Dancing Elephant"

**Comment by omega09** [comment]
@goelrohi Can't reproduce. Can you post a small code snippet?
