### ISSUE TITLE
com.sun.tools.javac.tree.JCTree$JCTypeApply cannot be cast to com.sun.tools.javac.tree.JCTree$JCArrayTypeTree

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#530]
_Migrated from Google Code (issue 457)_

**Comment by melany-chavez-17** [comment]
i have this problem: 
java: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid'

**Comment by rspilker** [comment]
@melany-chavez-17   I guess you switched to JDK21 and did not used the latest versin of lombok.

**Comment by rspilker** [comment]
Closing this issue, too old to still be relevant
