### ISSUE TITLE
error: Lombok visitor handler class lombok.javac.handlers.HandleVal failed: java.lang.NullPointerException

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#578]
_Migrated from Google Code (issue 543)_

**Comment by rahatmushfiqabir** [comment]
java: Lombok visitor handler class lombok.javac.handlers.HandleVal failed: java.lang.NoSuchMethodError: 'boolean com.sun.tools.javac.code.Symbol$TypeSymbol.isLocal()'

**Comment by rzwitserloot** [comment]
@rahatmushfiqabir That error does not seem to be related to this issue. You should file a new one, but note that you will need to add a stack trace (from the 'Error Log' view in eclipse for example), no information about which lombok version you are using, and no source file that can be used to reliably reproduce this error (or more in-depth information about when this error seems to occur or not, if you can't reproduce it reliably), it'll just be closed.
