### ISSUE TITLE
Could we get a var to go with val please?

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#634]
_Migrated from Google Code (issue 599)_

**Comment by sizebay** [comment]
I would like to, kindly, ask you guy to give another chance to _var_. All arguments pointed here was pretty valid. Even though *reinierz* has pointed many caveats and issues regarding this, _var_ would be a nice improvement that Lombok could introduce to their users.

> I'm pretty sure that 'var' instead of 'val' is going to result in mischaracterising the types of your expressions when glancing at code, where 'val' mostly avoids it.

I'm also sure that the same problem could happen on Scala, Kotlin and Groovy (_def_). Who have designed a code that uses _var_ should keep in mind that it could happen. But, whom those a have good designed code would be greatly benefited with features. When people talk about _var_, the first think that comes up to me is capability to write a code like this:

```java
// this is just an exemple
public Item chooseBetweenThings() {
    var item = Defaults.ITEM;
    if ( somethingComesUp ){
        item = new Item();
    }
    return item;
}
```

But most of time, we could avoid the verbosity that the Java Generics imposes on code design:

```java
// the bellow code
List<Something<Generic>> list = new ArrayList<>();
// could be turned into
var list = new ArrayList<Something<Generic>>();
```

It starts to make more sense when you have something like this:
```java
public DTO convertToDTO( VO vo ){
    List<VOItem<B>> originalItems = vo.subItems();
    List<DTOItemB> items = new ArrayList<>;

    for ( VOItem<B> originalItem : originalItems ){
        DTOItemB item = DTOItemB.from( originalItem );
        items.add( item );
    }

   return new DTO( items );
}
```
The above code become more clear if it would be something like this
```java
public DTO convertToDTO( VO vo ){
    var originalItems = vo.subItems();
    val items = new ArrayList<DTOItemB>;

    for ( val originalItem : originalItems ){
        var item = DTOItemB.from( originalItem );
        items.add( item );
    }

   return new DTO( items );
}
```

Is there any chances that _var_ could be reconsidered?
Note that I'm arguing that the issues that was pointed out by you guys does not make sense. But arguing that, besides the issues that it could led, we still have benefits  by using _var_.
