### ISSUE TITLE
Add an annotation making arguments final

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#656]
_Migrated from Google Code (issue 621)_

**Comment by Maaartinus** [comment]
Years later, I ran over this idea again and I'd like you to have one more look.

- assigning parameters is sometimes the best solution, but sometimes a mistake
- having a way to get a warning or an error on doing this could be helpful
- AFAIK no static tool can handle this properly (an *unconditional* warning is useless)
- Lombok is the only tool offering `@NonFinal`

I don't want the annotation anymore, all I'd like to have is a configuration like
```lombok.finalArgs=true```
which makes all args final, except for those marked by `@NonFinal`. I find this perfect, as it allows me to do everything, but forces me to be explicit about it. As parameter assignment is not very common, the visual clutter is no problem.
