### ISSUE TITLE
@Builder should require invoking methods associated with final fields

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#707]
_Migrated from Google Code (issue 672)_

**Comment by fransf-wtax** [comment]
@Maaartinus If a PR were to be submitted for this, would it be considered?

I think it's reasonable to at least have a `finalFieldsAreRequired` parameter to the `@Builder` annotation (defaulting to `false` for backwards compatibility), which would:
- introduce a boolean field in the builder class for each final field of the target class called `<field>Set`
- set this boolean to true whenever a `<field>()` method in the builder is called for a final field of the target object
- check in the `build()` method that all these booleans have been set to `true` before actually creating the target object instance, or throwing an `IllegalArgumentException` if one or more fields have not been set (possibly indicating in the error message which fields these are)

I think this provides full backwards compatibility with how `@Builder` currently works, while introducing stronger checks for objects with final fields, aligning to the checks the Java does in the constructor of a class with final fields.
