### ISSUE TITLE
Renaming field doesn't rename getters and setters

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#753]
_Migrated from Google Code (issue 718)_

**Comment by rgra** [comment]
Looks like a duplicate of #210.

**Comment by gregors** [comment]
still aggravating in 2017

**Comment by Rawi01** [comment]
The issue has been addressed and is [covered by a test](https://github.com/projectlombok/lombok/blob/master/test/eclipse/src/lombok/eclipse/refactoring/RenameTest.java)
