### ISSUE TITLE
Can't use ExtensionMethod in Java 8 Interfaces

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#755]
_Migrated from Google Code (issue 720)_

**Comment by Rawi01** [comment]
@rzwitserloot I just tried to add this feature and it seems like it can be done with a few additional/modified lines. Do you accept a PR for this one?

**Comment by Vyacheslav-Lapin** [comment]
is it duplicate of #3228 ?

**Comment by marc-guenther** [comment]
Hasn't this been resolved by #3259 last week?
