### ISSUE TITLE
Names of Getters and Setters generated by Lombok are buggy for attributes like "eMail" or "aValue" etc

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#757]
_Migrated from Google Code (issue 722)_

**Comment by shijiebei2009** [comment]
as I think, the eclipse and IDEA do the right things, why are not you in conformity with them???

**Comment by o-pikozh** [comment]
Maybe, we should create `@xGetter` and `@xSetter` annotations with new behavior?

**Comment by rzwitserloot** [comment]
@o-pikozh No, clearly a world where there are 18 different `@FooGetter` annotations, each with slightly different behaviour, is far worse than what we have now. In 99.99% of all cases this doesn't matter, but having multiple getter annotations is something lots of people are going to see and then they need to have their day rudely interrupted to read all about exotic, irrelevant details.

It is what it is.

**Comment by Toilal** [comment]
Please make it happen without breaking change, `@Getter(strict=true)`, `@Setter(strict=true)` could do the job.

**Comment by rzwitserloot** [comment]
Duplicate of #2693

**Comment by Ketty0725** [comment]
Simple things have to be complicated，it's so low!

**Comment by Rawi01** [comment]
@Ketty0725 If you read the linked catch-all issue, you can see that it is not as simple as it looks at first glance. And this is fixed, by the way.
