### ISSUE TITLE
didn't work with eclipse Mars (64 bit)

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#873]
_Migrated from Google Code (issue 838)_

**Comment by rspilker** [comment]
Lombok v1.16.6 has just been released and contains several Mars fixes. Can you please verify if this version still contains the problem?

**Comment by hking-shutterfly** [comment]
Lombok 1.16.8 works with Eclipse Mars in Windows, but not in Mac OS.  Discussion of this problem in http://stackoverflow.com/questions/31297342/lombok-not-working-in-eclipse-mars

Verified in Mac OS /Applications/Eclipse.app/Contents/Eclipse/eclipse.ini has the line
-javagent:../Eclipse/lombok.jar
and /Applications/Eclipse.app/Contents/Eclipse//lombok.jar is there
