### ISSUE TITLE
Checkstyle plugin in Eclipse

### ISSUE THREAD

**Issue by Maze-fr** [projectlombok/lombok#887]
Hello,

It is known for a long time (according to my google search) that using Lombok with Checkstyle Eclipse plugin makes a lot of errors appear because Checkstyle plugin doesn't see Lombok.

Is there a way to make it happen with Lombok, like the way Lombok make Eclipse recognize it and make auto completion appear ?
Or do I have to complain to Checkstyle Eclipse plugin team ?

**Comment by lealceldeiro** [comment]
Long thread and no answer yet

**Comment by Rawi01** [comment]
As far as I know checkstyle works properly in eclipse. Can you explain your problem?

**Comment by rzwitserloot** [comment]
Unfortunately, we do not have the resources to go in and manually 'fix' every other project that interacts with source code. The checkstyle team is presumably quite a bit more familiar with their codebase than we are :)

Lombok (now, I don't think we had that in 2015) annotates generated methods, and plugins should notice this and act accordingly. If checkstyle doesn't, then checkstyle's devs can probably update checkstyle to take `@Generated` and co into account fairly easily. If checkstyle is going off of eclipse ASTs, then I'd give it another try, we (especially @Rawi01) has done a lot of work on that front.

**Comment by lealceldeiro** [comment]
> As far as I know checkstyle works properly in eclipse. Can you explain your problem?

The issue for me shows up when configuring the [Checkstyle Maven Plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/) v8.44 to check for [Violations as Part of the Build](https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html) in a Springboot multi-module project with no special config:

```
        <execution>
            <id>check-code-style</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
```
When I run `./mvnw clean compile verify` the checkstyle maven plugin "doesn't see" the generated code by Lombok (i.e. *getters*/*setters*)

**Comment by lealceldeiro** [comment]
> Unfortunately, we do not have the resources to go in and manually 'fix' every other project that interacts with source code. The checkstyle team is presumably quite a bit more familiar with their codebase than we are :)
> 
> Lombok (now, I don't think we had that in 2015) annotates generated methods, and plugins should notice this and act accordingly. If checkstyle doesn't, then checkstyle's devs can probably update checkstyle to take `@Generated` and co into account fairly easily. If checkstyle is going off of eclipse ASTs, then I'd give it another try, we (especially @Rawi01) has done a lot of work on that front.

Fair enough :)

I completely agree with you. Thanks for the quick reply.

**Comment by rzwitserloot** [comment]
@lealceldeiro That bug is unrelated to this bug, entirely so. This bug's title is 'checkstyle plugin in eclipse', and I'm pretty sure that the checkstyle plugin for maven doesn't fire up an eclipse to do the work :)

The fix for your issue would presumably making the checkstyle plugin apply lombok as it does its work. I have no idea how checkstyle even works - probably uses either ecj or javac under the hood, because writing your own java parser is quite a big job. Especially if it uses ecj, it won't be all that hard to add support.

Perhaps add a new issue, given that this one is specifically for the _eclipse plugin_ of checkstyle, not the maven plugin.
