### ISSUE TITLE
Lombok installer does not work with SpringSource Tool Suite 2.1.0.RELEASE

### ISSUE THREAD

**Issue by lombokissues** [projectlombok/lombok#95]
_Migrated from Google Code (issue 22)_

**Comment by atankala** [comment]
Rename the file "STS.EXE" to "sts.exe" under ../sts-bundle/sts.app/Contents/MacOS/.
And then run java -jar lomobok.jar and select the STS.ini file under ../sts-bundle/sts.app/Contents/Eclipse

This worked for me.

**Comment by magicofdiety** [comment]
Rename the file "STS.EXE" to "sts.exe" worked for me. Thanks.
